### ISSUE TITLE
Using on a CBV?

### ISSUE THREAD

**Issue by 7wonders** [Suor/django-cacheops#101]
Is there a way to use on a class based view? I have tried all the usual methods overriding dispatch, as_view etc and keep getting "The response content must be rendered before it can be pickled". Any example i am missing?

**Comment by Suor** [comment]
`TemplateResponse`s is supported naturally since 2c10a0f501530507cbb23b2bcb81abff453d853a. So this is now sifficient:
```python
cached_view = cached_as(SomeModel)(YourView.as_view())
```
