### ISSUE TITLE
Suggestion: debug_toolbar plugin

### ISSUE THREAD

**Issue by ScottEAdams** [Suor/django-cacheops#102]
Title says it all really. It would be great with a debug_toolbar plugin for seeing when the cache is getting hit. Similar to the default cache toolbar and https://github.com/ross/memcache-debug-panel

**Comment by kichik** [comment]
I think this will come for free if cacheops uses Django's Cache Framework. Django Toolbar already has a panel that summarizes the results of that framework. Is that something you would consider including in cacheops?

**Comment by Suor** [comment]
Cacheops doesn't use Django cache framework. And it can't do it since it requires redis-specific oeprations like running Lua scripts.
