### ISSUE TITLE
Django on command "migrate" or "syncdb" small problem

### ISSUE THREAD

**Issue by ebertti** [Suor/django-cacheops#125]
When run the `migrate` or `syncdb` the cache maybe be a problem.

In my case, has return a empty value on check if need to create a permission of django.

In this scenary, I was testing django migrate, creating and destroing the database

**on file django/contrib/auth/management/__init__.py on line 91 of Django 1.7.1**
``` python

    # all_perms allways return None, but in second time,
    # on migration, need if has or not data in databse
    all_perms = set(Permission.objects.using(using).filter(
        content_type__in=ctypes,
    ).values_list(
        "content_type", "codename"
    ))

    # have only application to create permission on database
    perms = [
        Permission(codename=codename, name=name, content_type=ct)
        for ct, (codename, name) in searched_perms
        if (ct.pk, codename) not in all_perms
    ]
````
in second time running, to evolve the models of app, this was return to create data that was already create, but not cached on django-cacheops.

Sorry for my bad english...

**Comment by pySilver** [comment]
@Suor I hit the same problem. Config:

```python
CACHEOPS = {
    # skip my apps as not relevant for this issue.

    ### THIRD PARTY APPS ###
    'auth.*': {'ops': 'all'},
}
```
My installed apps contains https://github.com/ottoyiu/django-cors-headers. For the first time syncdb runs ok (creates a table, auth.permissions, django content types. For the second call ./manage.py syncdb fails with:

```
django.db.utils.IntegrityError: (1062, "Duplicate entry '56-add_corsmodel' for key 'content_type_id'")
```

If I set CACHEOPS to FAKE, everything works fine. Also disabling cache for 'auth' app also fixes issue.

**Comment by Suor** [comment]
Any chance you can cut your project down into some demo one with the problem?

**Comment by pySilver** [comment]
@Suor sure, here it is: https://github.com/pySilver/test_cacheops

any subsquent calls to a ./manage.py syncdb would result into the same integrity erros unless you disable cacheops or remove 'auth' app from cacheops settings.

**Comment by Suor** [comment]
Fixed it finally. Many thanks for following this rabbit hole to the very bottom :)
