### ISSUE TITLE
better docs

### ISSUE THREAD

**Issue by pySilver** [Suor/django-cacheops#129]
Hi!

Can you please describe the roles of supported operations? Fetch vs Get confuses me. What is the difference?

**Comment by Suor** [comment]
Since this was the only case of confusion, I decided to not complicate docs and leave it as is.

**Comment by ckeeney** [comment]
I know this is an old issue but I did have to come here to find the difference between `.get` and `.fetch`.

**Comment by Suor** [comment]
It's actually explained now in the start of usage example.
