### ISSUE TITLE
How to invalidate objects in queryset when using bulk update? 

### ISSUE THREAD

**Issue by whitefoxx** [Suor/django-cacheops#136]
No signals were send by django update method, right? so, how to invalidate the objects when using 
```python
model.objects.filter(**kwargs).update(**kwargs)? 
```
I wrote this method to invalidate the objects return by filter method explicitly, will it work?
```python
def nocache_update(qset, **kwargs):
    from cacheops import invalidate_obj
    for obj in qset.iterator():
        try:
            invalidate_obj(obj)
        except:
            pass
    # update must behind invalidate obj
    n = qset.update(**kwargs)
    return n
```
And call this method as follow:
```python
qset = model.objects.filter(**kwargs)
nocache_update(qset, **kwargs)
```

**Comment by Suor** [comment]
This will kind of work, but could be very slow. Also, you should update first, invalidate next, and no need to catch all exceptions:
```python
from cacheops import invalidate_obj

def invalidated_update(qs, **kwargs):
    n = qs.update(**kwargs)
    for obj in qs.iterator():
        invalidate_obj(obj)
    return n
```

If it's too slow you can drop cache for the whole model:
```python
from cacheops import invalidate_model

qs = ...
qs.update(**kwargs)
invalidate_model(qs.model)
```

**Comment by whitefoxx** [comment]
Thank you for your answer. 
It is still a little confusing for me, why update first and invalidate next. In my understanding, the update method will modify even remove some of the objects in qs. If an object was contained in qs before and then removed after update operation, how can I invalidate this object since it's no longer in qs?

**Comment by Suor** [comment]
If you invalidate first and update second you get a race: some other process can come just in the meantime and cache something. If you are worrying about objects get removed from a set you are querying, which is a valid concern if your fields you filter by and fields you update intersect, you can query objects, then make an update and then invalidate objects:
```python
def invalidated_update(qs, **kwargs):
    list(qs) # fill queryset cache
    n = qs.update(**kwargs)
    for obj in qs: # iterate by queryset cache
        invalidate_obj(obj)
    return n
```

**Comment by rattrayalex** [comment]
Can this example be added to the documentation? I think it's a very important one.

**Comment by Suor** [comment]
Handled with `.invalidated_update()` now.
