### ISSUE TITLE
Configuring cacheops with a redis URL that contains a password?

### ISSUE THREAD

**Issue by njamaleddine** [Suor/django-cacheops#140]
How do you enter a redis URL that contains a password for authentication?

**Ex:**
`'redis://password@localhost:6959'`

I've tried passing in the password in the `settings.py` in the `CACHES` dictionary without any luck.

<pre>
REDISTOGO_URL = os.environ.get('REDISTOGO_URL', 'redis://localhost:6959')
redis_url = urllib.parse.urlparse(REDISTOGO_URL, None)

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': '%s:%s' % (redis_url.hostname, redis_url.port),
        'OPTIONS': {
            'DB': 1,
            'PASSWORD': redis_url.password,
        }
    }
}
</pre>

Similar issue to: https://github.com/Suor/django-cacheops/issues/60

**Comment by Suor** [comment]
Cacheops doesn't accept URLs, has nothing to with neither redistogo nor `CACHES` setting. You are refering an issue, which was also created here erroneously.
