### ISSUE TITLE
Question: Handling of migrations

### ISSUE THREAD

**Issue by EmilStenstrom** [Suor/django-cacheops#142]
Is this the right place to ask questions?

How does cacheops handle database migrations? If I do a migration that adds a new field to a model, will that whole table be invalidated? Or do you do a integrity check on the returned data and discard it if it doesn't match the returned data? Or is this my concern, so I should make sure to clear the whole cache for each deploy?

**Comment by Suor** [comment]
It's ok to ask questions here, but [gitter chat](https://gitter.im/Suor/django-cacheops) can, however, offer more interactivity.

Cacheops integrates all field names and types as part of cache key. So you can't get broken data from cache nor you need to manually flush it. So old data hangs in a cache until timeout exceeded or it's invalidated. This works great with rolling deployments, but cache size can grow during switch.

**Comment by EmilStenstrom** [comment]
Excellent! Thanks.
