### ISSUE TITLE
Performance tip about django-pickling still relevant?

### ISSUE THREAD

**Issue by Bartvds** [Suor/django-cacheops#146]
The readme mentions `django-pickling` to optimise unpickling, but when we try it it errors as it's still Python3, and the code itself went without changes for 3 years.

So we wondered: is this still a valid optimization?

**Comment by Suor** [comment]
Yes, it's relevant. It never changed 'cause it never needed to change. It doesn't work under Python 3 now, but could be easily adapted. Most probably just changing `itertools.izip()` to builtin `zip()` will work.
