### ISSUE TITLE
Invalidation during deleting not cached proxy model

### ISSUE THREAD

**Issue by kosmos342** [Suor/django-cacheops#148]
I have one cached model and another not cached proxy model(used only in admin). Object still in cache after deleting proxy object.

**Comment by Suor** [comment]
Can you create a test?

**Comment by kosmos342** [comment]
Done

**Comment by Suor** [comment]
Fixed in 723724fac91c719897fcdbf9be296f1611eb5e9c

**Comment by Suor** [comment]
Just to let everyone interested know: there is complementary bug - if you cache a proxy and delete/change non-cached base. This one is fixed for Django 1.7+. Will probably never be fixed for older Djangos.
