### ISSUE TITLE
When does this not do what I want?

### ISSUE THREAD

**Issue by rattrayalex** [Suor/django-cacheops#150]
Hi, 

If I just dropped this into my settings: 

```py
CACHEOPS = {
    '*.*': {'ops': 'all'},
}
```

What would be the surprises that would bite me? What would I do to prevent them?

The only one that's obvious to me is bulk updates (solution documented well here: https://github.com/Suor/django-cacheops/issues/136). What are the other ones? What are the solutions?

You touch on these a bit in CAVEATS but I still don't feel like I have a good answer to the questions "when should I use or not use cacheops", and "what are the solutions to common "problems". 

I'm sure you have a very good feel for the answers to these questions. Could you put them in the README?

**Comment by Suor** [comment]
Your questions is very general, but I will try to do the best thing I can.

**I just dropped ... What would be the surprises that would bite me?**. First, you forgot `timeout`, it's not optional. Second, you will cache everything, probably, sometimes when you don't need that or expect. Third, you can run into situation when some cache won't invalidate, most known is mass updates. 

**What would I do to prevent them?** Not sure you can prevent everything in bulk. You can minimize possible issues, by using more granular settings or even manual caching. My own strategy is using automatic cache for helper/utility models - categories, cities, tags (everything that is rarely changed) and explicit caching (`.cache()` method) for everything else I need to cache. You can also read about [how cacheops works](http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/), proper undertanding will reduce any issues.

**when should I use or not use cacheops**. You should use it if:
- you are going to cache many different queries, functions and/or template fragments,
- don't want to write too much cache logic,
- want granular event-driven invalidation.

 You should not use it if:
- you are ok with table level invalidation (johnny-cache will work for you),
- cache only a few things with simple invalidation logic (just use built-in cache),
- not ok with using redis.

**what are the solutions to common "problems"**. A question is to broad, I can only recommend reading README.

**Comment by rattrayalex** [comment]
Thanks so much for your quick answer! I know this is a tricky one =)

> you can run into situation when some cache won't invalidate, most known is mass updates.

Right... what are the others? Unknown situations when the cache won't invalidate are *very scary* - if I don't know all those situations, I just can't use this library. I do know another example would be updates that enter the database without passing django. 

Describing your own strategy could be a wonderful thing to do in the Readme =) as well as - why don't you automatically cache things that are more frequently changed at the settings level? (the docs make it look like this is the recommended way of doing things). 

It would also be terrific if you could link to that article on the Readme, as reading through it... I really have no idea how cacheops works - and I certainly agree it's a very important thing. 

Then when to use / when not to use are great - would be awesome to have them in the readme as well! If you'd like, I'd be happy to submit a PR with these changes.

**Comment by Suor** [comment]
Circumstances leading to not invalidating something is described in CAVEATS 3, 4 and 7. I don't know of other ones.

I am not sure this belongs to README.

**Comment by rattrayalex** [comment]
Well, those and race conditions involving transactions ;-)

Would a PR be welcome? If you're not sure now, you could decide then? I want to use cacheops, and I want a lot of other people to use cacheops too - but as you say, cache invalidation is one of the hardest things in computer programming, and I think folks need to understand the tradeoffs and caveats quite well before diving in. Maybe I'm just more conservative than average. 

The numbered list on the readme was insufficient for me, as-is. Maybe that's an IQ issue on my end, but my hunch is it has to do with the fact that I haven't yet implemented automatic cache invalidation before ;-)

Perhaps I'm being lazy - after all, I'm not digging in and reading the source, which I otherwise feel I would need to do. But I don't think people should be required to read the source before even deciding if this library is the right tool for them.

**Comment by Suor** [comment]
You are probably a lot more cautioius than most people, I think so 'cause nobody asked that questions before and cacheops has already 4 year history and plenty of users.

I will let this issue hang with a "discussion" label for now.
