### ISSUE TITLE
KEY_PREFIX

### ISSUE THREAD

**Issue by vartagg** [Suor/django-cacheops#152]
Hello. What do you think about possibility of adding KEY_PREFIX param, which would be left-concatenated to all cache keys? This gives the opportunity to use only one redis database as single cache store of all web-applications on a server. It's very helpful when there are about 10-15 web-applications on one server (or all of them on different servers, but using only one Redis instance placed on separate server). So, support of 10-15 Redis databases can be very painful in this case and using of key prefixes can be excellent solution.

**Comment by Suor** [comment]
This could be useful, however implementation would be far from simple. You will need to add prefix everywhere and pass (or compile it) into lua scripts too. 

You are probably having very special use case. For most users using separate redis databases should be perfectly ok. Not sure I want to complicate code significantly for such a rate use case.

**Comment by Suor** [comment]
An additional limitation would be inability to invalidate everything for single app, like `invalidate all` management command does.

**Comment by vartagg** [comment]
Ok, I'm not very good in LUA and not quite understand how is it integrated with the app. I thought it would be enough to change simple.CacheKey.make method  - to concatenate ``KEY_PREFIX`` with ``value`` before call of ``CacheKey(value)``. 
Thanks for explanation!

**Comment by vartagg** [comment]
I previously read incorrect information, that Redis allegedly can only have 16 dbs, but now I found in documentation http://www.rediscookbook.org/multiple_databases.html that this number can be simply modified in redis.conf 
Following this, key prefix isn’t necessarily needed. Thank you for your attention and for cacheops library.
Good luck!
