### ISSUE TITLE
Get access to redis client to send additional commands

### ISSUE THREAD

**Issue by saritasa** [Suor/django-cacheops#155]
Right now
cacheops/simple.py 
line 97, cache = RedisCache(redis_client)

gives us 3 methods get/set/delete, what about getting method such as
cache = RedisCache(redis_client)
cache._get_connection() that will return self.conn

**Comment by saritasa** [comment]
or add a method to proxify all 'unknown' commands to self.conn besides get/set/delete

**Comment by Suor** [comment]
Why do you want that?

**Comment by saritasa** [comment]
so that I can run other commands like lpush, ltrim and work with sets/lists/hashes in my application, without using a different lib and opening a secondary connection to redis. 

Right now I'm using cache.conn.COMMAND to pursue this, but this is kinda hacky way of doing things, I'd prefer a method that will return me connection to redis, instead of relying on redis.conn that may change without notice.

**Comment by Suor** [comment]
First, if you want to use arbitrary redis commands for your own purposes you should create and use separate connection. Using cacheops connection is violation of abstraction. Second, you generally shouldn't write anything to cacheops redis db as it could interfere with its logic.
