### ISSUE TITLE
Is kwargs missing in _cached_as of query.py?

### ISSUE THREAD

**Issue by hcqin** [Suor/django-cacheops#156]
It looks the kwargs is missing when calling the original view functions. For the view functions that need kwargs, it will bring error. Is there any special consideration? 

    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            cache_key = 'as:' + _get_key(func, args, kwargs, key_extra)

            cache_data = redis_client.get(cache_key)
            if cache_data is not None:
                return pickle.loads(cache_data)

            result = func(*args)   #  **kwargs is missing?

**Comment by Suor** [comment]
This is a bug. Weird that nobody finds it earlier.
27 июня 2015 г. 12:22 AM пользователь "hcqin" <notifications@github.com>
написал:

**Comment by hcqin** [comment]
Thanks for the quick confirmation. One more question related to cached view. 

How should we invalidate a simple cached view?

    @cached_view(timeout=number_of_seconds)
    def top_articles(request, category=None):
        # Some costly queries
        return HttpResponse(...)

Is it the same as simple cached function? e.g.
      top_articles.invalidate()

I guess different caches will be built for the same view function with different request data. If we don't pass request data to top_articles.invalidate(), how should we find the proper cache?

**Comment by Suor** [comment]
There is no way to manually invalidate cached view.

**Comment by Suor** [comment]
Fixed the bug and added a way to invalidate cached view in 7258a7e and c18d220 respectively.

**Comment by hcqin** [comment]
Thanks a lot for the quick response!
