### ISSUE TITLE
invalidate_m2m doesn't respect reverse flag

### ISSUE THREAD

**Issue by bourivouh** [Suor/django-cacheops#159]
Hello!
Django's m2m_changed signal have ```reverse``` flag. It indicates which side of the relation is updated (forward or reverse relation). ```instance``` and ```pk_set``` kwargs depend on it. There is a good examples in django docs (https://docs.djangoproject.com/en/dev/ref/signals/#m2m-changed).

Cacheops doesn't respect ```reverse``` flag and allways works as if it have changes from forward model.
Let's get those models from tests:
```
class Label(models.Model):
    text = models.CharField(max_length=127, blank=True, default='')

class Brand(models.Model):
    labels = models.ManyToManyField(Label, related_name='brands')

label = Label.objects.create()
```
Clear all brands for label ```label.brands.clear()```. ```Invalidate_m2m``` will try to find objects for invalidation by condition: ```objects = sender.objects.filter(**{m2m.m2m_field_name(): instance.pk})```. But in this case ```m2m_field_name``` - is 'brand', but ```instance``` - is Label instance. 
This happens for all actions with reverse relation.
If your related models have different type of ids it even can crush your code.

Tests will coming soon.

**Comment by Suor** [comment]
Thanks for tests I'll look into it.

**Comment by Suor** [comment]
Should be fixed, thanks for pointing this out.

**Comment by bourivouh** [comment]
Thanks for fix.
