### ISSUE TITLE
Recalculation of cache not tied to a specific model

### ISSUE THREAD

**Issue by enkitosh** [Suor/django-cacheops#162]
Hi is it correct understanding that if a cached function is not connected to a specific model, and thus has no events/signals to invalidate cache, then cache is refreshed on a timeout?

Say I have this function

    @cached(timeout=60*5)
    def do_foo():
        print("foo")

So this will stay in cache for 5 minutes and once that time is over what happens?
does cacheop re-run do_foo to fill the cache again? or the key will simply be invalidated
and the the cache is refreshed next time someone requires this function?

thank you

**Comment by Suor** [comment]
It's invalidated in 5 minutes, not recached. It's recached next time function is called.

Sorry I am answering so late, you can use gitter chat for questions like this - https://gitter.im/Suor/django-cacheops.

**Comment by enkitosh** [comment]
No problem Suor. Thank you for your answer, yeah this was my conclusion after using this library for few days. Outstanding library btw, I'll check on gitter next time for questions :+1:
