### ISSUE TITLE
Strange problem with prefetch_related

### ISSUE THREAD

**Issue by alonisser** [Suor/django-cacheops#169]
I have a model that isn't in the CACHOPS settings (but used to be..)
When I add a prefetch_related clause to the query for some relation for this object
and then try to get the relation (In the serializer) I get this error
```python
  File "/home/alonisser/server/django-warren/top_traders/serializers.py", line 144, in get_daily
    period='day_1').gain
  File "/home/alonisser/server/django-warren/venv/local/lib/python2.7/site-packages/cacheops/query.py", line 447, in get
    return self.get_queryset().inplace().get(*args, **kwargs)
  File "/home/alonisser/server/django-warren/venv/local/lib/python2.7/site-packages/cacheops/query.py", line 319, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/home/alonisser/server/django-warren/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 313, in get
    (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one CurrencyPeriodicGain -- it returned 24!

```
(If this helps then the 24 is the number of CurrencyPeriodicGain that would exists as related to this object if there was no filtering, tracing the code it looks like the filter is ignored. don't know why)
But if I turn off CACHEOPS . everything works as expected. and the get just works..

Any clues what I might be missing here ? (Also cudos for this great and useful project)

versions:
django-cacheops=2.4.2
Django==1.6.11

**Comment by Suor** [comment]
First thing you should check is whether it's a stale cache issue - clear
all cache and then do your request twice.

If this persists then try to make this into test. If it goes away you are
probably having one of CAVEATS situation, read them carefully and add some
`invalide_obj()` call(s).

**Comment by alonisser** [comment]
I checked and run the "invalidate all" command and it still happens (in my tests also..)
I can't find a place in CAVEATS describing that problem and I really fail to understand why should Cacheops influence an uncached queryset? I'll try to write a test

**Comment by alonisser** [comment]
Hmm, looks like writing a test for this would be quite hard - maybe you got an idea what might be the problem before that?

**Comment by Suor** [comment]
First thing you should know that `.prefetch_related()` does separate queries, so if you have something like:
```python
# queryset
SomeModel.objects.filter(...).prefetch_related('currency_periodic_gain')

# settings
CACHEOPS = {
    'app.somemodel': None,
    'app.currencyperiodicgain': {'ops': 'all'}
}
```
Then Django will do 2 requests, one on `SomeModel` not cached and one on `CurrencyPeriodicGain` cached.

**Comment by Suor** [comment]
Seconf it's hard to say more not seeing your queryset and model definitions.

**Comment by alonisser** [comment]
1. currencyperiodicgain: not in cacheops settings at all, should it be explicit None?
The models (cleared for brevity)

```python
class Trader(model):
    account = OneToOneField('performance.AccountPerformance', related_name='+', null=True, blank=True, on_delete=models.SET_NULL)

class AccountPerformance(model):
    pass

class CurrencyPeriodicGain(model):
   class Meta:
        unique_together = (('entity_id', 'currency', 'period'),)

       currency = CharField(max_length=3, db_index=True)
       period = CharField(max_length=10, db_index=True)
       entity_id = CharField(max_length=40, db_index=True)
       gain = DecimalField(max_digits=12, decimal_places=4, default=0, db_index=True)
       account = ForeignKey(AccountPerformance, related_name='currency_periodic_gains', null=True)
```

Where there are  24 CurrencyPeriodicGain objects for each AccountPerformance.

When I add a prefetch_related clause to the queryset
```python
queryset.prefetch_related('performance_account__currency_periodic_gains')
```

And Later in a serializer do:

```python
obj.performance_account.currency_periodic_gains.get(currency=self.context['currency'],
                                                                   period='day_1')
```
the get fails with the 24 results . I checked the queryset and looks like the get just doesn't filter and return an 'all' but if I remove the prefetch_related clause everything works.

And as I said, none of those models (Trader, PerformanceAccount, CurrencyPeriodicGain) are not defined in the CACHOPS settings

**Comment by Suor** [comment]
Looks like we'll need a test after all ;)

**Comment by alonisser** [comment]
So no need for a test? You found the problem?

:)

**Comment by Suor** [comment]
Test turned up pretty simple.

**Comment by alonisser** [comment]
Would it be in the next release?

**Comment by Suor** [comment]
Yes
