### ISSUE TITLE
Problem with non auto increment composite primary key

### ISSUE THREAD

**Issue by Novarg** [Suor/django-cacheops#170]
Seems i have a problem with saving of unmanaged model that have composite primary key set.
When i save such model cacheops trying to fill `_ojd_objs` list in `_pre_save` method by pk only.
But in my case p2 field (that is part of composite PK) can be non unique itself it's unique only in conjunction with others.
Is there any workaround for such cases except turning off cacheops for that model completely? 

I do understand that cacheops can't just "know" how to properly fetch such models but maybe 
you can fetch models by few params in case if model's `primary_key` field contained in `unique_together` meta option and field isn't auto increment?

Model example:
```python
class MyModel(models.Model):
    p1 = models.IntegerField(default=0)
    p2 = models.CharField(max_length=12, primary_key=True)
    p3 = models.IntegerField(default=0)
    
    class Meta:
        db_table = u'sometable'
        unique_together = (('p1', 'p2', 'p3'), )
        managed = False
```

Table:
```
CREATE TABLE `sometable` (
  ...
  PRIMARY KEY (`p1`,`p2`,`p3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

When i'm saving such model:
```python
File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/django/db/models/base.py", line 486, in save_base
    signals.pre_save.send(sender=origin, instance=self, raw=raw, using=using)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/cacheops/query.py", line 362, in _pre_save
    _old_objs[get_thread_id(), sender, instance.pk] = sender.objects.get(pk=instance.pk)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/cacheops/query.py", line 424, in get
    return self.get_queryset().inplace().get(*args, **kwargs)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/cacheops/query.py", line 316, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/Users/novarg/work/python/py27dj14-env/lib/python2.7/site-packages/django/db/models/query.py", line 368, in get
    % (self.model._meta.object_name, num, kwargs))
MultipleObjectsReturned: get() returned more than one MessageRecipient -- it returned 2! Lookup parameters were {'pk': 'KYd65PytAGrw115'}
```

**Comment by Suor** [comment]
But primary key should by definition be unique, you are doing extremely fishy thing by declaring it primary key, knowing it's not. You could try patch this particular problem by providing `pk` property on your model:
```python
class MyModel(models.Model):
    @property
    def pk(self):
        return (self.p1, self.p2, self.p3)
```
It could, however, break something else. Then you may just clone cacheops and patch it. As Django does not support composite primary keys I don't see a good way for cacheops to support this generally. 

Even if you deal somehow with cacheops, e.g. using patched version, you'll still have issues eventually with other packages and with Django itself. The best solution is just adding real unique primary key, it doesn't matter whether it would be autoincremented or not, you may even make it calculated, like:
```python
class MyModel(models.Model):
    def save(self, ...):
        if not self.pk:
            self.pk = '%s.%s.%s' % (self.p1, self.p2, self.p3)

        super(MyModel, self).save(...)
```

**Comment by Novarg** [comment]
> As Django does not support composite primary keys I don't see a good way for cacheops to support this generally

Well i can't disagree with that. Lack of composite PK support in Django is initial prob.

Thanks for your support, i think i will avoid direct save and will use ```.filter().update()``` to not trigger any signals and then manually invalidate necessary objects.
