### ISSUE TITLE
Option to temporary disable cacheops

### ISSUE THREAD

**Issue by generalov** [Suor/django-cacheops#175]
I want to disable the cacheops caching in the test configuration. I found in the git history the `CACHEOPS_FAKE=True`, but I note it was removed. I tried setting CACHEOPS to the different values: 
```
CACHEOPS = None
CACHEOPS = {}
CACHEOPS = {'*.*': None}
CACHEOPS = {'*.*': {'timeout': 0}}
```
but then I got exceptions. 
Why the CACHEOPS_FAKE was removed and how to disable the cacheops now?

**Comment by Suor** [comment]
What exceptions do you get? And why do you want to disable caching during testing?

**Comment by Suor** [comment]
I removed `CACHEOPS_FAKE` because was unaware if anyone is using it, it was also a hustle supporting it.

**Comment by generalov** [comment]
I need to count the number of queries from views in the case of the cold start. Therefore I want to disable the caching at all. But I need the `cacheops` app is present because of views render templates with cacheops template tags.

CACHEOPS = None

This exception I've got running `manage.py runserver`:
```
File "/home/vagrant/.virtualenvs/.../cacheops/conf.py", line 92, in prepare_profiles
    for app_model, profile in ops.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

These exceptions I've got in the runtime.

CACHEOPS = {}
```
File "/home/vagrant/.virtualenvs/.../cacheops/query.py", line 175, in cache
    self._require_cacheprofile()
  File "/home/vagrant/.virtualenvs/.../cacheops/query.py", line 123, in _require_cacheprofile
    % (self.model._meta.app_label, get_model_name(self.model)))
ImproperlyConfigured: Cacheops is not enabled for account.country model.
If you don't want to cache anything by default you can configure it with empty ops.
```

CACHEOPS = {'*.*': None}
```
File ".../models.py", line 112, in sorted_by_firms
    return qs.cache(timeout=86400)  # 24 hours
  File "/home/vagrant/.virtualenvs/.../cacheops/query.py", line 175, in cache
    self._require_cacheprofile()
  File "/home/vagrant/.virtualenvs/.../cacheops/query.py", line 123, in _require_cacheprofile
    % (self.model._meta.app_label, get_model_name(self.model)))
ImproperlyConfigured: Cacheops is not enabled for account.country model.
If you don't want to cache anything by default you can configure it with empty ops.
```

What is the `empty ops`?

CACHEOPS = {'*.*': {}}}
```
File "/home/vagrant/.virtualenvs/.../cacheops/conf.py", line 122, in prepare_profiles
    'You must specify "timeout" option in "%s" CACHEOPS profile' % app_model)
django.core.exceptions.ImproperlyConfigured: You must specify "timeout" option in "*.*" CACHEOPS profile
```

CACHEOPS = {'*.*': {'ops': []}}}
```
File "/home/vagrant/.virtualenvs/.../cacheops/conf.py", line 122, in prepare_profiles
    'You must specify "timeout" option in "%s" CACHEOPS profile' % app_model)
django.core.exceptions.ImproperlyConfigured: You must specify "timeout" option in "*.*" CACHEOPS profile
```

CACHEOPS = {'*.*': {'ops': [], 'timeout': 0}}

It seems it works. :) I think I got an exception from the `redis` module about an invalid timeout value, but now I can't reproduce it. May be this is the solution?

**Comment by generalov** [comment]
Oh, no. I reporduce the exception with the `{'timeout': 0}` too. 
```  
File "/home/vagrant/.virtualenvs/.../redis/connection.py", line 582, in read_response
    raise response
ResponseError: Error running script (call to f_c54d7c8aeb17b974055d5eb1f1a08f0dafcaaf81): @user_script:8: ERR invalid expire time in SETEX 
```

**Comment by Suor** [comment]
Hmm, not sure if counting queries in tests is a good idea. App tests should check app logic not cache/db behavior.

**Comment by Wrhector** [comment]
As a note I use CACHEOPS_FAKE when developing and debugging

**Comment by generalov** [comment]
Thanks, but I noted above the CACHEOPS_FAKE was removed in the last releases. Anyway It didn't cover the full QuerySet interface and caused the distinct set of issues.

The cacheops makes assertions by [TransactionTestCase.assertNumQueries](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries) unstable. The cacheops itself has a code to omit the caching, but I didn't found how to control that from the outside.

**Comment by Suor** [comment]
The cacheops doesn't make assertions about `assertNumQueries` only its tests. So you shouldn't care unless you develop cacheops itself.

**Comment by Suor** [comment]
I think now that this thing should be implemented the same way as `no_invalidation` decorator/context manager. 

@generalov are you up to it?

**Comment by generalov** [comment]
> The cacheops doesn't make assertions about assertNumQueries only its tests. So you shouldn't care unless you develop cacheops itself.

OMG. =) I use assertNumQueries and I do not develop cacheops.  
I've thought about a some sort of a simple [toggle](http://django-cachalot.readthedocs.org/en/latest/quickstart.html?highlight=disable#cachalot-enabled), but it seems an obstruction. Then I've just removed cacheopts from the testing configuration.

**Comment by Suor** [comment]
Again, cacheops do not interfere with assertNumQueries, so you can use it
with cacheops freely.

For a switch, you can look how no_invalidation one is implemented and make
some no_cache switch by analogy. I'll look into this myself in 2-3 weeks,
but for now I'm on vacation :)

**Comment by rhblind** [comment]
Hi,
Just want to report that I've got big problems as well by running my current test suite with cacheops enabled. I've got all sort of weird behaviour, haven't really digged into them so it might be a bit premature to blame cacheops for them all, but all I know is that the test suite runs without errors if I remove cacheops from `INSTALLED_APPS`.

My solution to disabling cacheops during tests is to create a mixin class (or a custom `TestCase`) with the following code.

```python

from django.test import modify_settings

class NoCacheMixin(object):
    """
    TestCase mixin class for disabling django-cacheops.
    """

    def setUp(self):
        self.patched_settings = modify_settings(
            INSTALLED_APPS={
                "remove": "cacheops"
            }
        )
        self.patched_settings.enable()

    def tearDown(self):
        self.patched_settings.disable()
```

**Comment by Suor** [comment]
Added `CACHEOPS_ENABLED` setting in https://github.com/Suor/django-cacheops/commit/2f5dd820d5594483c3c8098f0179664d3b385d3e

**Comment by generalov** [comment]
Thanks!

**Comment by pashinin** [comment]
I updated cacheops but when I set `CACHEOPS_ENABLED=False` it still uses cache. Only if I remove some records from `CACHEOPS` dict I have SQL queries in django debug toolbar again. What can be wrong?

**Comment by Suor** [comment]
Do you use master branch or published version? CACHEOPS_ENABLED only
supported on master branch.

**Comment by pashinin** [comment]
Latest with `pip`, my bad. Will you release it soon?

**Comment by Suor** [comment]
I plan to
