### ISSUE TITLE
django-pickling does not appear to be faster (advice may be out of date)

### ISSUE THREAD

**Issue by catskul** [Suor/django-cacheops#187]
Django-pickling which has been dormant for 4 years at first glance does not appear to offer a performance advantage.

I tested by creating 1500 objects and running `prun foo=list(TestObject.objects.all().cache()` a bunch of times. cPickle seems to run regardless, and timings seem to be the same.

Not sure if there's a more formal test somewhere, but the django-pickling advice may be out of date

**Comment by catskul** [comment]
Hmm, tried it again and may have been wrong. It appears that a call to `invalidate all` between tests may be necessary

**Comment by Suor** [comment]
The right way to test it is using pickle/unpickle directly. Also,
TestObject should have many fields for better effect.
