### ISSUE TITLE
redis master/slave connection support?

### ISSUE THREAD

**Issue by lishenzhi** [Suor/django-cacheops#188]
does the cacheops_redis support redis master/slave set up?

**Comment by Suor** [comment]
It doesn't. 

Maybe I'll be more helpful if you describe your situation and say why do you want it to use master/slave.

**Comment by ttyS15** [comment]
May be you will be interested in simple patch

https://github.com/ttyS15/django-cacheops/commit/dae088d07446468fe9f3d8853ec761e000f01610

**Comment by Suor** [comment]
Not sure this is possible with simple patch. I consider
django-db-router-like approach.

**Comment by lishenzhi** [comment]
@Suor i am trying to use cacheops with redis on AWS. I have a replication group for redis, and my redis config looks like:

CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                "redis://master:6379/1",
                "redis://replica1:6379/1",
                "redis://replica2:6379/1",
            ],
            "OPTIONS": { ... }
    } }

is it possible for cacheops to use the CACHES config directly, instead of using CACHEOPS_REDIS?

**Comment by Suor** [comment]
@lishenzhi using `django_redis.cache.RedisCache` and `CACHES` setting won't work. cacheops uses its own `CACHEOPS_REDIS` setting and its own redis client instance. Using Django caching framework is out of question - it doesn't support all required capabilities. Pretending to use it by only allowing `django_redis.cache.RedisCache` is confusing and have no benefits: it adds nothing useful atop pure redis client.

The approach I support for master slave is using router function. You can look up discussions in #121 and #35.
