### ISSUE TITLE
Invalid model objects being fetched

### ISSUE THREAD

**Issue by subramanyamVemu** [Suor/django-cacheops#190]
When multiple instances of the same project are hosted on a single machine and accessed then the model objects of the other instance are showing up 

Tried with the key_prefix in CACHES of settings.py but didnt work

**Comment by Suor** [comment]
`CACHES` is not used by cacheops, it uses `CACHEOPS_REDIS`. You should use separate redis instances (recommended) or separate redis dbs for separate projects.
