### ISSUE TITLE
Django templatetag cached_as timeout not working

### ISSUE THREAD

**Issue by Gillingham** [Suor/django-cacheops#198]
Seems that trying to set the timeout to 0 doesn't actually work.
Using:
```
{% cached_as object_foo 0 'template_foo' %}
```
Results in a key being created with a ttl of 900. I'm confirming this via the redis-cli looking for the key, checking the contents of the `as:<stuff>` to verify it's the cached template, and running ttl that key.
If I set the cached_as to a non-0 value, it the ttl gets set accordingly.

This is happening with django-cacheops 2.4.3, Django 1.8.13, and redis 3.0.7

I do have `'*.*': ('all', 60*15)` in my Django settings, which is where I assume the 900 is coming from, but cached_as should override that default.

**Comment by Suor** [comment]
0 in this tag means use default timeout, this is documented.

**Comment by Gillingham** [comment]
Is there no option for an infinite timeout?

**Comment by Suor** [comment]
You can just use very big number.
