### ISSUE TITLE
django debug_toolbar panel

### ISSUE THREAD

**Issue by genxstylez** [Suor/django-cacheops#199]
Hi, 
I like your work but I was wondering if we can have debug_toolbar panel to keep track of the performance.

found a reference done by cachealot https://github.com/BertrandBordage/django-cachalot/blob/master/cachalot/panels.py

maybe we can reference this. 

I can help you on this, but maybe direct me to the functions.

Cheers

**Comment by Suor** [comment]
See #102. The summary is that I encorage somebody to do that as separate project. I can answer questions and even consider making instrumental changes to cacheops.
