### ISSUE TITLE
Persistent errors after V3 upgrade

### ISSUE THREAD

**Issue by Koed00** [Suor/django-cacheops#203]
I keep seeing these errors after updating to version 3 with Django 1.10 

```
AttributeError: Can't get attribute 'simple_class_factory' on <module 'django.db.models.base' from '/app/.heroku/python/lib/python3.5/site-packages/django/db/models/base.py'>
```
When I run `python manage.py invalidate app_name` the errors go away.
But they re-appear with every deploy, forcing me to clear the cache after every deploy to prevent a crashing server.

Any idea what's going on here?

**Comment by Suor** [comment]
Try `python manage.py invalidate all` if that doesn't help then post an error with full stacktrace, please.

**Comment by Koed00** [comment]
Yes , that fixed it. Thanks!
