### ISSUE TITLE
How to force cache usage even if it's invalidated

### ISSUE THREAD

**Issue by lolorama** [Suor/django-cacheops#204]
I have issue on high-load project. I'm caching heavy sql query and when it invalidates, multiple requests missing cache and making query to database. This push cpu load to 100%.

I want to make all heavy queries in background to evaluate cache only once and force in request to use only cached data even if it's already invalidated. Is it possible?

if not can we somehow force to recache query?

**Comment by Suor** [comment]
You are probably experiencing dog-pile effect: your query is recalculated by several processes simultaneously and thus you get high CPU load. There is an [unfinished and outdated pull request](https://github.com/Suor/django-cacheops/pull/134) to fix this. Implementing it would be proper solution.

To quickfix your issue you can somehow prepopulate and refresh it manulally when something happens. I.e. do not use cacheops or use simple cache with big timeout and manual refresh:

```python
@cached(timeout=24*60*60*365)  # a year
def heavy_query():
    return ... # Some costly queries

def handle_change(...):
    ...  # do updates
    heavy_query.key().set(heavy_query())  # update cache
```
You can also update cached value in background if it's ok to serve stale data for a short while.

**Comment by lolorama** [comment]
Thanks! That's it.
