### ISSUE TITLE
Cache does not seem to be working

### ISSUE THREAD

**Issue by tawanda** [Suor/django-cacheops#205]
Hello, i am monitoring my local redis and nothing seems to be getting cached

i am running django rest framework and i have a simple endpoint that lists all image files no matter how many times i hit the endpoint nothing is cached

here are my settings

my image models are in `apps.imagefiles.models`

```
# ############ CACHE SETTNGS
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/5",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# ######## END CACHE SETTINGS ##########


# ####### CACHEOPS #####################

CACHEOPS_ENABLED=True

CACHEOPS_REDIS = "redis://127.0.0.1:6379/6"

CACHEOPS = {
    # Automatically cache any User.objects.get() calls for 30 minutes
    # This includes request.user or post.author access,
    # where Post.author is a foreign key to auth.User
    'apps.accounts.accounts.user': {'ops': 'get', 'timeout': 60*35},

    # Automatically cache all gets and queryset fetches
    # to other accounts models for an hour
    'apps.accounts.accounts.*': {'ops': ('fetch', 'get'), 'timeout': 60*60},

    # Cache gets, fetches, counts and exists to all the following apps
    # 'all' is just an alias for ('get', 'fetch', 'count', 'exists')
   
    'apps.imagefiles.*': {'ops': 'all', 'timeout': 60*60},
   

    # Enable manual caching on all other models with default timeout of an hour
    # Use Post.objects.cache().get(...)
    #  or Tags.objects.filter(...).order_by(...).cache()
    # to cache particular ORM request.
    # Invalidation is still automatic
    '*.*': {'ops': (), 'timeout': 60*60},
}
# ####### CACHEOPS #########
```

Thanks for the assist

**Comment by Suor** [comment]
You should not use full app paths in CACHEOPS setting, just
"appname.modelname".

**Comment by tawanda** [comment]
its working now, many thanks

I get this warning in the console however

WARNING py.warnings /Users/tawanda/sandbox/env/eright/lib/python3.4/site-packages/cacheops/query.py:263: RuntimeWarning: Pickled model instance's Django version is not specified.
  return iter(pickle.loads(cache_data))

I installed django-pickling as per your reccomendations

**Comment by tawanda** [comment]
actually dont worry about it, i see its an issue with django-pickling

`https://github.com/Suor/django-cacheops/issues/153`

**Comment by Suor** [comment]
I am aware of this warning, it does no harm. I'll fix it soon.

**Comment by tawanda** [comment]
Thanks for this great lib, all my tests pass and monitoring redis shows the expected results
