### ISSUE TITLE
Seeing values duplicated in redis-cli monitor

### ISSUE THREAD

**Issue by eronaeon** [Suor/django-cacheops#211]
Hi @Suor and thanks a million times for this great piece of software, my question is which I can't be sure whether this is something normal or an issue. When a template fragment is cached, I see two consecutive commands in the `redis-cli monitor` log with the same cached value. For example,
```
1475201463.158820 [1 127.0.0.1:56912] "EVALSHA" "c54d7c8aeb17b974055d5eb1f1a08f0dafcaaf81" "1" "as:e8ab4c0efd7e7d8a1d8065516eb43ade" "BLABLABLABLA"
1475201463.159029 [1 lua] "setex" "as:e8ab4c0efd7e7d8a1d8065516eb43ade" "100" "BLABLABLABLA"
```
Is this something normal or the value is cached twice?

**Comment by Suor** [comment]
It's normal. First is Lua script evaluation, second is actual write command from within the script.
