### ISSUE TITLE
Setting for disabling invalidation in CACHEOPS

### ISSUE THREAD

**Issue by chemary** [Suor/django-cacheops#213]
I use django-cacheops for managing MySQL replication lag, so I set **cache_on_save** to avoid fast reads after write to get stale data.
I think it will be handy to be able to disable invalidation in `CACHEOPS` settings to avoid the `ManagerMixin._post_save()` to make and extra query to get the object, this in conjunction with **cache_on_save** makes code cleaner as no `with no_invalidation:' has to be used .

There is any drawback doing so?
This is my suggested implementation
```python
class ManagerMixin(object):
    ...
    def _pre_save(self, sender, instance, **kwargs):
        # NOTE: it's possible for this to be a subclass, e.g. proxy, without cacheprofile,
        #       but its base having one. Or vice versa.
        cacheprofile = model_profile(instance.__class__)
        no_invalidation_on_save = cacheprofile.get('no_invalidation_on_save') if cacheprofile else False

        if instance.pk is not None and not (no_invalidation.active or no_invalidation_on_save):
           try:
               _old_objs.__dict__[sender, instance.pk] = sender.objects.get(pk=instance.pk)
           except sender.DoesNotExist:
               pass
```

**Comment by Suor** [comment]
First, `cache_on_save` has nothing to do with neither `pre_save` nor invalidation. Second, your patch doesn't prevent invalidation, it prevents one get request and hurts subsequent invalidation.

What are you trying to achieve? Disable invalidation entirely? Or just skip that request? Why?

**Comment by chemary** [comment]
What I was trying to achieve is do the minor number of read requests to database.
I know it will be dangerous if you do updates to querysets and forguet to do manual invalidation, but if you only do `get()` and `save()` you can work with the object on cache reading it the first time and updating the cache every time that is saved (avoiding the invalidation and database refresh).

**Comment by Suor** [comment]
This is brave microoptimization for very particular scenario, not sure it's generally useful. Not sure whether it's even that necessary for your scenario, gets are fast. And that get can come from cache. So we have:

1. Fetch old state from cache.
2. Invalidate by old and new state, cache is cleared.
3. Write new state to cache.

After proposed change manipulations 1 and 2 will go away (2 maybe even partially). **So no db request is actually saved.** Unless you happen to get race condition between 2-3, but that's rare and only adds single get to db.

I suggest trying with invalidation on first, it may appear to be fast enough.

**Comment by Suor** [comment]
Closing this since original author doesn't appear to be interested anymore.
