### ISSUE TITLE
warch cache

### ISSUE THREAD

**Issue by jankrnavek** [Suor/django-cacheops#214]
Hello,
is there way how to put all objects into cache?
I have a big table with 9 milions records and  i try to do something like
len(Big.objects.all()) but  that doesnt work.
Thank you in advance.
Hanz

**Comment by Suor** [comment]
To add something to cache you can just execute requests you want to cache. So if it's gets then:
```python
for pk in Big.objects.nocache().values_list('pk', flat=True).iterator():
    Big.objects.get(pk=pk)
```

**Comment by Suor** [comment]
**P.S.** If that query proves to be too big you can use `queryset_iterator()` from [handy](https://github.com/Suor/handy):

```python
from handy.db import queryset_iterator

for pk in queryset_iterator(Big.objects.nocache().values_list('pk', flat=True)):
    Big.objects.get(pk=pk)
```
