### ISSUE TITLE
AssertError while check not transaction_state.is_dirty()

### ISSUE THREAD

**Issue by Godod** [Suor/django-cacheops#215]
Hello. I was updated django-cacheops to version 3.1 and now, when I'm using django.db.transaction.atomic() to save model I have AssertError. Error arise on 42 line at query.py file:

```python
assert not transaction_state.is_dirty()
```

Can you explain why cacheops considers that transaction is dirty and how can I avoid this situation?
Thank you.
Using: Python 3.5.2, Django 1.9.11, PostgreSQL 9.5

P.S. Sorry for my bad English
P.P.S PostgreSQL don't support dirty transaction

**Comment by mr-bo-jangles** [comment]
Same issue here

**Comment by Suor** [comment]
Can you please create a test? And post a stack trace for a start. 

Also, did you mean updated to 3.1?

**Comment by Suor** [comment]
And not sure what you meant on PostgreSQL. There is no need of any support from database for this to work.

**Comment by Godod** [comment]
@Suor I will create test tomorrow.

> Also, did you mean updated to 3.1?

Yes. On django-cacheops 3.0.1 version all work normal

**Comment by mr-bo-jangles** [comment]
Yeah I have the same issue, 3.0.1 works, but latest asserts with some
refactoring work you did

**Comment by Godod** [comment]
@Suor I can't reproduce this bug on a clean install (clean install django, redis, cacheops, postgresql). I will try to reproduce, if it's reproduced, again at monday, when I will be at work.

**Comment by Godod** [comment]
Hello again. Here is cut traceback log:

```python
File "/home/godod/PycharmProjects/test_project/test/models.py" in event
  161.             self.save()

File "/home/godod/venv/lib/python3.5/site-packages/django/db/models/base.py" in save
  708.                        force_update=force_update, update_fields=update_fields)

File "/home/godod/venv/lib/python3.5/site-packages/django/db/models/base.py" in save_base
  732.                                   update_fields=update_fields)

File "/home/godod/venv/lib/python3.5/site-packages/django/dispatch/dispatcher.py" in send
  192.             response = receiver(signal=self, sender=sender, **named)

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/query.py" in _pre_save
  414.                 _old_objs.__dict__[sender, instance.pk] = sender.objects.get(pk=instance.pk)

File "/home/godod/venv/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  122.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/query.py" in get
  351.         return qs._no_monkey.get(qs, *args, **kwargs)

File "/home/godod/venv/lib/python3.5/site-packages/django/db/models/query.py" in get
  381.         num = len(clone)

File "/home/godod/venv/lib/python3.5/site-packages/django/db/models/query.py" in __len__
  240.         self._fetch_all()

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/query.py" in _fetch_all
  305.                         self._cache_results(cache_key, self._result_cache)

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/query.py" in _cache_results
  169.         cache_thing(cache_key, results, cond_dnfs, self._cacheprofile['timeout'])

File "/home/godod/venv/lib/python3.5/site-packages/funcy/decorators.py" in wrapper
  26.             return deco(call, *dargs, **dkwargs)

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/redis.py" in handle_connection_failure
  16.             return call()

File "/home/godod/venv/lib/python3.5/site-packages/funcy/decorators.py" in __call__
  43.             return self._func(*self._args, **self._kwargs)

File "/home/godod/venv/lib/python3.5/site-packages/cacheops/query.py" in cache_thing
  42.     assert not transaction_state.is_dirty()

Exception Type: AssertionError at /processing/card/review/
Exception Value:
```

If you want some additional information, please write what information you needed. Thank you

**Comment by Godod** [comment]
And some additional information. If I changed the fields and save with django.db.transaction.atomic, cacheops raise AssertionError on any changed models. If, I remove django.db.transaction.atomic - all is fine. On a clean install I tried to reproduce the bug, but cacheops doesn't raise error

**Comment by Suor** [comment]
As far as I can see transaction becomes dirty inbetween a check at the start of `_fetch_all()` and a call to `cache_thing()`. I see that this is legitimately possible, so I'll probably need to switch assert to return.

However, it would be nice to see the particular reason behind the bug. So can you log all calls to `CursorWrapperMixin` methods [here](https://github.com/Suor/django-cacheops/blob/3.1/cacheops/transaction.py#L78)?

**Comment by Suor** [comment]
**P.S.** as they would be called numerous times you might also want to add markers to the starts of `_fech_all()` and `cache_thing()` fir us to see what calls are going inbetween.

**Comment by Godod** [comment]
Found something, that can help you:
when I changed field and write:

```python
with django.db.transaction.atomic():
    obj.save()
```

Call go to execute function at the CursorWrapperMixin:
![execute function](https://i.imgsafe.org/99312461c3.png)

and mark as dirty transaction, as you can see.

At in_transaction function:
![in_transaction function](https://i.imgsafe.org/9931452672.png)

At is_sql_dirty function:
![is_sql_dirty function](https://i.imgsafe.org/993135fe6c.png)

**Comment by Godod** [comment]
**P.S.** sql - only select fields from db

**Comment by Suor** [comment]
Of course there is select, this saw this from stack trace. The question is
why it marks dirty?

**Comment by Godod** [comment]
@Suor because I have update_at field and check:

```python
'update' in sql or 'insert' in sql or 'delete' in sql
```

found 'update' string in select query and return True.
