### ISSUE TITLE
Make CACHEOPS keys case "insensitive"

### ISSUE THREAD

**Issue by mapher87** [Suor/django-cacheops#216]
conf:prepare_profiles made case insensitive, but conf:model_profile did not

may be "lower()" when getting "app_lable" and "model_name" to make it compatible

**Comment by Suor** [comment]
`model_profile()` is an internal interface same way as `prepare_profiles()`. `CACHEOPS` keys are already case insensitive. Am I missing something?

**Comment by mapher87** [comment]
In my project there has a UPPER_CASED app_label for history reason, and then all models in it can not be configured in CACHEOPS option.
In my opinion, the "prepare_profiles" and "model_profile" should be both matching the lower cased app and model name, or this would be a BUG.
