### ISSUE TITLE
django>=1.10.x

### ISSUE THREAD

**Issue by GuillaumeCisco** [Suor/django-cacheops#217]
Hello,

Just tested last version of django-cacheops and Django 1.10.3.
Steps : 
./manage.py invalidate all
reload server
./manage.py invalidate all

Still it does not work properly, list is not invalidated.

If I run again command `./manage.py invalidate all` list is obviously invalidated but if I want to remove an item, still, list is not invalidated.
Anyone in this case, did I do something wrong?

My settings file is:
```python
CACHEOPS_REDIS = {
    'host':  environ.get('REDIS_HOST', '127.0.0.1'),
    'port': environ.get('REDIS_PORT', '6379'),
    'db': 1,
    'socket_timeout': 4,
}

CACHEOPS_DEFAULTS = {
    'timeout': 60*10  # 10 minutes
}

CACHEOPS = {
    'auth.user': {'ops': 'get'},
    '*.*': {'ops': 'all'}  # caching for all models
}

```

**Comment by Suor** [comment]
You need to be more specific. Whats is the list? Why it should be invalidated? What do you mean by removing an item?

**Comment by GuillaumeCisco** [comment]
Thanks @Suor for your quick response.
I'll try to be more specific.

Just using django-cacheops with django rest framework, so it is an API.
My list refer to a list of items when make a GET requests.
Deleting an item of this list consist of making a DELETE request on an item.
Sorry for misunderstanding.

So I've juste made my test on the Web Browsable API of a django rest framework project.
When I create or delete objects, and after request my list, I got a cached version. Nothing seems invalidated.

Thank you,

**Comment by Suor** [comment]
Cacheops doesn't operate in terms of lists, deletes and so on. I don't know what happens within django rest framework so can't say why it doesn't work. People have used cacheops with django rest framework before with no issues though.

Maybe you have some cache on top of cacheops? You can try executing corresponding queryset in a console before and after change and look if that invalidates.

**Comment by GuillaumeCisco** [comment]
Yes you're right, I think I don't express myself correctly.
When I talk about list, it is related to `MyModel.objects.all()`, it returns a list of items.
As far as I understand, this operation is invalidated when we create/delete an item of this MyModel, right?

I've used django-cacheops with django-rest-framework and had no issues for  the past 3 years :)
Just checked I have no cache on top of caheops and django version 1.9.11 works perfectly with it.
I've just executed the sql query manually on postgresql after adding an item, and the list was well updated, but in my case django-cacheops do not make the request to the db. It returns the cache version :/
If I run `./manage.py shell`, import `MyModel` and query `MyModel.objects.all()`, I get a list correctly updated.
Still... If I reload my page in my browser, the list is not updated, I have to wait the end of the cache_timeout (10min in my case)

**Comment by Suor** [comment]
> As far as I understand, this operation is invalidated when we create/delete an item of this MyModel, right?

Right.

Still looks like extra cache, e.g. browser cache or something. If queryset results are correctly updated then cacheops works, you need to query 2 times, though, before and after the change to really know.

**Comment by GuillaumeCisco** [comment]
Something I still do not understand is that it works perfectly with django 1.9.11, no need to change a thing.
So for now, I'm stuck with django version < 1.10.
I hope someone will have the same issue and will be able to solve it.
I cannot be stuck too long with a older version of django.

**Comment by Suor** [comment]
cacheops should work with Django 1.10. Maybe you also updated django rest framework and cacheops simultaneously?

You can also look into what is happening, what querisets are fetched and what changes are made. Probably, even write a test :).

**Comment by GuillaumeCisco** [comment]
I did not updated django rest framework or cacheops simultaneously...
Only thing I've seen which can be part of the issue, it seems pickling is different in django > 1.10.
Will try to investigate...
Got this error too -> https://github.com/Suor/django-cacheops/issues/203

**Comment by Suor** [comment]
Pickles are expected to fail on major code changes.

**Comment by GuillaumeCisco** [comment]
Ok just found something very interesting :)
I put some breakpoints in the code and remarked with django 1.10.x, signals handlers are not called in django-cacheops code.
https://docs.djangoproject.com/en/1.10/ref/signals/
```
Warning

Many of these signals are sent by various model methods like __init__() or save() that you can override in your own code.

If you override these methods on your model, you must call the parent class’ methods for this signals to be sent.

Note also that Django stores signal handlers as weak references by default, so if your handler is a local function, it may be garbage collected. To prevent this, pass weak=False when you call the signal’s connect().
```
Putting `weak=False` worked!

So line 383 need to be changed :
`signal.connect(receiver, sender=sende)`
to 
`signal.connect(receiver, sender=sender, weak=False)`

I'll make a PR

**Comment by Suor** [comment]
Fixed, thanks.

**Comment by GuillaumeCisco** [comment]
Thank you very much for writing the test! And accepting this fix :)
Hope to see it quickly in a next release :+1:
