### ISSUE TITLE
Race condition when in transaction

### ISSUE THREAD

**Issue by Suor** [Suor/django-cacheops#22]
Data can be invalidated on post_save and recached before actual commit hits the database.

**Comment by rattrayalex** [comment]
How can this be solved?

**Comment by Suor** [comment]
On application level this could be solved by manual invalidation after commit. Adding appropriate `invalidate_obj()` or such. On cacheops level - by monkey patching transaction handling routines.

**Comment by rattrayalex** [comment]
Cool. This seems like a standard caveat - it probably makes sense not to have cacheops solve it for people. But it would be really nice to have this in the docs =)

**Comment by rattrayalex** [comment]
I'd be happy to submit this w/ related changes to readme if you're interested.

**Comment by Suor** [comment]
Cacheops can solve this, I just never really needed this features and overall demand is low. The lack of interest is the primary reason this is not addressed yet.

**Comment by Suor** [comment]
This is finally fixed, thanks to @jhillacre.
