### ISSUE TITLE
django-cacheops breaks django-polymorphic

### ISSUE THREAD

**Issue by mjnaderi** [Suor/django-cacheops#222]
Hi. I installed latest versions of django-cacheops and django-polymorphic:

- python==3.5.2
- django==1.10.3
- django-cacheops==3.1.1
- django-polymorphic==1.0.2

With these versions, django-polymorphic does not work correctly. When I downgrade django-cacheops to 3.1, the problem still exists, and when I downgrade django-cacheops to 3.0.1, the problem goes away. Something in CacheOps 3.1 has broken django-polymorphic.

This is the problem:

Suppose we have following models.

```python
class A(PolymorphicModel):
    pass


class B(A):
    pass


class Z(models.Model):
    a = models.ForeignKey(A)
```

Both A, and B are cached using cacheops, using these settings in settings.py:

```python
CACHEOPS = {
    'myapp.a': {'ops': 'all', 'timeout': 60 * 15},
    'myapp.b': {'ops': 'all', 'timeout': 60 * 15},
}
```

I run following commands in django shell:

```python
>>> from myapp.models import A
>>> from myapp.models import B
>>> from myapp.models import Z
>>> b=B.objects.create()
>>> z = Z.objects.create(a=b)
>>> z2 = Z.objects.get(id=z.id)
>>> type(z.a)
<class 'myapp.models.B'>
>>> type(z2.a)
<class 'myapp.models.A'>
```

As you see, type of z2.a is "A", bit it should be "B". With cacheops 3.0.1, this is the result:

```
>>> type(z.a)
<class 'myapp.models.B'>
>>> type(z2.a)
<class 'myapp.models.B'>
```

**Comment by Suor** [comment]
Have no idea why this is hapening. I can look into it if you provide a test.

But you should be aware that cacheops doesn't support multi-table inheritance in a sense that invalidation could be incomplete with it - https://github.com/Suor/django-cacheops/issues/31.

**Comment by mjnaderi** [comment]
I wrote a failing test for this issue.
