### ISSUE TITLE
PicklingError

### ISSUE THREAD

**Issue by nMustaki** [Suor/django-cacheops#224]
Hello,
we cannot pinpoint when, but we started getting this pickling error : Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
It seems to happen when a save is followed by a get, but I'm not sure. The issue only happens with uwsgi, I cannot reproduce it with python manage,py shell or python manage.py runserver.

Would be great if you had some idea !

Thanks,
Nathan

**Comment by Suor** [comment]
You can't pickle a function if it's not a module attribute, this might be an issue. You might be saving such function into object attribute. You should just examine stack trace carefully and place logging statements strategically.
