### ISSUE TITLE
Please provide test case or examples where django cacheops doesn't work properly

### ISSUE THREAD

**Issue by anuragjain67** [Suor/django-cacheops#227]
Hey,
Can you please provide examples/ test cases for caveats. (I am using 2.4.3)

1. Conditions other than __exact, __in and __isnull=True don't make invalidation more granular
2. Conditions on TextFields, FileFields and BinaryFields don't make it either. One should not test on their equality anyway.
3. Update of "selected_related" object does not invalidate cache for queryset.
4. ORDER BY and LIMIT/OFFSET don't affect invalidation.
5. Conditions on subqueries don't affect invalidation.
6. Aggregates are not implemented yet.

**Comment by Suor** [comment]
These caused little confusion over cacheops 6 year life, so I consider examples an overkill. Yes, they will make things clearer, but this is extra code I am not willing to bring here. I will think of a way to clarify this without adding more code or text.

For now you can read [this post](http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/) on how cacheops works. Or ask specific questions if you are still confused.

**Comment by fdemmer** [comment]
Link to archived post: https://web.archive.org/web/20220115075253/http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/
