### ISSUE TITLE
Issue when sorting conjunctions in DNF

### ISSUE THREAD

**Issue by michalochman** [Suor/django-cacheops#232]
Turns out that there is an issue when querying the same field multiple times when one of the query is for `__isnull=True`.

For example, given we have following models:

    class Site(models.Model):
        domain = models.CharField(max_length=127)

    class Article(models.Model):
        site = models.ForeignKey(Site, null=True)

The following query:

    Article.objects.cache().filter(Q(site__isnull=True) | Q(site__in=[site])).filter(site=site)

fails with `TypeError: unorderable types: int() < NoneType()`. The error happens while sorting conjunctions in `clean_dnf` function:

    map(sorted, cleaned)

where `cleaned` in this case is:

    [[('site_id', None), ('site_id', 1)]]

One way to fix this would be to cast values to strings before comparing them, like that:

    map(lambda l: sorted(l, key=lambda x: str(x)), cleaned)

I will submit PR with the above fix and relevant test case in a minute.

**Comment by Suor** [comment]
```python
Article.objects.cache().filter(Q(site__isnull=True) | Q(site__in=[site])).filter(site=site)
```
is the same as
```python
Article.objects.cache().filter(site=site)
```
So this is non-issue for you.

Thinking a bit more about it I can't see how sane queryset can lead to this. The only possible way is that you have `field=a&field=b` in your query which is stupid.

**Comment by michalochman** [comment]
This was just an example, the actual QuerySet is built dynamically. It also works when not using cacheops so it is clearly a regression.

**Comment by michalochman** [comment]
To clarify, the real world example using the above-mentioned models is this:

One part of the website code could return an ArticleQuerySet based on the Site the User is registered on, the articles returned may be either assigned to a particular site or to all sites (then the site property of the Article is NULL), resulting in:

    qs = Article.objects.filter(Q(site__isnull=True) | Q(site=request.user.site))

Then, let's say that the User wants to further filter the Articles based on the site:

    qs = qs.filter(site=requested_site)

Combining the above we get the following query:

    Article.objects.filter(Q(site__isnull=True) | Q(site=request.user.site)).filter(site=requested_site)

which works perfectly fine using plain Django. Unfortunately, it is not working when cacheops is active due to the above bug.
