### ISSUE TITLE
is_sql_dirty matches on column name

### ISSUE THREAD

**Issue by icereval** [Suor/django-cacheops#234]
Transaction method `is_sql_dirty` matches on strings `update`, `delete` or `insert`. Causing false positives when column names match.

e.g.

`is_deleted`
`delete`
`deleted`

**Comment by Suor** [comment]
Yes it is. This is ok, can cause superficial invalidation but won't hurt logic.

**Comment by icereval** [comment]
In our case loading a User (w/ a column `is_deleted`) out of the database/cache on each authenticated request coupled with using Django's [Atomic Requests](https://docs.djangoproject.com/en/1.10/topics/db/transactions/#tying-transactions-to-http-requests) features causes cacheops to disable itself immediately.

**Comment by Suor** [comment]
I will think about it

**Comment by Suor** [comment]
So my considerations so far:

1. Atomic requests is a stupid idea, which I currently support though.
2. There are rational use cases which could be bitten by this.
3. Even though no logic issues stem from this, certain cases are still completely ruined.
4. Reading user from cache in your example won't really dirty the transaction as long as that sql is not executed. Won't probably help much anyway.

This means just dropping support for atomic requests won't help here :) So we come to the last consideration - regular expressions is slow. I don't like making everything slower, but I'll see what I can do.
