### ISSUE TITLE
Cache is saving the object in presave without the model been in CACHEOPS configs

### ISSUE THREAD

**Issue by leonardoo** [Suor/django-cacheops#237]
i was looking with django debug toolbar, and a object that is not config in CACHEOPS was been searched and added, to the cachelist but this object was not in the cacheops list

**Comment by Suor** [comment]
If `cache_on_save` is set then it will work, ops do not affect this. If that flag is not set then there should be no precaching. 

If you believe this is not how it works now then prove it with the test.

**Comment by leonardoo** [comment]
i figure out why this happend, i use something like this

id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

so this condition is always "instance.pk is not None" is always true in the _pre_save

**Comment by Suor** [comment]
This is irrelevant've
