### ISSUE TITLE
cached_as with kwargs?

### ISSUE THREAD

**Issue by littlehome-eugene** [Suor/django-cacheops#243]
I'd like to cache function result per different kwargs.. 

I tried searching github issues since it seems to me very plausible use cases.

How can we cache function results per different kwargs?

**Comment by Suor** [comment]
If you mean cached function has kwargs and you want cache key to vary on them then it should just work.

**Comment by littlehome-eugene** [comment]
Thank you

**Comment by littlehome-eugene** [comment]
I'd like to use cacheops to cache function results only. (not messing with database queryset caching)

I though using `from cacheops import cached` and using the decorator to method would just do that.  
But I see cacheops in a lot of non-relevant db query in Django debug toolbar.
Below is the only line I added (other than settings.py) with cacheops.  
Why do I see lines such as below for db queries I see in the django debug toolbar panel?

> /home/eugenekim/virtualenvs/reservation/lib/python3.4/site-packages/cacheops/query.py in _fetch_all(295)
>   return self._no_monkey._fetch_all(self)

     def get_winning_seller_id(self):
        
         product = self
         @cached()
         def _get_winning_seller_id(id):
             seller_ids = product.get_seller_ids()
             seller_id = seller_ids.first()
             return seller_id
         return _get_winning_seller_id(product.id)

**Comment by Suor** [comment]
Cacheops patches django QuerySet to check if particular one at hand should be cached. When it's not it's just noop, calls Django default implementation. This code still shows in stacktrace of cause.

I believe you can write your snippet like:
```python
@cached
def get_winning_seller_id(self):
     return self.get_seller_ids().first()
```
It won't be invalidated on product change nor sellers change. I would probably use:
```python
def get_winning_seller_id(self):
    # I assume .get_seller_ids() returns queryset
    return self.get_seller_ids().cache().first()
```
