### ISSUE TITLE
invalidated_update does not invalidate correctly

### ISSUE THREAD

**Issue by MisterNando** [Suor/django-cacheops#244]
**Assumption**: the intent of invalidated_update is to:

1. Identify the set of objects to update.
2. Perform the update.
3. Call invalidate on each object in its original and post-updated state.

This is accomplished by maintaining a list of objects to update.  The list is populated initially with the contents of the query set (pre-update).  Then the update occurs.  Then the list is extended with the contents of the query set post-update.

The problem is that the contents of the query set post-update (i.e. the set of objects it returns) are not necessarily the same as the contents pre-update.  For example, the update operation might have altered the objects such that they no longer meet the criteria of the query set.  Thus, we have lost our handle on the original set of objects.  We still have them in the list we created before the update, but this is just the pre-update state - we're not invalidating the objects post-update.

**Comment by Suor** [comment]
Thanks for bringing this up.

**Comment by MisterNando** [comment]
You're welcome - thanks for the quick fix!
