### ISSUE TITLE
Query regarding atomic transaction.

### ISSUE THREAD

**Issue by sp1rs** [Suor/django-cacheops#245]
Let say 2 things are running parallelly, first to get the object which is cached and second the object which is saving that object (That is invalidating the cache). So is it possible that before the get operation, the cache get invalidated and we get the wrong or nothing from the 1st operation?

**Comment by Suor** [comment]
Cache works in coherence with database transactions. Until changing transaction is commited any other readers get older object state either from cache or db itself, after transaction is commited you get new state. 

Even transactions don't guarantee you from writing to same object twice and forgetting whatever first process have done. For that you should lock object with `SELECT FOR UPDATE`:
```python
with transaction.atomic():
    obj = Model.objects.select_for_update().get(pk=obj_pk)
    obj.field = val
    obj.save()
```
All `SELECT FOR UPDATE` queries automatically bypass cache.
