### ISSUE TITLE
without redis?

### ISSUE THREAD

**Issue by hyusetiawan** [Suor/django-cacheops#247]
I would like to use this library, however, my setup does not have redis :( 

Is it possible to set django-cacheops to cache automatically (not the simple time invalidation) using local memory instead of redis? I can even work with file based as well.

**Comment by Suor** [comment]
Cacheops uses redis sets and redis lua scripting at its core, so it's not easy to replace. You can reimplement `cache_thing()` and `invalidate_dict()` to work with localmem, but I would recommend just installing redis.
