### ISSUE TITLE
after Model.save() the get is getting the data back from DB

### ISSUE THREAD

**Issue by T2BDeepika** [Suor/django-cacheops#248]
after Model.save() the get() is getting the data back from cache and not DB. hence the changes are not being reflected. Any thoughts in this? Thanks

**Comment by Suor** [comment]
.get() fetches old value there to invalidate on it, we don't need to fetch new value, we already have it.

**Comment by ArupKantiDas** [comment]
After saving a new set of Values in a model with model.save() I need to get back the new value in the very next .get() call. I am not getting the new values but I am getting the Old values that was there before .save() call. Any settings for that? I am new to this please help me with this how it will work.

**Comment by Suor** [comment]
After calling original .save() everything should be invalidated, before
that you get old values obviously. If this doesn't work for you then please
create a test.

28 июл. 2017 г. 13:07 пользователь "ArupKantiDas" <notifications@github.com>
написал:

**Comment by ArupKantiDas** [comment]
Thanks but thats not working but it should. I will check If I've made a mistake. Thanks.
