### ISSUE TITLE
Trouble with caching working in tests

### ISSUE THREAD

**Issue by mattjmorrison** [Suor/django-cacheops#249]
Is there something that I'm missing or does caching not work for django tests for some reason? 

Here is an example: https://github.com/mattjmorrison/django_cacheops_example

I have one simple test that does the following
```
        MyThing.objects.create(description='x')
        with self.assertNumQueries(1):
            list(MyThing.objects.all())
        with self.assertNumQueries(0):
            list(MyThing.objects.all())
```

Running the tests in that repo gives
```
└──➤ ./manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F
======================================================================
FAIL: test_x (demo.tests.MyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/imtapps/Projects/django_cacheops_example/demo/tests.py", line 12, in test_x
    list(MyThing.objects.all())
  File "/Users/imtapps/.virtualenvs/django-cacheops-example/lib/python3.4/site-packages/django/test/testcases.py", line 88, in __exit__
    query['sql'] for query in self.captured_queries
AssertionError: 1 != 0 : 1 queries executed, 0 expected
Captured queries were:
SELECT "demo_mything"."id", "demo_mything"."description" FROM "demo_mything"

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

However, doing the same thing in the repl seems to work
```
└──➤ ./manage.py debugsqlshell
Python 3.4.6 (default, Apr 17 2017, 21:41:30)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from demo.models import MyThing
>>> list(MyThing.objects.all())
SELECT "demo_mything"."id",
       "demo_mything"."description"
FROM "demo_mything" [0.41ms]
[<MyThing: MyThing object>]
>>> list(MyThing.objects.all())
[<MyThing: MyThing object>]
>>>
```

I'm using django-debug-toolbar for the `debugsqlshell` command. I believe I'm using the latest versions of everything. My configuration in my django settings file is as follows:
```
CACHEOPS_REDIS = "redis://localhost:6379/1"
CACHEOPS_DEGRADE_ON_FAILURE = False
CACHEOPS = {
    'demo.*': {'timeout': 60*60, 'ops': 'all'},
}
```
I'm running on macOS (10.12) and I installed redis via homebrew.

I *think* that is all of the pertinent information - let me know if I'm leaving anything out.

**Comment by Suor** [comment]
This is somewhat correct behavior. Django wraps each test in a transaction, then you make this transaction dirty with `.objects.create()`, which turns off caching until the end of it, which is end of the test. The other thing cacheops does is delaying invalidation until the end of transaction. This is part of cacheops transaction handling.

You can use `TransactionTestCase` to prevent Django from wrapping test into transaction, but then it will use much slower strategy to protect your test db from changes. Alternatively you can use the hack I am using to speed up testing cacheops:

```python
from cacheops.transaction import transaction_states

class BaseTestCase(TestCase):
    def setUp(self):
        # Emulate not being in transaction by tricking system to ignore its pretest level.
        # TestCase wraps each test into 1 or 2 transaction(s) altering cacheops behavior.
        # The alternative is using TransactionTestCase, which is 10x slow.
        from funcy import empty
        transaction_states._states, self._states \
            = empty(transaction_states._states), transaction_states._states

    def tearDown(self):
        transaction_states._states = self._states
```

**Comment by Suor** [comment]
You should be careful when using cache in tests for one more reason - it carries over information and thus can introduce subtle dependencies between tests making them work in one order but not the other and so on.

I wonder if I should provide and document that `BaseTestCase` with also `invalidate_all()` call added to `.setUp()`.

**Comment by mattjmorrison** [comment]
Thank you for the explanation. I think that all makes sense. The tests in which I was using caching were not meant to be permanent tests - they were more exploratory performance tests that I was just using to find where adding caching could help eliminate some database calls.

I think the `BaseTestCase` with the hack mentioned above and the `invalidate_all()` would be a nice addition.

Thanks again for the explanation.
