### ISSUE TITLE
Performance degregation on QuerySet.delete() with cacheops enabled

### ISSUE THREAD

**Issue by pembo13** [Suor/django-cacheops#250]
Having `cacheops` enabled causes Django to always return `False` on calls to internal method `can_fast_delete`, resulting in all deletes being slow (and memory intensive).

1. `'*.*': {},` results in hooks to the `post_delete` signal on all models
2. `install_cacheops()` results in system-wide hooks to `m2m_changed`

If either 1 or 2 is true, `can_fast_delete` returns `False`. In my case, the end result was a jump from 64MB of RES memory to over 200MB, and eventual killing of the process by the operating system (GNU Linux) in an management command. 

My solution was to conditionally remove 'cacheops' from `INSTALLED_APPS` by way of an ENV variable and some `settings.py` logic. This allows a *fast-path* delete to occur.

If there is no way to avoid the performance degradation, this should at least be documented clearly.

**Comment by Suor** [comment]
cacheops uses signals to make invalidation, so mostly it's unavoidable. Two things I can do though:
- connect `m2m_changed` to individual models,
- say that `'*.*'` is not recommended.

**Comment by Suor** [comment]
Thanks for bringing this up.

**Comment by Suor** [comment]
**P.S.** your hack can lead to some stale cache.

**Comment by pembo13** [comment]
@Suor thanks for taking a look at this. If you think this issue can be coded around would be great. Even then, might be good to document that models registered by cacheops won't ever get **fast-path** deletes, it's not exactly something one may think of.

Thanks for your P.S. In this particular case of mine, I'm not touching any cached models.

**Comment by Suor** [comment]
Fixed in 479e641 and 6844868f42958cc26b788b66b27806545dcd38b4.

**Comment by pembo13** [comment]
@Suor thank you.
