### ISSUE TITLE
Using select_for_update in multiple threads stucks

### ISSUE THREAD

**Issue by M1hacka** [Suor/django-cacheops#251]
I use django 1.10.7, PostgreSQL 9.4, psycopg 2.7.3.1, cacheops 4.0 and 3.2.1 on local and production relatively.
The situation:

One of celery tasks can be executed simmultiniously by multiple workers.
If tasks are executed one by one - everything goes fine.
When 2 workers start on the same Conversation object, second thread is waiting on select_for_update (which is well), and the first is stuck in save() operation (in db i see ["idle in transaction" status](https://www.postgresql.org/docs/9.2/static/monitoring-stats.html), which means that query was executed, returned to backend, but transaction is not commited yet)

Here is the code:
```
 with transaction.atomic(using=settings.DB_SHARD):
        # if I remove select_for_update here, everything works fine
        # Second thread will wait here with "SELECT ... FOR UPDATE" query in database with "active" status
        conv = Conversation.objects.select_for_update().get(pk=116774)

        # Some code, changing conv object without sending
        conv.user_unread_count = 0

        # First thread is stuck here
        # I see "UPDATE ..." query in database with "idle in transaction" status
        conv.save(update_fields=['user_unread_count'])

        # This doesn't work as well
        # conv.save(update_fields=['user_unread_count'], force_update=True)
```

I've ran this code with django_debug toolbar and got stange select, done by save() method:
```
SELECT ••• FROM "messages_conversation" WHERE "messages_conversation"."id" = 116774 FOR UPDATE
-- ??? What is this select here for
SELECT ••• FROM "messages_conversation" WHERE "messages_conversation"."id" = 116774 

UPDATE "messages_conversation" SET "user_unread_count" = 0 WHERE "messages_conversation"."id" = 116774
```

I solved an issue in my project by disabling cache:
```
    with transaction.atomic(using=settings.DB_SHARD):
        # After I replaced save() with update() bug became floating, sometimes it was stuck in "idle in transaction" on this query. After adding nocache() the problem has been solved.
        conv = Conversation.objects.select_for_update().nocache().get(pk=116774)

        # Some code here
  
        Conversation.objects.filter(id=conv.id).update(user_unread_count=0)

        # This doesn't work too!!!
        # Conversation.objects.filter(id=conv.id).invalidated_update(user_unread_count=0)
```
Here is the screen, that shows save() stack trace:
![screen](https://user-images.githubusercontent.com/2315339/31166866-9f9598a0-a909-11e7-9c6c-13adb4e3c36c.png)

**Comment by Suor** [comment]
Not sure I understand this correctly. What is the issue? Is it that worker hangs up on `conv.save()`? Does it? If no, then I don't understand why transaction is not committed. 

Some things to clear up:

> ??? What is this select here for
> SELECT ••• FROM "messages_conversation" ...

cacheops fetches old model state to run invalidation on it as well as new one.

> Conversation.objects.select_for_update().nocache()

`.nocache()` here is noop, cache is always bypassed for `.select_for_update()`.

> Conversation.objects.filter(id=conv.id).update(user_unread_count=0)

This does no invalidation and hence to SELECT, `.invalidated_update()` does the fetch.

>  with transaction.atomic(using=settings.DB_SHARD):

You make no routing on querysets is it ok?

**Comment by M1hacka** [comment]
> Is it that worker hangs up on conv.save()
Correct. It never goes to next instruction after save().

> You make no routing on querysets is it ok?
It doesn't really matter. We have no shards yet =) It's only code preparing for it, shard is equal to default database.

**Comment by Suor** [comment]
So some queries within code block might actually go through another alias and thus another connection? This may lead to them blocking each other.

**Comment by M1hacka** [comment]
I've tested. Removing "using" statement resolves the issue both with `save()` `and invalidated_update()`

**Comment by stuaxo** [comment]
@M1ha-Shvn is it worth updating the related Django bug with this info?

**Comment by M1ha-Shvn** [comment]
5 years have passed since this issue, I don't even remember what it is about. And if there was  such a bug in django tracker. @stuaxo what issue are you talking about?
