### ISSUE TITLE
Attempts to cache huge querysets hits redis cap on string lengths

### ISSUE THREAD

**Issue by dchaplinsky** [Suor/django-cacheops#255]
I've added `django_cacheops` to the project and set it to cache everything. It works just fine when django is serving content for website, but for management commands there is a problem.

Over night I need to perform some housekeeping and get the big chunks of data from DB (Caching them is not the best idea, I agree).

Here goes the problem: Redis has strict limit on the size of the value string, it's 512mb. You cannot raise it. If you accidentally hit it (just like I did) you will receive non-descriptive error like:
`redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.`
or 
`redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.`

And that's it. Nothing in redis server logs (with default logging level).

Of course that problem can be bypassed with `CACHEOPS_DEGRADE_ON_FAILURE=True` (bad idea, but quick fix), nocache for big operations or better setup of caching strategy. 

But it would be good if django-cacheops can also throw a proper exception or degrade without hitting the redis, if the payload is bigger than 512mb.

**Comment by Suor** [comment]
Hello, let me first state that bad error message is obviously not a cacheops issue, but redis one. Handling that by silently ignoring is also a questionable solution. This makes me think that this should be solved at your app level, not in cacheops.

To do that you can just not cache that big query in management command. The best approach would probably be to use `QuerySet.iterator()`, which not only disables cacheops, but turns off queryset in-memory caching and db driver/db-level one (the last one when supported).

You can also call `.nocache()` on querysets, which you don't want to cache.
