### ISSUE TITLE
cacheops not working with django-querysetsequence

### ISSUE THREAD

**Issue by vkosh** [Suor/django-cacheops#259]
The problem described [here](https://github.com/percipient/django-querysetsequence/issues/34).
Is there a way or workaround to disable caching for certain classes inherited from QuerySet, like QuerySetSequence? Could you suggest something?

**Comment by Suor** [comment]
I would say that `QuerySetSequence` should not inherit from `QuerySet`, overall its implementation is way too complicated. As far as I can see, there is no need for `QuerySetSequence` to use any internals, and it would work flawlessly if it only used public interfaces. So it's up to it to fix this.

For now you can try forking `queryset_sequence` and adding things to `INHERITED_ATTRS`.

**Comment by Suor** [comment]
Another way you can try making this work is reverting some methods on `QuerySetSequence` to ones of unpatched `QuerySet`:
```python
QuerySetSequence._clone = QuerySet._no_monkey._clone
# ...
```

**Comment by Suor** [comment]
BTW, if you wanted to use cacheops automatic cache on `QuerySetSequence`, then it probably won't work anyway. The reason is that this is not really a queryset, the fact that it "inherits" from it is just a dirty trick. You can use `@cached_as()` though.

**Comment by vkosh** [comment]
@Suor thanks for helping.

I've almost made it work using the following:

```python
QuerySetSequence._clone = QuerySet._no_monkey._clone
QuerySetSequence._fetch_all = QuerySet._no_monkey._fetch_all

__getattribute_orig__ = QuerySetSequence.__getattribute__

def __getattribute__(self, attr):
    if attr == '_cacheprofile':
        return None
    if attr == '_no_monkey':
        return QuerySet._no_monkey
    val = __getattribute_orig__(self, attr)
    return val

QuerySetSequence.__getattribute__ = __getattribute__
```

First call to qs.all() of 
```python
qs = QuerySetSequence(Model1.objects.all(), Model2.objects.all())
```
returns the right result, and the second one leads to exception because QuerySetMixin._fetch_all used instead of QuerySet._fetch_all somehow. Can't understand why.

```
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 149, in get_app_config
    return self.app_configs[app_label]
KeyError: 'queryset_sequence.3b60046d8fea4034bd18cbd501a70dde'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 55, in <module>
    for a in q.all():
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/cacheops/query.py", line 282, in _fetch_all
    self._result_cache = pickle.loads(cache_data)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1807, in model_unpickle
    model = apps.get_model(*model_id)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 200, in get_model
    app_config = self.get_app_config(app_label)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 156, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'queryset_sequence.3b60046d8fea4034bd18cbd501a70dde'
```

**Comment by Suor** [comment]
`QuerySetSequence` uses externals methods like `.filter()` and `.exclude()` as template methods and when overrides internals like `._filter_or_exclude()`, this is very tied up with `QuerySet` implementation. Instead one can just proxy public methods or implement them:
```python
def proxy_to_querysets(name):
    def method(self, *args, **kwargs):
        return self.__class__(getattr(q, name)(*args, **kwargs) for q in self._querysets)
    method.__name__ = name
    return method


class QuerySetSequence:
    filter = proxy_to_querysets('filter')
    exclude = proxy_to_querysets('exclude')
    # ...

    def get(self, *args, **kwargs):
        # .. implement it
```
If you really want to use some `QuerySet` code as template one, ignoring how fragile is it, you can just copy method:
```python
class QuerySetSequence:
    get = QuerySet.get  # you might need to unwrap this in Python 2
```

If you need to trick someones code by presenting as `QuerySet` you can use metaclass instancecheck.

**Comment by vkosh** [comment]
> To solve @vkosh's actual problem though, something like this might work though:

> class MyQuerySetSequence(QuerySetSequence):
>     INHERITED_ATTRS = QuerySetSequence.INHERITED_ATTRS + ['_cloning']

Unfortunately this one doesn't work.
QuerySetSequence hasn't INHERITED_ATTRS, because it has deleted during class instantiation in PartialInheritanceMeta.
And if I copy-paste all QuerySetSequence INHERITED_ATTRS and NOT_IMPLEMENTED_ATTRS to MyQuerySetSequence with "_cloning" attr (https://gist.github.com/vkosh/37ef967340c11981f22ba7ede90c8adf) there is an exception:
```
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    print(q.all())
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 777, in all
    return self._clone()
  File "/usr/local/lib/python3.5/site-packages/cacheops/query.py", line 227, in _clone
    if self._cloning:
  File "/usr/local/lib/python3.5/site-packages/queryset_sequence/_inheritance.py", line 67, in __getattribute__
    return super(cls, self).__getattribute__(attr)
  File "/usr/local/lib/python3.5/site-packages/queryset_sequence/_inheritance.py", line 71, in __getattribute__
    (name, attr))
AttributeError: 'QuerySetSequence' object has no attribute '_cloning'
```

I think, the only way to workaround this is to monkey-path __getattribute__ like here: https://github.com/Suor/django-cacheops/issues/259#issuecomment-347666825

**Comment by vkosh** [comment]
BTW, about my case. I'm trying to imlpement autocomplete view across multiple models for generic fk field ([dal example](https://django-autocomplete-light.readthedocs.io/en/master/gfk.html#view-example-for-querysetsequence-and-select2)).
Also I need caching in my project for frontend queries/views. I actually don't care about caching in admin, and particulary in the autocomplete view.
So the case is quite common, but I can't get the whole project work because of the issue.

**Comment by Suor** [comment]
@vkosh maybe it would be easier for you to not use one of these libs. Like implement part of sequence functionality you need and dump the dependency or alternatively use some other, possibly lower level cache and dump cacheops dependency.

**Comment by vkosh** [comment]
@Suor I agree. For my case the easer way is to implement custom query sequence partially. But IMO it would be great if cacheops has support of unpatching. E.g.
```python
unmonkey(QuerySetSequence)
```
or
```python
@nocache
class MyQuerySetSequence(QuerySetSequence):
  ...
```

**Comment by Suor** [comment]
QuerySet class is patched, you can't "unpatch" a descendant. If you mean
patching it to circumvent previous patching then this sounds too dirty.

30 нояб. 2017 г. 15:55 пользователь "vkosh" <notifications@github.com>
написал:
