### ISSUE TITLE
install_requires forces to install Django 2.0

### ISSUE THREAD

**Issue by PaoloC68** [Suor/django-cacheops#261]
Having this in the setup requirements forces pip to install Django 2.0
 
       install_requires=[
        'django>=1.8',
        'redis>=2.9.1',
        'funcy>=1.8,<2.0',
        'six>=1.4.0',
    ],
For this reason even bigger Django projects exclude `Django` from the `install_requires`, see Django REST framework for example [here](https://github.com/encode/django-rest-framework/blob/master/setup.py#L64)

**Comment by Suor** [comment]
By this logic I should remove other dependencies too, so that they wouldn't be "unexpectedly" upgraded with cacheops. This makes no sense to me at all.
