### ISSUE TITLE
Cacheops and multiple databases

### ISSUE THREAD

**Issue by M1hacka** [Suor/django-cacheops#265]
Hi.
Recently we've started developing sharding of our database. We do it on the bases of [django-sharding library](https://github.com/JBKahn/django-sharding). And catched a bug (may be feature =)) of cacheops: it ignores `using` parameter and `self._db` in `_pre_save`, example:
```Python
# Works fine
u = User.objects.using('shard_1').get(pk=100500)
# Fails
u.save()
# Fails too
u.save(using='shard_1')
```
Both save queries fail with "users_user" doesn't exist error.

After long research, we found the reason in `cacheops/query.py`:
```Python
def _pre_save(self, sender, instance, **kwargs):
    if not (instance.pk is None or instance._state.adding or no_invalidation.active):
        try:
            # This query fails, as there is no using('shard_1') here and it tries getting data from 'default' database
            _old_objs.__dict__[sender, instance.pk] = sender.objects.get(pk=instance.pk)
        except sender.DoesNotExist:
            pass
```

So, my solutions are:
1) Replace code with `sender.objects.using(instance._state.db).get(pk=instance.pk)`
2) Can I redeclare this manager in some way and use custom _pre_save?

**Comment by M1hacka** [comment]
Same problem in
```
    def invalidated_update(self, **kwargs):
        clone = self._clone().nocache()
        clone._for_write = True  # affects routing

        objects = list(clone)
        rows = clone.update(**kwargs)

        # TODO: do not refetch objects but update with kwargs in simple cases?
        pks = {obj.pk for obj in objects}
        for obj in chain(objects, self.model.objects.filter(pk__in=pks)):
            invalidate_obj(obj)
        return rows
    def invalidated_update(self, **kwargs):
        clone = self._clone().nocache()
        clone._for_write = True  # affects routing

        objects = list(clone)
        rows = clone.update(**kwargs)

        # TODO: do not refetch objects but update with kwargs in simple cases?
        pks = {obj.pk for obj in objects}
        for obj in chain(objects, self.model.objects.filter(pk__in=pks)):
            invalidate_obj(obj)
        return rows
```
It should be `self.model.objects.filter(pk__in=pks).using(self._db)`

**Comment by Suor** [comment]
Looks like you are right. If you provide a pull request I will merge it.

**Comment by Suor** [comment]
By the way, this should not be an issue if router is used.

**Comment by M1hacka** [comment]
django-sharding uses router. But it decides what database to use parsing query filters (a key field of sharded table). Both functions above take data with pk only and no key field, which is not enogh for django-sharding router to determine the shard. And it uses default database, causing error.

**Comment by Suor** [comment]
Makes sense

24 янв. 2018 г. 12:02 пользователь "M1ha Shvn" <notifications@github.com>
написал:

**Comment by Suor** [comment]
Only you broke MySQL somehow )

24 янв. 2018 г. 13:45 пользователь "Alexander Schepanovski" <
suor.web@gmail.com> написал:

**Comment by M1hacka** [comment]
Hmm... It's hard to test for me as I have Postgres everywhere and tests went ok on it. Travis failures?

**Comment by M1hacka** [comment]
Test I've written on this issue failed on trying to delete Category table manually with cursor... I guess I can take any table without dependencies for this test. I've changed to Video which have no deps.
