### ISSUE TITLE
Use with django-rest-framework Viewset?

### ISSUE THREAD

**Issue by sfdye** [Suor/django-cacheops#267]
How can I add caching to a drf's `ModelViewSet`? What is the best practice to do this?

What I want is to have caching for list and retrieve API and automatic invalidate the cache whenever the model is updated.

**Comment by Suor** [comment]
You can set queries to be cached to this model globally, this is documented at the start of README. Or you can call `.cache()` on queryset.

**Comment by sfdye** [comment]
I've enabled it globally for all models:
```
    '*.*': {'ops': 'all', 'timeout': 60*60},
```

It does not seem to work.

Do I still need to use the decorator on my API viewset?

**Comment by Suor** [comment]
It should work. Why do you think it doesn't?

**Comment by sfdye** [comment]
The response is still not cached, ie. it's not hitting the cache but computing the response every time.

**Comment by Suor** [comment]
Using Django ORM via DRF is nothing special so it should work, and it does for many people. I can think of a few reasons why it doesn't:
- something is misconfigured, like:
    - cacheops is not in `INSTALLED_APPS` or
    - `CACHEOPS_ENABLED` set to `False` or
    - `CACHEOPS_REDIS` set incorrectly/redis inaccessible and `CACHEOPS_DEGRADE_ON_FAILURE` set to `True`
- your views are wrapped into transactions and some db write is happening before db read,
  within dirty transaction cacheops turns itself to not write to cache something that might not be commited later
- a query is cached but invalidated immediately by some change
- some third-party lib or your code interferes with cacheops

**Comment by sfdye** [comment]
@Suor Thanks for the response. I will check again.

**Comment by Suor** [comment]
Ok, reopen with new info.
