### ISSUE TITLE
intermediate table caching of m2m relationship based on source Model timeout

### ISSUE THREAD

**Issue by Lepird** [Suor/django-cacheops#272]
so I am just wondering how to cache m2m tables based on config of source model ? 
so far with my test it seems to always get the config of the target Model.

for more details our implementation is to cache setup/config models on a 30 day timeout while having user/session scoped models on a 2 hour time out 

so as an example let say we have the below models

``` python
class Product(models.Model):
  name = models.CharField()
  price = models.PositiveIntegerField()

class User(models.Model):
  username = models.CharField()
  products = models.ManyToManyField('Product', related_name='user_products')
```

using the below config

``` python
CACHEOPS = {
    'app.product': {'ops': ('fetch', 'get'), 'timeout': 60*60*24*30},
    'app.user': {'ops': ('get', 'fetch'), 'timeout': 60*60*2},
}
```

how to set the many to many field between user and product to cache on 2 hours rather than 30 days ?

**Comment by Suor** [comment]
Hello, sorry for slow response. M2m has their own models accessable via `m2m_field.through`. In your case it's `User.products.through`, which by default will be `User_products`, so you add this line:
```python
  # cache m2m for N hours
  'app.user_products': {'ops': ('get', 'fetch'), 'timeout': 60*60*N},
```
