### ISSUE TITLE
ManyToMany relations are not invalidated?

### ISSUE THREAD

**Issue by brun0kb** [Suor/django-cacheops#273]
I've just upgraded to v4.05 (django 1.11.10) from an old version. Unfortunately, invalidation on m2m relations doesn't seem to work anymore. 
```
class Label(models.Model):
    text = models.CharField(max_length=127, blank=True, default='')

class Brand(models.Model):
    labels = models.ManyToManyField(Label)
```
After calling add() or remove() on the ManyToManyField, the cached query doesn't reflect the changes.
```
b = Brand()
b.save()
l = Label(text = "l")
l.save()

print b.labels.all().cache() # returns <QuerySet []>
print Brand.objects.filter(labels__id = l.id).cache() # returns <QuerySet []>

b.labels.add(l)

print b.labels.all().cache() # still returns <QuerySet []>
print Label.objects.filter(brand = b).cache() # still returns <QuerySet []>
print Brand.objects.filter(labels__id = l.id).cache() # returns <QuerySet []>

print b.labels.all().nocache() # returns <QuerySet [<Label: Label object>]>
print Label.objects.filter(brand = b).nocache() # returns <QuerySet [<Label: Label object>]>
print Brand.objects.filter(labels__id = l.id).nocache() # returns <QuerySet [<Brand: Brand object>]>
```

It seems that, when 'b.labels.add(l)' is being called, invalidate_m2m() only invalidates the 'Brand_labels' model. But since my queries are made on the Label and Brand models, the Label and Brand objs involved should be invalidated as well.

I've tried adding extra calls to invalidate_obj() at the end of invalidate_m2m(), like this:
```
def invalidate_m2m(sender=None, instance=None, model=None, action=None, pk_set=None, reverse=None,  **kwargs):
    ...
    elif action in ('post_add', 'pre_remove'):
        # NOTE: we don't need to query through objects here,
        #       cause we already know all their meaningfull attributes.
        for pk in pk_set:
            invalidate_dict(sender, {
                instance_column: instance.pk,
                model_column: pk
            })
            # try to invalidate the related models
            try:
                obj = model.objects.get(pk= pk)
                invalidate_obj(obj) # invalidates Label instance
            except model.DoesNotExist:
                pass
        invalidate_obj(instance) # invalidates Brand instance
```
That seems to do the trick.

**Comment by Suor** [comment]
Sorry for slow response.

Tried your code, everything gets invalidated correctly. In fact there are [tests](https://github.com/Suor/django-cacheops/blob/adba2dc9908c50157d417fd7564669c11ed23b2a/tests/tests.py#L669) that check exactly that. Something else must be interfering.

BTW, invalidating model objects is not needed since queries are also invalidated by intermediate dependents, e.g. `b.labels.all()` depends on `{'brand_labels': [{'brand_id': 1}], 'label': [[]]}`.

**Comment by brun0kb** [comment]
Thanks for responding (and for the great module).

I uninstalled/reinstalled django, cacheops and redis. Now, the queries on the Label model are invalidated correctly. But queries on the Brand model still aren't invalidated.

Both these queries keep returning an empty queryset after a label has been added:
```
b = Brand()
b.save()
l = Label(text = "l")
l.save()

Brand.objects.filter(labels__id = l.id).cache() # <QuerySet []>
l.brand_set.all().cache() # <QuerySet []>

b.labels.add(l)

Brand.objects.filter(labels__id = l.id).cache() # <QuerySet []>
l.brand_set.all().cache() # <QuerySet []>
```

Any idea what could be wrong?

**Comment by Suor** [comment]
Still works for me correctly. And also tested. 

Maybe you have old redis and use `CACHEOPS_DEGRADE_ON_FAILURE = True` and invalidation doesn't work at all? Maybe you have orphane pyc files? Try fresh virtualenv with no-system-packages.

**Comment by Suor** [comment]
Also does it work with other cacheops versions? Or Django versions?

**Comment by brun0kb** [comment]
Fresh virtualenv with only django and cacheops, CACHEOPS_DEGRADE_ON_FAILURE set to False.

Doesn't work with cacheops 4.0.1-4.0.5 (tested with django 1.11.10 and django 1.10)
Works with cacheops 3.2.1 and 4.0 (tested with django 1.11.10 and django 1.10)

**Comment by brun0kb** [comment]
redis-2.10.6

```
CACHEOPS_REDIS = {
    'host': "127.0.0.1",
    'port': "6379",
    'db': "1",
    'socket_timeout': 3,
}
CACHEOPS = {
    'mysite.brand':{'ops': 'all', 'timeout': 60*60},
    'mysite.label':{'ops': 'all', 'timeout': 60*60},
    '*':{'ops': 'all', 'timeout': 60*60},
}
CACHEOPS_DEGRADE_ON_FAILURE = False

```

**Comment by Suor** [comment]
Oh, I see now. This is misconfiguration - `*` does nothing, it should be `*.*`, combined with non-obvious cacheops behavior - when no profile is specified for m2m table invalidation does not happen. 

Once you fix your config this should start working for you. I will make m2m always happen to confuse people less.

**Comment by brun0kb** [comment]
Yep, it works. Thanks for following up!

**Comment by casoetan** [comment]
Hi @Suor.
Thanks for a great package.
I have the same issues. I'm checking then updating a value, but the m2m is not invalidated, after the update so when I try to read its value again, it returns the cached value.
