### ISSUE TITLE
What is "Invalidation Data"

### ISSUE THREAD

**Issue by chukkwagon** [Suor/django-cacheops#274]
From the readme:

> Cacheops stores cached data along with invalidation data, so you can't just set maxmemory and let redis evict at its will

What is "invalidation data" and why would cache key invalidation depend on it? Shouldn't it just use a TTL so you don't have to worry about the redis eviction strategy at all?

**Comment by Suor** [comment]
To invalidate on events like `post_save` or `post_delete` cacheops stores associations event -> set of keys to invalidate. This is explained in full [here](http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/).
