### ISSUE TITLE
How to add information about caching to a response header?

### ISSUE THREAD

**Issue by metachris** [Suor/django-cacheops#281]
First of all, really great project! Thanks for working on it.

I'm wondering what's the best way to add a response header with information whether the cache was hit or missed, in particular for DRF API responses.

Should we add a custom middleware with a cache-hit counter and a certain threshold for adding the header to the response, or do you think there would be a better way?

**Comment by Suor** [comment]
Middleware + `cache_read` signal would work, some base class can do too. Hard to say not looking at your code.

**Comment by metachris** [comment]
Thanks for the feedback. The code would just be a generic DRF serializer+view, nothing special.

**Comment by Suor** [comment]
Middleware or base class then
