### ISSUE TITLE
Error while using lock=True on queryset

### ISSUE THREAD

**Issue by chetandhembre** [Suor/django-cacheops#285]
Hi,
As per document, I added qs.cache(lock=True) to making sure only single db query happens when qs is invalidated from cache.
But after running this query from django shell I am getting ```ERR invalid expire time in setex``` error.

Notable thing here is qs was not cached before using `lock=True`.

Can you help me with this error?

**Comment by chetandhembre** [comment]
This error is coming because I am not sending timeout named parameter used in cached_as which has a default value as None.
If cache_profile timeout for qs is 0 then `setex` throw error while running lua script for `cache_thing`.
is it intended behavior?  as a timeout is named parameter and I expect to work even I do not send it properly.

**Comment by Suor** [comment]
Can you write a test around it?

**Comment by Suor** [comment]
Anyway can't set timeout to zero, this is an error indeed.
