### ISSUE TITLE
add ability to add more connection options to sentinel through CACHEOPS_SENTINEL

### ISSUE THREAD

**Issue by ramSeraph** [Suor/django-cacheops#286]
any other options set in CACHEOPS_SENTINEL other than those documented should be passed along directly to sentinel either in the constructor or master_for() call..  

currently there seems to be no way to ovverride the connection pool size or to override socket_connect_timeout for the actual redis client or even a way to socket_connect_timeout for the sentinel itself

**Comment by Suor** [comment]
PR welcome

**Comment by carlosabalde** [comment]
It seems the PR has been received :) Any chances it will be merged and a new release generated in the near future?

**Comment by Suor** [comment]
This is not here. A pull request is done to some fork.

**Comment by carlosabalde** [comment]
Ups! It seems something went wrong when creating the PR. It seems right now :)
