### ISSUE TITLE
Use `UNLINK` rather than `DEL` if Redis version >= 4

### ISSUE THREAD

**Issue by nicwolff** [Suor/django-cacheops#288]
Redis version 4.0.0 added the `UNLINK` command, which passes deleted keys to another thread to be asynchronously removed from memory. Conj sets in particular would benefit from this – in our deployment, invalidation of large conj sets can block for seconds. Cacheops should use `UNLINK` rather then `DEL` if it's available.

**Comment by Suor** [comment]
This makes sense. Need to plan this properly, I don't want to add setting and detecting this will add a check and some state, which I also don't like.

**Comment by nicwolff** [comment]
I'll open a PR – my approach is
```py
@memoize
def conj_del_fn():
    redis_version = redis_client.info()['redis_version']
    redis_version_at_least_4 = StrictVersion(redis_version) >= StrictVersion('4.0')
    return 'unlink' if redis_version_at_least_4 else 'del'
```
and then pass `conj_del_fn()` as an extra arg to the `invalidate` script in `invalidate_dict`.

**Comment by nicwolff** [comment]
If you don't want to incur the `memoize` wrapper cost on each invalidation, we could assign it to a module global instead, like
```py
conj_del_fn = None

def set_conj_del_fn():
    global conj_del_fn
    redis_version = redis_client.info()['redis_version']
    redis_version_at_least_4 = StrictVersion(redis_version) >= StrictVersion('4.0')
    conj_del_fn = 'unlink' if redis_version_at_least_4 else 'del'
```
and then in `invalidate_dict`
```py
if conj_del_fn is None:
    set_conj_del_fn()
```
and just pass `conj_del_fn` to the `invalidate` script.

**Comment by Suor** [comment]
`memoize()` cost is negligable. I thought it would be just clearer to not pass it each time.

**Comment by Suor** [comment]
Merged, thanks.
