### ISSUE TITLE
Invalidation and multiple database

### ISSUE THREAD

**Issue by Svan70** [Suor/django-cacheops#292]
The invalidate functions in invalidation.py are designed to receive a db connection name (using parameter) but never receive it. Instead, DEFAULT_DB_ALIAS is always used. 
Exemple of such usages : 
- post_save, post_delete and m2m_changed receivers. 
- bulk_create and invalidated_updated

**Comment by Svan70** [comment]
(I did some modifications on a branch but can't push it)

**Comment by Suor** [comment]
Why?

**Comment by Suor** [comment]
Merged and cleaned up. Thanks for this.

**Comment by Svan70** [comment]
You're welcome. But I still have 2 points : 
- In the cached_as function : if used as a decorator,  like in this case : 
`@cached_as(Article, timeout=120) `
`def article_stats()`
The db used in cached_as (and passed to cache_thing) will always be default (because the dbs are retrieved when decorator is created at 'compile-time'). But if article_stats is called while using another connection at run time (via a db router) I think we should pass the new connection to cache_thing. 
- For the invalidation, it is currently always db agnostic : if the user specifies a model as not db_agnostic and doesn't override CACHEOPS_PREFIX, a query on that model will always invalidate cache for that model whatever the db connection used. 

I created a branch. I let you see if you think it's relevant : 

https://github.com/Suor/django-cacheops/compare/master...Svan70:292_some_propositions

**Comment by Suor** [comment]
I consider second point to be a good thing. Trying to separate invalidation will break many scenarios starting from master-slave. Additionally, using `db_agnostic` is questionable here since one queryset can depend on several models. On the up side we have potential increase in invalidation granularity, which is also doubtful, e.g. in the most common non-master-slave sharding scenario invalidation sets will differ by condition. 

All the same considerations apply to `@cached_as()`, also it can depend on several querysets, which complicate things even furter. I see no issues with "compile time" though, everything will be routed appropriately via routers anyway. Anyway variating cache key is possible via `extra` param.

**Comment by Svan70** [comment]
Sorry for late answer ! Ok for your points. For the first point with
cached_as, what I wanted to point out is that if you use a dynamic router
(like this one https://github.com/ambitioninc/django-dynamic-db-router),
"dbs" computed at line 84 and given at get_prefix (line 99) are not
necessarily the current working databases at the time the decorated
function is called due to possible dynamic routing. Let you decide if it's
worth fixing it.

PS : Thanks for cacheops, very useful.

**Comment by Suor** [comment]
You can use local function within the scope of dynamic router:

```python
def some_func():
    # ...
    @in_database('db_x')
    @cached_as(qs, ...)
    def query(...):
        # ...
        return ...

    return query(...)

```

**Comment by Suor** [comment]
BTW, what's the use case of dynamic router? Why can't you use usual one?

**Comment by Suor** [comment]
Another workaround - copy `cached_as()` and move `dbs` calculation into inner function, use it instead of original one.

I don't want to change it in cacheops since it will degrade performance to support some strange external hack.

**Comment by Svan70** [comment]
In our case we have to create Databases dynamically and route queries to
them. The dynamic router is designed  for that and avoid modifying settings
at runtime (which is not recommended). But I don't need it to be fixed for
my usages : just thought about it when reading the code and wanted you to
know it. If I need it one day I'll apply your workaround on my fork. Thanks.
