### ISSUE TITLE
Don't cache django_migrations, detect accidental sharing, and other footguns

### ISSUE THREAD

**Issue by yozlet** [Suor/django-cacheops#297]
This is related to #239, but that issue is closed and there are enough different topics here that this may be worth a new issue.

I was also suffering the problem of `no such table: "django_content_type"`, and it took several days of investigation and debugging before I traced the problem to cacheops.

It happened because:

1. I've joined a team that has started using cacheops, but neither they nor I realised that cacheops would cache the `django_migrations` table (or rather, the `django.db.migrations.MigrationRecorder.Migration` model)
1. I have several instances of the app running locally, each with their own SQLite databases. However, they all share the single Redis instance running on my machine, and none of them differentiate through other methods (e.g. `CACHEOPS_PREFIX`) because we didn't realise it was needed.
1. So, when switching between app instances in different states, and recreating databases, cacheops will provide stale cache information. The `django_content_type` errors are caused by Django's `auth` app having a post-migration hook which writes data to that table, and this fails if Django thinks the table exists but it doesn't.

I fixed this in a couple of ways:

1. Added this to my `CACHEOPS` setting, to make it not cache `django_migrations`: `'migrations.*': { 'ops': (), 'timeout': 0 }`
2. Set a `CACHEOPS_PREFIX` that uses the `BASE_DIR` of my Django app, but not the whole thing (as it's very long sometimes): `CACHEOPS_PREFIX = lambda _: 'cacheops:' + '/'.join(map(str(pathlib.Path(BASE_DIR[-2:])))) + ':'`

I suspect that this issue is a fairly common one when a developer adds cacheops to an app and doesn't realise all the implications, or when a developer joins a project that's already using cacheops, and the team doesn't have cacheops-specific instructions in the app README. Both of these are pretty common situations, especially because the cacheops documentation doesn't seem to talk about it at all. (There _is_ a section called "[Sharing redis instance](https://github.com/Suor/django-cacheops#sharing-redis-instance)" but it's far down in the docs, and aimed at the use case where there are multiple Django hosts, rather than apps on the same host.)

To be clear: `cacheops` is working as designed. Unfortunately, this design is both lacking some safety features that would prevent certain common problems, _and_ when those problems happen it's not clear that `cacheops` is the cause.

Some ideas:

1. **Exclude `migrations.*` from cacheops coverage unless explicitly configured.** I'm fascinated to know why anyone would want `django_migrations` to be cached; I can't think of a good reason myself.
1. **Detect accidental Redis sharing.** Cache a set of app-specific attributes that don't change often (e.g. `BASE_DIR`, database URL, hostname, etc.) Check these on startup; if the set is cached _and_ any of the attributes are different, raise a warning.
1. **Show footguns early in the docs.** It's great that you have a "Caveats" section, but it's pretty far into the docs and it doesn't mention these particular issues.

**Comment by Suor** [comment]
Fixed by README updates
