### ISSUE TITLE
Cachops shouldn't break the system if the cache memory is full

### ISSUE THREAD

**Issue by babu-upcomer** [Suor/django-cacheops#299]
```
Error running script (call to f_450fb983ac023d2a5436c3c4e6b0622ebb9fccaa): @user_script:9:@user_script: 9: -OOM command not allowed when used memory > 'maxmemory'.
```

Can it fallback to DB by catching the exception?

**Comment by Suor** [comment]
Does `CACHEOPS_DEGRADE_ON_FAILURE = True` work for you?

**Comment by Suor** [comment]
But looks like this is permanent error, memory can't be freed - so you either have too small memory limit or too many non-volatile keys. So this is probably misconfiguration issue.

**Comment by Suor** [comment]
Also, not breaking the system when cache is full is questionable behavior, cacheops relies on cache not to be full when maxmemory is not used and maxmemory working when it is used. So breaking loudly is correct behavior.

**Comment by Suor** [comment]
If you set `maxmemory allkeys-lru` then you will get invalidator keys invoked sometimes which refer existing cache keys, making that cache keys not invalidate on corresponding event. So you will serve some stale data from time to time.

**Comment by babu-upcomer** [comment]
Hmm, I see! Thanks for the insight. I'll set it back to volatile-lru and clear the cache when it is reaching the maxmemory then?

**Comment by babu-upcomer** [comment]
About the cache node memory, we do have a 6 Gig of elastic cache node, for 100K user base. Do you think that's not gonna be enough?

**Comment by Suor** [comment]
That depends on what kind of queries you cache. In conservative setting this should be more than enough. But if you have so much invalidation structures that they exceed memory then you are probably caching many queries with complex and non-repeated where clauses. This is usually useless as they tend not to be hit anyway.

**Comment by Suor** [comment]
You can introspect cache to see what structures are there. Or use signals to log what you are caching. Then cut on it.

The way I use cacheops:
- use automatic cache only on simple helper models or that tend to be queried by id or other simple key only. Like cities, users, profiles and so on.
- use manual caching for other models when needed.

This keeps it manageable and prevents surprises.

**Comment by mrmachine** [comment]
@Suor do you have a tip on how I can introspect the Redis database to determine if it is invalidation structures or something else that is filling my database?

Is it definitely invalidation structures, or is it the size of the actual data being cached?

We do cache a lot of complex queries and generated XML that is not small, and this cached data is unique per user. But it is also hit frequently enough to make caching worthwhile for us.

I'd just like some insight on how big the cached data is, and how big the invalidation structures are, so I can set a realistic `maxmemory` limit.
