### ISSUE TITLE
How can I use this namespaced with multiple databases?

### ISSUE THREAD

**Issue by flxfxp** [Suor/django-cacheops#305]
Hi there,

I have one codebase that's connecting to a multitude of django postgres databases.
However, I only have one redis backend.

If I query something with `.using("database_b")`, the str will still display the result of `database_a`.

Is there a way to automatically namespace cacheops based on the database name used? Thanks!

**Comment by Suor** [comment]
There are two sections in readme about this: multiple database support and sharing redis instance. If your dbs are completely independent then you should look into second one.

**Comment by flxfxp** [comment]
If anybody in the future comes across this, please do the following to get correct cache namespacing.
**settings.py**

```python
def cacheops_prefix(query):
    prefix = '{}:'.format(query.dbs[0])
    return prefix

CACHEOPS_PREFIX = cacheops_prefix
```

On a sidenote, I feel like this would be a sane default to have in django-cacheops as it's not detrimental to the system.

**Comment by Suor** [comment]
Yes, the easiest way is:
```python
CACHEOPS_PREFIX = lambda q: q.db + ':'
```
This will check that you only cache things referring only to single db. Your code won't do that check.

And this is not good default, as it doesn't play nice with master-slave scenario and is not needed for sharding. The most common use is multihost/multidb website, and it won't work for multihost/multischema one, so this configuration should be conscious not default.
