### ISSUE TITLE
Feature proposal: custom serializers

### ISSUE THREAD

**Issue by harrybiddle** [Suor/django-cacheops#306]
Hey guys,

I have picked up django-cacheops to cache Pandas dataframes stored in my database and it works great!

However, I can't override the default behaviour of pickling the series in Redis. I'd prefer to use an alternative serializer, the msgpack one.

On quick first look it seems fairly simple to expose the serializer method either as a global option or as a parameter to the `cached_as` decorator.

What do you think? Would you be interested in a contribution for this?

**Comment by Suor** [comment]
Why pickle doesn't work for you?

**Comment by harrybiddle** [comment]
It works, but I'd prefer to reduce our attack surface. I don't want a malicious actor to trick my web server into de-pickling a dangerous object.

**Comment by Suor** [comment]
Not a big fan of such customization really.

**Comment by Suor** [comment]
Ok, looks like this has enough people wanting this. I am changing my mind, let's add a way to use custom serializer.
