### ISSUE TITLE
Is a not found Model.get() cached and if so, how can it be invalidated?

### ISSUE THREAD

**Issue by ferrants** [Suor/django-cacheops#308]
With the Automatic configuration in the settings.py, if I do a search for an object and it's not found, I want the next time I query this to see if the object exists to hit the database, not the cache. Is there a way I can configure this?

I'm using the Model.get(), if that makes any difference:
```
        try:
            obj = MyModel.objects.get(id=model_id) # this gets cached
        except MyModel.DoesNotExist:
            # invalidate the above cache?
```
settings.py:
```
CACHEOPS = {
    'api_app.MyModel': {'ops': {'get', 'filter'}, 'timeout': 60 * 15},
    '*.*': {}
}
```

**Comment by ferrants** [comment]
@Suor , do you have any advice on this? Any help is appreciated. Thanks!

**Comment by Suor** [comment]
First, there is no such op as `'filter'`, it is called `'fetch'`.

To your question, there is no built in way to skip caching now. You can invalidate it with:
```python
from cacheops.invalidate import invalidate_dict
invalidate_dict(MyModel, {'id': model_id})
```
Or you can subclass your queryset to not cache empty responses:
```python
class MyQuerySet(QuerySet)
    def _cache_results(self, cache_key, results):
        if results:
            super()._cache_results(cache_key, results)

```
This will skip cache write for all empty results, not only gets. To get even more specific you can copy and tweak `QuerySetMixin._fetch_all()` method from cacheops.

Sorry for slow response.

**Comment by ferrants** [comment]
Thank you, @Suor , I appreciate the response!
