### ISSUE TITLE
Finer-grained caching?

### ISSUE THREAD

**Issue by Yriuns** [Suor/django-cacheops#310]
For example, I have a `Article` model:
```python
class Article(models.Article):
    title = models.CharField(...)
    content = models.TextField(...)
    views_count = models.IntegerField(default=0)
```
And a `ArticleListView` list all the articles:
```python
qs = Article.objects.all().only('title', 'views_count')
# serialize the articles...
return data
```

Increase `views_count` every time user accesses the the `ArticleDetailView(pk)` for a specific `Article`:
```python
Article.objects.filter(pk=pk).update(views_count=F('views_count')+1)
article = Article.objects.get(pk=pk)
# serialize the article...
return data
```

Therefore, once the `ArticleDetailView(pk)` is accessed, the cache of `ArticleDetailView(pk)` and `ArticleListView` will be invalidated, because the `views_count` has changed.

1. However, it's unnecessary to invalidate the data for other `articles` in `ArticleListView`, since only the `views_count` of `Article(pk)` has changed.
2. Other fields of `Article(pk)` also doesn't change, can we reuse the cache?

*Or*

Maybe I should create a new table to store the value of some volatile fields like `view_count`?

**Comment by Suor** [comment]
cacheops doesn't work in terms of views but in terms of querysets, if you change any small part concerning that queryset the whole thing is invalidated, cacheops can't do anything about it. You can split your querysets to cache and invalidate them individually. In theory querysets like:
```python
Article.objects.only('title') # and
Article.objects.only('views_count')
```
Could be invalidated separately, however, cacheops doesn't do that, it only differentiates querysets by their tables and conditions. So yes you can separate frequently changed data to separate table or store counts in something like Redis.

**P.S.** `Article.objects.filter(pk=pk).update(...)` won't trigger invalidation at all, see CAVEATS.

**Comment by Yriuns** [comment]
I thought it is weird, too. Here is my production code (variable name differs from above) and `SQL` listed by `django-debug-toolbar`:
1. 
```python
qs = Article.objects.filter(identifier=pk)
qs.update(views=F('views')+1)
article = qs.first()
```
will trigger.
```sql
UPDATE `explore_article`
  SET `views` = (`explore_article`.`views` + 1)
  WHERE `explore_article`.`identifier` = 'xxxx'

SELECT ... FROM `explore_article`
  WHERE `explore_article`.`identifier` = 'xxxx'
  ORDER BY `explore_article`.`id` ASC LIMIT 1
```
2.

```python
Article.objects.filter(identifier=pk).update(views=F('views')+1)
article = Article.objects.filter(identifier=pk).first()
```
won't trigger.
```sql
UPDATE `explore_article`
  SET `views` = (`explore_article`.`views` + 1)
  WHERE `explore_article`.`identifier` = 'a-table-yummies-pre-sale'
```

3.
Also
```python
Article.objects.filter(identifier=pk).update(views=F('views')+1)
article = Article.objects.filter(identifier=pk).first()
```
won't trigger.

**Comment by Suor** [comment]
Yes, I found that `.update()` corrupts queryset by marking it for write.

**Comment by Suor** [comment]
So, this is Django bug:
```python
def update(self, **kwargs):
    # ...
    self._for_write = True
    # ...
    query = self.query.clone(sql.UpdateQuery)
    # ...
    self._result_cache = None  # clear queryset cache
    return rows
```
This could be even intended behavior, see how queryset cache is cleared.

**Comment by Yriuns** [comment]
Thanks a lot! Maybe we can update the CAVEATS.

**Comment by Suor** [comment]
No point, this is minor issue, which doesn't lead to stale cache.
