### ISSUE TITLE
key`s expiration time param `timeout` not work

### ISSUE THREAD

**Issue by mayouzi** [Suor/django-cacheops#311]
set a value `CACHEOPS_DEFAULTS = {'timeout': 60 * 60}`, but the cache key\`s expiration time is `-1` actually, and it\`s data type is `set`

**Comment by mayouzi** [comment]
@Suor 
Has anyone had this problem?

**Comment by Suor** [comment]
Can you paste your code which has an issue?

**Comment by mayouzi** [comment]
okay

@Suor 

django settings

```
    CACHEOPS_REDIS = {
        'host': '127.0.0.1'),
        'port': 6379,
        'db': 1,
        'socket_timeout': 3,
        'password': '',
    }
    CACHEOPS = {
        'product.*': {'ops': 'all'},
        auth.user: {'ops': 'all'},
    }
    CACHEOPS_DEFAULTS = {'timeout': 60 * 60}
    CACHEOPS_PREFIX = lambda query: '%s:' % 'local'
```
the version is `django-cacheops==4.1`

then, cache model with 

```
product = Product.objects.all()
```

**Comment by Suor** [comment]
So does it cache?

**Comment by mayouzi** [comment]
yes, it is

i add the `cacheops` into `INSTALLED_APPS` at django settings

```
INSTALLED_APPS = (
          ...
         'cacheops',
)
```

**Comment by Suor** [comment]
So if it does cache when what's the issue?

>

**Comment by mayouzi** [comment]
the params `timeout` not work, because the cache key\`s expire time is `-1`

**Comment by Suor** [comment]
How do you know?

>

**Comment by mayouzi** [comment]
use redis command

```
>ttl local:schemes:user
-1
```

**Comment by Suor** [comment]
This means no TTL on this key, it's not volatile and won't expire. However,
this is scheme key not cache key or invalidator key. It's supposed to not
expire.

**Comment by mayouzi** [comment]
thx, it means `timeout` not work for scheme key? is there any way to set scheme key expired

**Comment by Suor** [comment]
This is internal mechanics of cacheops, you shouldn't bother about it.

>

**Comment by mayouzi** [comment]
Thank you for your reply. Usually, we should not be bothered about this, except when there are some regulations on the key of redis

**Comment by Suor** [comment]
What regulations?
