### ISSUE TITLE
Distinct queryset cast to list shows old representation

### ISSUE THREAD

**Issue by mvanlonden** [Suor/django-cacheops#314]
```py
In [36]: langs = Language.objects.all()

In [37]: distinct_langs = Language.objects.filter(speakers__in=User.objects.all()).distinct()

In [38]: langs
Out[38]: <QuerySet [<Language: en>, <Language: es>]>

In [39]: distinct_langs
Out[39]: <QuerySet [<Language: en>, <Language: es>]>

In [40]: list(langs)
Out[40]: [<Language: en>, <Language: es>]

In [41]: list(distinct_langs)
Out[41]: [<Language: en>]
```
Distinct queryset is correct but when cast to list old representation is printed

**Comment by Suor** [comment]
How does this relates to cacheops?

**Comment by mvanlonden** [comment]
When I disable cacheops, the casting works correctly

**Comment by Suor** [comment]
Can you make a test case out of it?

пт, 21 дек. 2018 г., 11:11 Mel van Londen notifications@github.com:

**Comment by mvanlonden** [comment]
I'm not reusing the queryset. Where would you like me to create the test case?

**Comment by Suor** [comment]
Your can read about creating test at the bottom of the README

пн, 24 дек. 2018 г., 23:47 Mel van Londen notifications@github.com:

**Comment by mvanlonden** [comment]
I can't seem to reproduce in a test and this code flow is no longer needed in my app. I will close this issue for now
