### ISSUE TITLE
Caching views protected with auth is vulnerability 

### ISSUE THREAD

**Issue by ApaDoctor** [Suor/django-cacheops#318]
If you cache whole view protected with authentication mechanism with `cached_view` and there was any response(successful or not). All other clients will receive this response. So it returns last cached response instead of checking if user really authenticated or not. 
I had this issue using `cahced_view` on `.as_view()` for DRF CBV.

**Comment by Suor** [comment]
This is not cacheops responsibility, but app authors.

**Comment by ApaDoctor** [comment]
In this case some information should be provided in docs.
