### ISSUE TITLE
Using cacheops with password auth to redis causes big connection number

### ISSUE THREAD

**Issue by M1hacka** [Suor/django-cacheops#319]
Hi. 
It may be related to https://github.com/Suor/django-cacheops/issues/315, but I'm not sure.
After setting up password for CACHEOPS_REDIS, I began getting a lot of connections to redis, while number of operations hasn't changed:
http://prntscr.com/mr6p53. 
This causes a lot of authentication attempts => TimeoutError-s and performance degrading.
Can you help me guess what's the reason, and how to resolve this?
Thanks.

**UPD**: cacheops is working on separate redis instance. Another instance, using redis-py directly doesn't have this problems after adding password: http://prntscr.com/mr6qjs

**Comment by Suor** [comment]
Have no idea. Cacheops does nothing special just passes all the options to redis-py constructor.

**Comment by M1hacka** [comment]
Found the problem, it was haproxy who closed connections. Thanks.
