### ISSUE TITLE
Disable caching on specific models

### ISSUE THREAD

**Issue by jpmohan1111** [Suor/django-cacheops#320]
Is there a way to disable caching on specific models, and enable cache on the rest?
I tried like below:
```python
CACHEOPS = {
	'APP.*': {'ops': {'fetch', 'get'}, 'timeout': 60*10},
	'APP.model1': None,
}
```
But it seems not to work as i see the redis data being populated for model1 as well.

**Comment by Suor** [comment]
This should work.
