### ISSUE TITLE
about settings

### ISSUE THREAD

**Issue by pyprism** [Suor/django-cacheops#321]
I am just confused about settings after reading setup instruction. Suppose I have two models ; `ProductImage` in `shop` app and `Account` model in `base` app . Then which one is correct 

1.
```
CACHEOPS = {
    'base.account.*': {'ops': 'all', 'timeout': 60*60},
    'shop.productimage.*': {'ops': 'all', 'timeout': 60*60},
}
```

or 2.
```
CACHEOPS = {
    'base.Account.*': {'ops': 'all', 'timeout': 60*60},
    'shop.ProductImage.*': {'ops': 'all', 'timeout': 60*60},
}
```

**Comment by Suor** [comment]
Both wrong. Case doesn't matter, it's just `'app_name.model'`.
