### ISSUE TITLE
Django 2.2 bulk_create ignore_conflicts support

### ISSUE THREAD

**Issue by stefan8** [Suor/django-cacheops#324]
There is new argument in django QuerySet `bulk_create` method called `ignore_conflicts` which breaks cacheops patched querysets / managers.
Are you going to support django 2.2 or are you willing to merge PRs since I see there is no active development :(

Cheers

**Comment by stefan8** [comment]
I've created simple PR https://github.com/Suor/django-cacheops/pull/326
Is it possible to merge?

**Comment by Suor** [comment]
I will look at it

**Comment by glqstrauss** [comment]
@Suor Any updates here?

**Comment by Suor** [comment]
Merged, thanks.
