### ISSUE TITLE
cacheops.cache.set/get/delete does not include the CACHEOPS_PREFIX on the keys

### ISSUE THREAD

**Issue by luzfcb** [Suor/django-cacheops#325]
Hello, is it expected that the [`cacheops.cache`](https://github.com/Suor/django-cacheops/blob/883cc9448d9954bb83257f21cf20c586135f2e06/cacheops/simple.py#L81-L103) methods don't automatically include on the key the value returned by `CACHEOPS_PREFIX` if that function/value was defined?

if yes (that is, the current behavior is expected), maybe this should be documented with a Big Warning.

Anyway, thanks for the incredible work at this library.

**Comment by Suor** [comment]
This is an obvious situation I agree. I added a note to README and will consider fixing this an a next major update.

**Comment by OmenApps** [comment]
Just to verify, as long as we're using redis (and not simple or file), the prefix works as expected, right?

**Comment by Suor** [comment]
@OmenApps cacheops simple cache ignores prefix even for redis. `QuerySet` cache, `@cached_as()` and `@cached_view_as()` honor prefix.

**Comment by Suor** [comment]
Fixed in https://github.com/Suor/django-cacheops/commit/e29dcbc8fbf1845e9249bd5a4a8462fa846afb80.
