### ISSUE TITLE
Cacheops hangs when CACHEOPS_DEGRADE_ON_FAILURE set to True and ConnectionError to redis

### ISSUE THREAD

**Issue by peteyb** [Suor/django-cacheops#327]
Whilst CACHEOPS_DEGRADE_ON_FAILURE does stop connection exceptions being thrown, on pages where multiple models are being referenced it takes upwards of 60 seconds before returning the response. The socket timeout makes little difference to this.

My django app is run inside a python 3.6 docker image. The redis instance is another container which I reference via a name lookup, not ip address; as this matches the production configuration on GCP.

Is it possible to update the CACHEOPS_DEGRADE_ON_FAILURE so that if one call to redis fails then all subsequent calls made as part of the same request are ignored, instead of attempting to hit redis for every model.

**Comment by Suor** [comment]
Sorry for slow response.

This could be done. I am, however, don't think `DEGRADE_ON_FAILURE` feature should receive any development. I don't see how it is useful in a loaded website scenario since failing cache will simple mean non-functional website.

If you have other ideas then you are welcome to present your case.

**Comment by Suor** [comment]
Here is how it may look:
```diff
diff --git a/cacheops/redis.py b/cacheops/redis.py
index ebb2d01..25a7b38 100644
--- a/cacheops/redis.py
+++ b/cacheops/redis.py
@@ -13,6 +13,8 @@ from .conf import settings
 
 
 if settings.CACHEOPS_DEGRADE_ON_FAILURE:
+    from funcy import compose, limit_error_rate, ErrorRateExceeded
+
     @decorator
     def handle_connection_failure(call):
         try:
@@ -21,6 +23,16 @@ if settings.CACHEOPS_DEGRADE_ON_FAILURE:
             warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
         except redis.TimeoutError as e:
             warnings.warn("The cacheops cache timed out! Error: %s" % e, RuntimeWarning)
+        except ErrorRateExceeded:
+            warnings.warn("The cacheops exceeded number or connection errors,"
+                          " not trying for %d seconds" % settings.CACHEOPS_DEGRADE_TIMEOUT,
+                          RuntimeWarning)
+
+    if settings.CACHEOPS_DEGRADE_FAILS and settings.CACHEOPS_DEGRADE_TIMEOUT:
+        handle_connection_failure = compose(
+            handle_connection_failure,
+            limit_error_rate(settings.CACHEOPS_DEGRADE_FAILS, settings.CACHEOPS_DEGRADE_TIMEOUT)
+        )
 else:
     handle_connection_failure = identity
```

**Comment by tumb1er** [comment]
May be it's better to mark client instance as failed till `request_finished` is fired?
```python
if settings.CACHEOPS_DEGRADE_ON_FAILURE:
    @decorator
    def handle_connection_failure(call):
        global failed
        try:
            if failed:
                warnings.warn("The cacheops cache is disabled till the end of request", RuntimeWarning)
                return None
            return call()
        except redis.ConnectionError as e:
            failed = True
            warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
        except redis.TimeoutError as e:
            failed = True
            warnings.warn("The cacheops cache timed out! Error: %s" % e, RuntimeWarning)

failed = False

@receiver(request_finished)
def reset_failed_flag(*args, **kwargs):
    global failed
    failed = False
```

The point is that connectivity problem may be partial or temporary (like DNS probing errors for some containers which last only a few seconds) and there may be not so much db queries to ruin database shielded with cacheops.

**Comment by Suor** [comment]
So there appear different strategies, none of which I am a fan of. I would suggest using custom `CACHEOPS_CLIENT_CLASS` to achieve your desired behavior. You will only need to wrap `.execute_command()` to handle errors or skip requests appropriately.

**Comment by tumb1er** [comment]
> So there appear different strategies, none of which I am a fan of. I would suggest using custom `CACHEOPS_CLIENT_CLASS` to achieve your desired behavior. You will only need to wrap `.execute_command()` to handle errors or skip requests appropriately.
Could you please add this advice to docs?

**Comment by Suor** [comment]
It doesn't belong there.

ср, 21 авг. 2019 г., 16:14 Sergey Tikhonov <notifications@github.com>:
