### ISSUE TITLE
Add cache key to share cacheops cache with microservice

### ISSUE THREAD

**Issue by Siecje** [Suor/django-cacheops#328]
I have a main Django application and a microservice that will share the same models. I want to use the same cacheops cache for both applications.

Currently the model needs to be in an app with the same name and have all fields and field classes the same.

https://github.com/Suor/django-cacheops/blob/e26c114b82a133573471fec51a69724367995991/cacheops/utils.py#L79

I'm wondering if each model can have a cache key that can override the default to be able to share the same cache with all models that have the same cache key?

Otherwise I am thinking about monkey patching `stamp_fields()` to check for a meta property or falling back to the default.

**Comment by Suor** [comment]
If models are the same then you shouldn't need to do anything.

**Comment by Siecje** [comment]
The model needs to be exactly the same. An API microservice might not need all of the fields like a fk for internal data. 

Even if you have all of the fields the class name and app of each field type needs to be the same.

**Comment by Suor** [comment]
If fields are different than model cached by microservice and loaded by the app will trigger attribute errors. If classes are different it would be impossible to deserialize at all.
