### ISSUE TITLE
The existence of the cache

### ISSUE THREAD

**Issue by dgorobets** [Suor/django-cacheops#330]
Is there a way to check if a cache exists for a specific queryset?

**Comment by Suor** [comment]
```python
from cacheops.redis import redis_client
redis_client.exists(queryset._cache_key())
```

**Comment by Suor** [comment]
This is not a public API though.

**Comment by Uninen** [comment]
> ```python
> from cacheops.redis import redis_client
> redis_client.exists(queryset._cache_key())
> ```

Not OP but Thanks for this still 👍 

> BTW, whats your use case?

I have a custom DRF view with an expensive query + super expensive serializer. I'm manually caching the deserialized data and returning it from cache if the cacheops key for the queryset exists. It was simple to implement and the invalidation works seamlessly as well.

**Comment by Suor** [comment]
@Uninen this is what `@cached_as()` is for. Can you use it?

**Comment by Uninen** [comment]
I wasn't able to use `@cached_as()` in this particular case but I'm using it elsewhere and it works great.

Thank You for your work!
