### ISSUE TITLE
How do you cache a relationship?

### ISSUE THREAD

**Issue by Siecje** [Suor/django-cacheops#332]
I want to cache this query.

```SQL
SELECT
    Platform_platformuser . user_id,
    Platform_platformuser . uuid,
FROM Platform_platformuser
    INNER JOIN MyApp_project_platform_users
    ON ( Platform_platformuser . user_id = MyApp_project_platform_users . platformuser_id ) 
WHERE MyApp_project_platform_users . project_id = ?
```

```Python
# MyApp/models.py
class Project(models.Model):
    # ...
    platform_users = models.ManyToManyField(
        "Platform.PlatformUser", name='platform_users', related_name='projects'
    )
```

Here is my config for `PlatformUser`.
```Python
CACHEOPS = {
    'MyApp.Project': {'ops': 'get'},
    'Platform.PlatformUser': {'ops': 'get'},
    '*.*': {},
}
```

**Comment by Suor** [comment]
Cacheops acts on querysets not sql queries, so it all depends on how you construct those. If you start from `Project` and then somehow join related then `Project` setting will be used. If you start from `PlatformUser` then its setting will be used. You might also call `cache()` on queryset to force its caching:
```python
PlatformUser.objects.filter(...).cache()
```

If you use `prefetch_related()` then it creates a separate queryset inside, which does not inherit its container setting, whether set via config file or overwritten. It follows its base model settings.

In your config you only set `get` op to be cached automatically, so no `Model.objects.filter()/all()/...` things will be cached unless you call `.cache()` on them explicitely. Things like `Model.objects.get()/first()/...`, will be cached unless you call `.nocache()` on them.

**Comment by Siecje** [comment]
Thanks.
