### ISSUE TITLE
Different backend than redis (memcached)

### ISSUE THREAD

**Issue by pySilver** [Suor/django-cacheops#339]
Hi @Suor !

Thanks for you lib. It works well for many years for us! Quick question: what special features or data structures of redis are used by cacheops? I'm asking in order to determine if this would be possible to add memcached support which with latest facebook proxy looks very interesting:

Refs:
http://www.cs.utah.edu/~stutsman/cs6963/public/papers/memcached.pdf
https://github.com/facebook/mcrouter

Biggest benefits:
* Distributed cache clusters
* Speed (well redis isn't slow at all)

**Comment by Suor** [comment]
Cacheops uses sets and lua scripting.
