### ISSUE TITLE
Cache view for each user

### ISSUE THREAD

**Issue by milad-ghr** [Suor/django-cacheops#344]
Hey there 
I have a issue with 'cached_view_as' as I want to cache a response data for each user. 
The data that is responding to user depends on permissions that user has, so queryset will be different.
Is there any way to cache 'data' separately for each user and when user requests the view, returns specific data for that user.
Thanks

**Comment by Suor** [comment]
Not with `@cached_view_as()`. You will need to use something simpler, e.g. `@cached_as()`:

```python
def some_view(request, arg):
    @cached_as()
    def _get_response(user):
        # ... basically the old body here
        response = render('some_template', ...)
        
        if hasattr(response, 'render') and callable(response.render):
            response.render()
        return response

    return _get_response(request.user)
```

You should pass anything you want to cache to vary on to `_get_response()`.

Yeah, I should probably think of making this easier :)

**Comment by milad-ghr** [comment]
Thanks man 
yeah and if you need help just tell me :))
