### ISSUE TITLE
Multi tenant Django with multiple databases

### ISSUE THREAD

**Issue by guilhermej** [Suor/django-cacheops#351]
I have a multi tenant Django app.
I use the same code and same settings file for all my clients, but each tenant has his own database, I use a database router to route for the correct database based on the domain that access the application using some middleware tricks.
When I use the django-cacheops for all clients the cache mix information of different tenants.
I know that the correct is to use a redis db for each of my clients but how I do this? There are some way to select the redis db for cacheops based on the request domain?

**Comment by Suor** [comment]
By default cacheops doesn't vary cache key based on database to seamlessly work for master/slavev or shading scenarios. You can however, set `db_agnostic` option to `False`. This will prevent key mixing.

To use different databases you'll need to use different connections. You can do that in custom `CacheopsRedis` class.

**Comment by guilhermej** [comment]
Thanks a lot for your help.
Using `db_agnostic = False` apparently works fine.

Looking for the keys I can see now that threre is some king of hashing in their names:
```
155) "conj:ead_privatevideo:user_id=1"
156) "q:510b1ff4203e44d579f7b0983354cf98"
157) "conj:ead_course:slug=aba-na-educacao&active=true"
158) "q:2844c6598c3d8bd9bf179c27aae141a6"
159) "schemes:ead_coursediscount"
160) "conj:ead_course:upgrade_to_id=1"
161) "conj:ead_courseteacher:course_id=5"
162) "q:40b82ebb35bf7961099af131e27d1788"
163) "conj:ead_coursediscount:course_id=5"
164) "q:73b2b19aea04e9d9ed490df057b65396"
165) "conj:ead_customprofile:"
166) "q:f4841d84f1a614f124ba7ccf4a086851"
167) "q:b9a0ecdb904eacf522725684db4da642"
168) "as:c0de00ce3d6794dea45b8ea07ea49646"
169) "conj:ead_course:upgrade_to_id=3"
170) "q:76215ffc84ecc60b8410c1cc21c4cfd7
```

But there are some querys that has a normal key like `conj:ead_coursediscount:course_id=5`, this key looks like is not db awareness. Should I worry about it?

**Comment by Suor** [comment]
This can't lead to corrupt cache. It may lead to unneeded invalidation though. If you worry about that you can set up cache prefix as described in [Sharing redis instance](https://github.com/Suor/django-cacheops#sharing-redis-instance) section.

**Comment by guilhermej** [comment]
Thanks a lot.
I just it the prefix based on the tenant ID and it works!
