### ISSUE TITLE
Memory error when pickle.dumps large data set

### ISSUE THREAD

**Issue by babylonlin** [Suor/django-cacheops#356]
When I try to modify large data set (more than 300 K objects), the current pickle.dumps throw Memory error. If I change the pickle in query.py to standard python pickle. It stops complain and runs much faster.

The lines I modified

from .cross import md5
import pickle

e.g. I run under python-3.7

**Comment by Suor** [comment]
There's no such thing as `cross.py` in cacheops anymore. Looks like your are using some of cacheops version, try updating to the latest version.

**Comment by babylonlin** [comment]
Ohoops. I forgot to update to 5.0. Thx.
