### ISSUE TITLE
Is nameclash possible in cacheops?

### ISSUE THREAD

**Issue by krnr** [Suor/django-cacheops#357]
once in a while we notice on our sentry such error:

Jun 2, 2020 3:28:33 PM UTC
TypeError: argument of type 'IndexQuerySet' is not iterable

(4 times in that minute, the once on Feb 18, once on Feb 7, again 4 times on Jan 14, 2 times on Oct 24, 2019)

the code under investigation is:

```
        qs = (
            Model.objects.using("connect")
            .filter(ignore=True, relation1_id=instance_id)
            .values_list("rel1_id", "rel2_id")
            .cache(ops=["get", "fetch", "count"], timeout=settings.CACHE_TTL)
        )

        if (instance_id, rel2_id) in qs:
            return False, True
```

from what I get the only reason of this error is when `._result_cache` is not iterable. then the occurences of this error allow to make the proposal that they only happen when some value is in the cache and after it's invalidated everything is back to normal.

the only reason of `._result_cache` being not iterable is when the [blob from the cache key](https://github.com/Suor/django-cacheops/blob/master/cacheops/query.py#L287) is not a list. yes, cache_key is built using [full sql](https://github.com/Suor/django-cacheops/blob/master/cacheops/query.py#L186) repr, so it must be unique for `.count()` and `.all()` queries. but could it be that the same cache key appear to have integer instead of the list?

and could https://github.com/Suor/django-cacheops/issues/346 be relevant to this?

or am I missing something and looking into the wrong direction?

ps: thank you for the very useful library.

**Comment by Suor** [comment]
[This](https://code.djangoproject.com/ticket/26600) might be related. You can check that by turning qs into a list before using `in` operator.

**Comment by Suor** [comment]
But let's look at full stack trace first.

**Comment by krnr** [comment]
yeah, i would be raving for a full stack trace, but I can't reproduce the problem.

thank you for the link to a bug report, maybe it's really relevant to the internal exception after which the `_result_cache` is left `None`. so, in this way it will be cached nevertheless?

**Comment by Suor** [comment]
It's doesn't matter at that point.

**Comment by krnr** [comment]
it matters for the following queries which will try to `pickle.loads(b'\x80\x03N.')`

**Comment by Suor** [comment]
If you have an error in other you will still have an error you show higher. So it doesn't matter what is in result_cache at this point, since no one will read it anyway.

**Comment by Suor** [comment]
Try converting to a list to avoid the Django bug above.

Reopen if still relevant with a stack trace.
