### ISSUE TITLE
obj_key unstable for model fields with validators

### ISSUE THREAD

**Issue by kirberich** [Suor/django-cacheops#358]
(tl;dr: using django's built-in field validators breaks cache keys between processes/restarts)

Hi! 

I just did a fun hunt for a subtle issue that's causing cache misses after server restarts / across server instances.

`utils.obj_key` uses some custom logic to make the various field attributes returned by `deconstruct` serializable. One of the things it does is to specially serialize functions, I'm assuming to avoid any function's default behaviour of including its memory address in its string representation, which would cause cache misses.

The edge case that occurs is that `obj_key` uses `inspect.isfunction`, which doesn't catch callable class instances, which caused a problem for me because one of my models uses a validator - and django's built-in validators are callable classes, not functions. This causes the cache key to include the memory address of the validator.

Here's a concrete example:
```python
    example_field = models.PositiveIntegerField(
        default=5,
        validators=[MinValueValidator(5)],
    )
```

```python
(Pdb) from cacheops.utils import obj_key
(Pdb) for field in self.model._meta.fields: print(f'{field} {json.dumps(field.deconstruct(), sort_keys=True, default=obj_key)}')
#...
db.ExampleModel.example_field ["example_field", "django.db.models.PositiveIntegerField", [], {"default": 5, "validators": ["<django.core.validators.MinValueValidator object at 0x107109f10>"]}]
```

I'm happy to make a PR for this, but I first wanted to check if this is a known issue, and what the preferred solution would be - my first impulse would be to check if something is executable by using `callable()`, and then creating a string representation in the existing way if it's a function and maybe using the object's class name if it's a callable object.

**Comment by Suor** [comment]
Any object may cause this issue, it doesn't need to be callable. The issue is it's not having stable string representation. 

I don't know of a general solution of this problem. Inspecting the whole tree graph might help, but it could be slow, contain cycles and still contain some unstable attrs deep down. 

So if you can come up with some partial solution, which will help with your case, then it's ok. Even if that is limited to that validitors. They are part of Django I suppose?

**Comment by Suor** [comment]
I would say let's start with a test. There is an instruction at the bottom of README.
