### ISSUE TITLE
Support for specifying Pickle protocol in options

### ISSUE THREAD

**Issue by MarkBird** [Suor/django-cacheops#362]
Hi,

I have an issue where we were sharing a Redis cache between 2 sites, one of which has been upgraded to Python 3.8, but the other is on Python 3.6 (due to be upgraded soon). The Python 3.8 server cached some data using Cacheops, but the Python 3.6 server then tried to read from the cache and threw a `unsupported pickle protocol: 5` error, because Python 3.6 doesn't support pickle protocol 5.

It would be useful if we could (optionally) specify the Pickle protocol in our Cacheops settings.

**Comment by Suor** [comment]
I'll take a look.

**Comment by Suor** [comment]
Related to #306. 

Thought about your use case and it feels like it's easier to simply use separate redises or prefixes. This is how model changes work - field list is incorporated into cache key. So the decision for now - looking for more interest and more use cases.

**Comment by Suor** [comment]
Closed in favor of #306.

**Comment by mesili** [comment]
I ran across this issue while trying a pre-production with python 3.8 in parallel with a production running with python 3.6.
In case of the django caches, there were no problem as one can specify the `PICKLE_VERSION` but there is no solution for cacheops.

Would there be anything against this feature other than low interest? 
I am willing to submit a PR if you are ok with it.

**Comment by Suor** [comment]
This one was closed in favor of of #306. Better discuss it there. I see how simply setting pickle version might be more desirable than more general mechanism though.
