### ISSUE TITLE
Caching frontend HTML

### ISSUE THREAD

**Issue by RidenShark** [Suor/django-cacheops#364]
Hi, I am working on a django project and trying to use cacheops. I have used the default settings in the readme. I can also see that the keys are being added in the Redis database. But I am unable to find any cache header keys in the browser response header. Does cacheops cache html?

settings

```
CACHEOPS = {
    'auth.user': {'ops': 'get', 'timeout': 60*15},
    'auth.*': {'ops': {'fetch', 'get'}, 'timeout': 60*60},
    '*.*': {'timeout': 60*60},
    'posts.*': {'ops': 'all', 'timeout': 60*60},
    'accounts.*': {'ops': 'all', 'timeout': 60*60},
    'categories.*': {'ops': 'all', 'timeout': 60*60},
}
```

**Comment by Suor** [comment]
Cacheops caches database queries or function results.
