### ISSUE TITLE
Feasibility of supporting Subquery invalidation

### ISSUE THREAD

**Issue by jeremystretch** [Suor/django-cacheops#365]
I understand that there's a known limitation concerning the invalidation of subqueries. The README says:

> Conditions on subqueries don't affect invalidation. ... [This] can be implemented if needed, but it's probably counter-productive since one can just break queries into simpler ones, which cache better.

I'm curious what degree of effort that would entail, as I recently discovered a use case for it under Django 3.1. I'll do my best to convey my current dilemma.

### Current Implementation

Assume two related models, Blog and Article:

```python
class Blog(models.Model):
    name = models.CharField()

    class Meta:
        ordering = ['name']


class Article(models.Model):
    blog = models.ForeignKey(to=Blog, related_name='articles')
    name = models.CharField()
    body = models.TextField()
```

When fetching a list of blogs, we annotate the number of articles associated with each using `Count()`. For example:

```python
blogs = Blog.objects.annotate(article_count=Count('articles'))
```

This works. Caching works. Everything works.

### Django 3.1

Django 3.1 [now removes the default ordering](https://docs.djangoproject.com/en/3.0/topics/db/aggregation/#aggregation-ordering-interaction) from queries when a `GROUP BY` clause is present, such as when using `Count()` above. This means that the above queryset still works, but the list of blogs returned is no longer ordered by name.

The presumed solution is to attach `.order_by('name')` to the queryset to restore the ordering. And indeed this works, however it's obviously not ideal to have to attach this to _every_ affected query for _every_ model in an application. Distaste for boilerplate aside, it's very easy to forget here and there.

As a workaround, I've experimented with using [subqueries](https://docs.djangoproject.com/en/3.0/ref/models/expressions/#subquery-expressions). It's a bit unwieldy, but the following works (and actually seems to be more efficient):

```python
article_count = Article.objects.filter(blog=OuterRef('pk')).values('blog').annotate(c=Count('*')).values('c')
blogs = Blog.objects.annotate(article_count=Subquery(article_count))
```

This works, and blogs are ordered, but of course now we've run into the issue with subqueries. Namely, once the above query has been cached, creating a new article on a blog won't update its count until the cached result expires.

All this is to ask: How feasible would it be to support the above use case? Any insight you can provide is greatly appreciated.

**Comment by Suor** [comment]
Your workaround looks way more complicated than simply adding `.order_by()`. It also looks like a bug in Django, which should be fixed there. Did you create a Django ticket?

Then subqueries is a separate issue. There is a common workaround - using `@cached_as()`:
```python
@cached_as(Article, Blog)
def blogs_with_counts():
    article_count = Article.objects.filter(blog=OuterRef('pk')) \
        .values('blog').annotate(c=Count('*')).values('c')
    return Blog.objects.annotate(article_count=Subquery(article_count))
```

As README says this is also fixable in cacheops. One simply needs to add a test and some code to `dnfs()` function.

**Comment by jeremystretch** [comment]
> Your workaround looks way more complicated than simply adding `.order_by()`

In practice, we offload the subquery generation to a function, so the queryset ends up as something like `Article.objects.annotate(article_count=get_subquery('articles'))`. From my limited experimentation, subqueries seems to perform better, though I haven't done any thorough testing.

> It also looks like a bug in Django, which should be fixed there. Did you create a Django ticket?

That was my first impression as well, but because `Count()` instills a `GROUP BY` clause, it's fair to argue that the lack of default ordering does technically follow the behavior called out in the 3.1 docs. It does seem rather disruptive, though. Honestly, I feel like I'm missing a step because I would assume this is a fairly common use case, but I wasn't able to find any discussion around it. Suppose I'll open a Django bug to at least clarify the intended behavior.

Appreciate the pointers; will ding into the DNF stuff and see if I can come up with anything.

**Comment by Suor** [comment]
There is a special treatment for combined queries in `dnfs()`, this might help.

**Comment by jeremystretch** [comment]
Alright, I think I'm onto the root issue. When defining a queryset such as

```python
queryset = Blog.objects.annotate(article_count=Subquery(article_count))
```

the Subquery assigned to `article_count` end up in `queryset.query.annotations`. These  subqueries must be inspected individually (as combined queries are currently).

```diff
diff --git a/cacheops/tree.py b/cacheops/tree.py
index e2b8dcd..1dbefbf 100644
--- a/cacheops/tree.py
+++ b/cacheops/tree.py
@@ -1,6 +1,7 @@
 from itertools import product
 from funcy import group_by, join_with, lcat, lmap
 
+from django.db.models import Subquery
 from django.db.models.query import QuerySet
 from django.db.models.sql import OR
 from django.db.models.sql.query import Query, ExtraWhere
@@ -122,5 +123,10 @@ def dnfs(qs):
 
     if qs.query.combined_queries:
         return join_with(lcat, (query_dnf(q) for q in qs.query.combined_queries))
+    elif qs.query.annotations:
+        subqueries = (
+            query_dnf(subq.query) for subq in qs.query.annotations.values() if type(subq) is Subquery
+        )
+        return join_with(lcat, (query_dnf(qs.query), *subqueries))
     else:
         return query_dnf(qs.query)
```

I suspect there's a more elegant way to achieve this, but the above seems to achieve what I'm after. Wanted to get a sanity check before I proceed with a test for it.

**Comment by Suor** [comment]
A query might both contain combined queries and subqueries. Also, subqueries might probably be present in other places, but annotations.
