### ISSUE TITLE
Django reset password emails not working with cacheops enabled

### ISSUE THREAD

**Issue by RidenShark** [Suor/django-cacheops#366]
I am using the automatic settings and had setup emails to display on the console.

Without cachehops - Reset email works.

With cacheops - Reset email is not working.

Any idea what's the issue here?

**Comment by Suor** [comment]
Never heard of something like that. Have no idea.

**Comment by RidenShark** [comment]
My bad. Turns out Django doesn't send emails for inactive accounts. It was redirecting silently.
