### ISSUE TITLE
ssl_cert_reqs support

### ISSUE THREAD

**Issue by Awmusic12635** [Suor/django-cacheops#372]
Do you support Disabling SSL verification? I am looking to use this on heroku where certificate verification is an issue due to the certs provided. 

I tried appending it to the connection url with:

```/?ssl_cert_reqs=none```

Though it did not appear to work.

**Comment by jigna-panchal** [comment]
Hi @Awmusic12635 were you able to figure this out? I'm running into the same issue.

**Comment by PiotrFiedoruk** [comment]
any luck?

**Comment by Suor** [comment]
Cacheops simply passes all arguments to `Redis`, do if redis-py supports this then it should work, if it doesn't then it won't. Any questions should go there.
