### ISSUE TITLE
CACHEOPS_DEGRADE_ON_FAILURE doesn't work with incorrect credentials

### ISSUE THREAD

**Issue by Awmusic12635** [Suor/django-cacheops#373]
I have been experimenting with this module on heroku using heroku's managed redis. So they provide the login string. I set `CACHEOPS_DEGRADE_ON_FAILURE=True` in my settings and loading a page causes an incorrect credentials exception. 

This leads me to two questions:

1. Shouldn't it degrade gracefully due to the credential failure?
2. Are there other reasons a credential error would appear other than wrong credentials? These are provided and auto managed by the heroku service so there should be no way they are wrong. It connects over ssl to redis 6 if that matters.

**Comment by Suor** [comment]
I wouldn't expect `CACHEOPS_DEGRADE_ON_FAILURE` to do anything about bad creds since that is generally a permanent error. This looks like some Heroku bug or misconfiguration. 

Sorry for slow response.
