### ISSUE TITLE
Invalidating a filtered queryset

### ISSUE THREAD

**Issue by RidenShark** [Suor/django-cacheops#375]
Hi. From the documentation, I see these three ways to invalidate.

```
from cacheops import invalidate_obj, invalidate_model, invalidate_all

invalidate_obj(some_article)  # invalidates queries affected by some_article
invalidate_model(Article)     # invalidates all queries for model
invalidate_all()              # flush redis cache database
```

Is there a way to invalidate a few objects?

**My case:**

I have a model `Post` related to the `Author`. And in the post view, I am using select_related to get one queryset and use it to display the post along with the author bio.

The problem is, I am unable to invalidate the author's posts whenever they edit their profile. I am only able to invalidate 1 object by using `invalidate_obj` or the entire `Article` model. I want to invalidate just the articles that belong to the author. How do I do that? I am a learner and I am having trouble trying to do that. If such method doesn not exist, Is it the right thing if I invalidate objects in a for loop?

**Comment by Suor** [comment]
Cacheops doesn't provide a way to invalidate a queryset on select related object. This is a design choice. You can use `.prefetch_related()` instead, which will make 1 more query, which will be cached and invalidated separately. You can read more about how cacheops works [here](http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/).
