### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one 'x' -- it returned y!

### ISSUE THREAD

**Issue by peteyb** [Suor/django-cacheops#380]
Are you aware of concurrency issues with django-cacheops when running simultaneous background workers. We have experienced an issue whereby cacheops attempts to get multiple results on a .save() when under load. If I set cacheops to ignore the `main.access` model the issue disappears. However, I really do not want to ignore that model from caching because of a background task as it helps reduce app load times as it is a frequently called model.

For context, we have an DRF API endpoint which accepts requests from a third party system, passes them on to Django-Q which then performs a set of commands that ultimately ends in the Access model save() method being called. The third party system can send batches of requests. We have 8 background workers running.

```bash
get() returned more than one Access -- it returned 7! : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 428, in worker
res = f(*task["args"], **task["kwargs"])
File "/app/xxxxxx/tasks.py", line 56, in sync_access_level
access.save()
File "/app/main/models.py", line 2377, in save
super(Access, self).save(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 744, in save
force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 769, in save_base
update_fields=update_fields,
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
for receiver in self._live_receivers(sender)
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
for receiver in self._live_receivers(sender)
File "/usr/local/lib/python3.7/site-packages/cacheops/query.py", line 431, in _pre_save
= sender.objects.using(using).get(pk=instance.pk)
File "/usr/local/lib/python3.7/site-packages/cacheops/query.py", line 352, in get
return qs._no_monkey.get(qs, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 412, in get
(self.model._meta.object_name, num)
main.models.Access.MultipleObjectsReturned: get() returned more than one Access -- it returned 7!
```

**Comment by Suor** [comment]
If you get several things on pk get then it's probably not cacheops issue. Not sure how this is possible at all. Do you have primary key constraint on db level?

**Comment by peteyb** [comment]
Here is a cut down sample of the model class:

```
class Access(models.Model):
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("organisation", "application")
        ordering = ['application__pk']
```

```
CREATE TABLE xxxxxx.main_access
(
    id integer NOT NULL DEFAULT nextval('main_access_id_seq'::regclass),
    .....
    CONSTRAINT main_access_pkey PRIMARY KEY (id),
    CONSTRAINT main_access_organisation_id_xxxxxxxxxx_uniq UNIQUE (organisation_id, application_id),
    ...
)
```

**Comment by tumb1er** [comment]
You can achieve such behavior even without cacheops at all. If you open database connection at the import time (i.e. before forking in uwsgi/guncorn), it is shared between multiple worker processes, so one process can receive from db connection a response for another process.
In logs it looks exactly the same: MultipleObjectsReturned on  primary key lookup and so on.

**Comment by peteyb** [comment]
I am leaning towards it being a Cacheops issue as it goes away when we add the `.nocache()` command to the filter e.g. 

```
for access in Access.objects.filter(organisation=organisation).nocache():
   .....
   access.save()
```

Applying the nocache workaround was sufficient for our purposes. Left the PR open in case others were affecting, happy to close if it is not a widespread issue.

**Comment by Suor** [comment]
Ok. I see several possibilities how you get this error:
1. You don't have unique on whatever you use in filter. 
2. You receive several objects from database in error, usually when results are misdirected. @tumb1er described one possibility, another one I experienced several years ago is a similar issue with pgbouncer.
3. You have a cache key clash, this way your get query may get results from some other one. I can think of that being a result of some not-properly serializable things in query tree.

Now about your code snippet. It is vulnerable to races anyway, when you are going to save an object you should lock fetching it with `SELECT FOR UPDATE` and wrap the whole thing in transaction. So there is a couple of ways to make it right:
```python
qs = Access.objects.filter(organisation=organisation)
with transaction.atomic():
    for access in qs.select_for_update():
        ...
        access.save()

# Or shorter transactions and locks
for access_pk in qs.values_list('pk', flat=True):
    with transaction.atomic():
        access = Access.objects.select_for_update().get(pk=access_pk)
        ...
        access.save()
```

Where `.select_for_update()` bypasses cache since you need to hit database to lock rows.

**Comment by peteyb** [comment]
Thank you fore the detailed feedback and code example, apologies for the delay in responding. I have pinned this to the project and we look to at the above changes when we next cycle back round to it. Happy to close the issue 👍
