### ISSUE TITLE
@cashed as decorator for function duplicate data with new cache key

### ISSUE THREAD

**Issue by dmytroivo** [Suor/django-cacheops#383]
Hello. I am using version 5.1. with redis
When I use @cached (timeout = 60 * 60) for some function (e.g. def get_data (self): ...), the result data is duplicated in the cache (and a new cache key is obtained).
I see when @cached is looking for the cached function data in the cache, it calls inside "func_cache_key" (def cached (self, timeout = None, extra = None, key_func = func_cache_key)), which always returns another cache_key for the same function with the same args, kwargs. Then the result data is not found in the cache and the same data is generated with a new key.

This is unexpected for me. Maybe it bug?

Thanks!

**Comment by Suor** [comment]
The most probable thing is that your are passing some custom objects to your func, which has memory address in their stringification. Ideally you would only pass simple things like strings and numbers and containers of them. You can look at  `func_cache_key()` and `obj_key()` implementation for reference: https://github.com/Suor/django-cacheops/blob/7c8a5c4c17a8a64acc8111ccaf2bd475ddc0b46a/cacheops/utils.py#L77-L94

**Comment by dmytroivo** [comment]
This happens when function def get_data (self) is a method of the SomeView (APIView) class where APIView is imported from rest_framework.views

**Comment by Suor** [comment]
Then you pass `self` as argument.

**Comment by Suor** [comment]
The solution is either:
- provide unique and non-changing stringification for your object
- do not pass objects as param, do not cache methods at least not directly
- use custom `key_func`

**Comment by dmytroivo** [comment]
In my case function was a method of class. I will use @cached for clean function.
Thanks!
