### ISSUE TITLE
AttributeError: type object 'DefaultClient' has no attribute 'from_url'

### ISSUE THREAD

**Issue by fengweiyuan** [Suor/django-cacheops#384]
AttributeError: type object 'DefaultClient' has no attribute 'from_url'

**Comment by Suor** [comment]
Looks like you are using non-default redis client, which doesn't have `.from_url()` constructor. Either add that or use dict configuration to be passed to `.__init__()`.

**Comment by fengweiyuan** [comment]
When I Delete code "CACHEOPS_CLIENT_CLASS = 'django_redis.client.DefaultClient'" in settings.py, it work.
Thanks.
