### ISSUE TITLE
"DoesNotExist: Profile matching query does not exist." exception upon Deletion

### ISSUE THREAD

**Issue by owocki** [Suor/django-cacheops#387]
HI from @gitcoinco - We are big fans of your work, thank you for creating & maintaining django-cacheops

We are using `django-cacheops==5.1` and running into an issue with one of the models ( https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py#L2773 ), wherein upon delete, an Exception is thrown.

```
In [1]: from dashboard.models import Profile

In [2]: Profile.objects.last().delete()
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-2-3b13653b2b8b> in <module>()
----> 1 Profile.objects.last().delete()

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/base.py in delete(self, using, keep_parents)
    917         collector = Collector(using=using)
    918         collector.collect([self], keep_parents=keep_parents)
--> 919         return collector.delete()
    920
    921     delete.alters_data = True

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/deletion.py in delete(self)
    316                     for obj in instances:
    317                         signals.post_delete.send(
--> 318                             sender=model, instance=obj, using=self.using
    319                         )
    320

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/dispatch/dispatcher.py in send(self, sender, **named)
    173         return [
    174             (receiver, receiver(signal=self, sender=sender, **named))
--> 175             for receiver in self._live_receivers(sender)
    176         ]
    177

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/dispatch/dispatcher.py in <listcomp>(.0)
    173         return [
    174             (receiver, receiver(signal=self, sender=sender, **named))
--> 175             for receiver in self._live_receivers(sender)
    176         ]
    177

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/cacheops/query.py in _post_delete(self, sender, instance, using, **kwargs)
    495         # NOTE: this will behave wrong if someone changed object fields
    496         #       before deletion (why anyone will do that?)
--> 497         invalidate_obj(instance, using=using)
    498
    499     def inplace(self):

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/cacheops/invalidation.py in invalidate_obj(obj, using)
     34     """
     35     model = obj.__class__._meta.concrete_model
---> 36     invalidate_dict(model, get_obj_dict(model, obj), using=using)
     37
     38

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/funcy/decorators.py in wrapper(*args, **kwargs)
     36         def wrapper(*args, **kwargs):
     37             call = Call(func, args, kwargs)
---> 38             return deco(call, *dargs, **dkwargs)
     39         return wraps(func)(wrapper)
     40     return _decorator

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/funcy/flow.py in post_processing(call, func)
    161 def post_processing(call, func):
    162     """Post processes decorated function result with func."""
--> 163     return func(call())
    164
    165 collecting = post_processing(list)

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/cacheops/invalidation.py in get_obj_dict(model, obj)
     97 def get_obj_dict(model, obj):
     98     for field in serializable_fields(model):
---> 99         value = getattr(obj, field.attname)
    100         if value is None:
    101             yield field.attname, None

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/query_utils.py in __get__(self, instance, cls)
    133             val = self._check_parent_chain(instance, self.field_name)
    134             if val is None:
--> 135                 instance.refresh_from_db(fields=[self.field_name])
    136                 val = getattr(instance, self.field_name)
    137             data[self.field_name] = val

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/base.py in refresh_from_db(self, using, fields)
    626             db_instance_qs = db_instance_qs.only(*fields)
    627
--> 628         db_instance = db_instance_qs.get()
    629         non_loaded_fields = db_instance.get_deferred_fields()
    630         for field in self._meta.concrete_fields:

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/cacheops/query.py in get(self, *args, **kwargs)
    351             qs = self
    352
--> 353         return qs._no_monkey.get(qs, *args, **kwargs)
    354
    355     def first(self):

~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    406             raise self.model.DoesNotExist(
    407                 "%s matching query does not exist." %
--> 408                 self.model._meta.object_name
    409             )
    410         raise self.model.MultipleObjectsReturned(

DoesNotExist: Profile matching query does not exist.
```

Is there perhaps something wrong with our DB setup, insofar cacheops is interacting with our DB schema in a funny way, whcih is causing the exception?

Or perhaps there is somewhere in the django-cacheops code that is failing noisily?

I'm hoping for any assistance in figuring this out. Please and thank you .

**Comment by owocki** [comment]
i took the liberty of addings some debugging code to `~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/query.py`, to see what `args` and `kwargs` looked like.  seems like they are both falsy, i wonder if we can figure out which field is failing to be looked up!

```
In [2]: Profile.objects.last().delete()
() {}
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-2-3b13653b2b8b> in <module>()
----> 1 Profile.objects.last().delete()
......
```

**Comment by owocki** [comment]
by inserting some debug code into `~/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/db/models/query.py` which prints the `model` and `obj` fields:

```
<class 'avatar.models.SocialAvatar'> lamegaz created 2021-01-23 00:36:43.595256+00:00
<class 'marketing.models.EmailSubscriber'> xxxx@hotmail.com
<class 'dashboard.models.Activity'> lamegaz type: joined created: today needs review: False
<class 'dashboard.models.Activity'> lamegaz type: updated_avatar created: today needs review: False
<class 'dashboard.models.UserAction'> Visit by lamegaz at 2021-01-23 00:36:55.646841+00:00
<class 'dashboard.models.UserAction'> Login by lamegaz at 2021-01-23 00:36:44.651876+00:00
<class 'dashboard.models.Profile'> lamegaz
```

looks like it's following all of the foriegn keys in the model, and failing when it gets back to a (perhaps self referential) foreign key?

i dont see why it's doing that though, there are no foriegn keys to `Profile` model to `Profile`, other than `referrer`, which is NULL for this user (though maybe there is a self-referrential loop of Foreign Keys from `Profile` => `User` and back to `Profile` that is causing this race condition. (here is the model itself - https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py#L2773)

after digging in on this, i am 80% sure that were in some sort of foreign key loop / race condition.  the cacheops `invalidate_obj()` method doesnt seem to know how to handle.

**Comment by owocki** [comment]
Just throw together a forked version of django-cacheops that fails silently when this exception occurs ( https://github.com/gitcoinco/django-cacheops/blob/master/cacheops/invalidation.py ) and it at least allows us to delete these objects again

```
In [1]: from dashboard.models import Profile

In [2]: Profile.objects.last().delete()
failed to invalidate job_location; got exception Profile matching query does not exist.
failed to invalidate as_dict; got exception Profile matching query does not exist.
failed to invalidate as_representation; got exception Profile matching query does not exist.
```

looks like its the JSONFields within the profile model ( https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py#L2773 ) that are failing to invalidate. i am not sure why.

i made a PR back to the gitcoin repo with this workaround on it https://github.com/gitcoinco/web/pull/8296 , but i think I'd need some help from the django-cacheops maintainers to understand why JSONFields are failing to invalidate in django-cacheops 5.1 , and to help remediate for other users' purposes.

**Comment by Suor** [comment]
Looks like you use `.only()` or `.defer()`, which makes `getattr()` trigger a db request. This isn't something I expected, the object is deleted already so it fails to fetch.

The fix would be to fetch object in full in `pre_delete` or simply skip deferred fields. The second option might obviously not invalidate somethings.

**Comment by owocki** [comment]
@Suor no worries; i know that open source maintenance is a side hustle for many :)

We dont use `.only()` or `.defer()` anywhere in our codebase for this model (i just grepped, and I didnt find it), but perhaps another pip module does (it seems this only happens with Postgres JSONFields, so maybe that is a hint?).  We'd be happy to use your suggested fix "The fix would be to fetch object in full in pre_delete or simply skip deferred fields.", but I suspect that a root cause fix on another pip module that uses `.only()` or `.defer()` may be in order.

**Comment by Suor** [comment]
If it is only JSONFields you can add it to `CACHEOPS_SKIP_FIELDS`, and they won't be used in invalidation. BTW, I probably should add them to default settings too.

You stacktrace suggests that they defered, which means their contents are loaded in a separate db request once for every (object, field) pair upon access - see how `getattr()` triggers database request. Maybe you are using some special JSONFields or special model superclass or special managers that defer for you automatically.

**Comment by fdemmer** [comment]
Thank you for 1952ecc and cacheops in general! Minor change, major impact; I just wanted to add for the record that I ran into this issue with cacheops 5.

In my codebase there was query optimization in the admin, that made it only fetch the columns required to display the changelist using `queryset.only(...)`. Therefore deleting objects directly from the changelist failed with the same `DoesNotExist` described here.

All good with cacheops 6. ✨
