### ISSUE TITLE
pre_save still fires query if CACHEOPS_ENABLED=False 

### ISSUE THREAD

**Issue by caffodian** [Suor/django-cacheops#388]
Just getting started with this library, so I might be missing something:

Should the _pre_save still be doing a `get` if cacheops is disabled?  Seems like it will not be used in _post_save anyway. I'm just making sense of the code now and am not sure if this is intended.

This is causing some issues with us trying out the library, since a bunch of querycount related tests all get an extra query for every thing that is saved, even with caching disabled. Happy to PR something if this is in fact unintended.

Thanks!

**Comment by Suor** [comment]
Looks, like a bug.
