### ISSUE TITLE
Invalidate outside of Django

### ISSUE THREAD

**Issue by Siecje** [Suor/django-cacheops#389]
I have code outside of Django that is making changes but the cache is not being invalidated.

Is it possible to manually remove the redis keys for the cache for that object?

**Comment by Suor** [comment]
If you use Django ORM it should be handled automatically. You need to run `django.setup()` to make it usable. If you make changes not via ORM but still have access to it you can use `invalidate_obj()` and friends, see README.

Then if you don't have access to ORM at all, i.e. changing something from a non-python script it becomes complicated. You basically need to call `invalidate.lua` script properly see `invalidate_obj()/dict()` implementation.

**Comment by Siecje** [comment]
This is a different codebase but still Python. I could create an `managed = False` model. Would I need all of the fields?

**Comment by Suor** [comment]
Why can't you simply use the same codebase?

On fields, if you omit ones that you never use for filtering that won't affect invalidation. It might be easier to use `invalidate_dict()` though.
