### ISSUE TITLE
cache views that have different content according to user privileges

### ISSUE THREAD

**Issue by fcoppey** [Suor/django-cacheops#397]
is it possible to do that?

in my html template I have some parts that are admin related therefore I  test if user is staff and if it's the case I display extra content. thing is when caching this view I don't know how to cache a version for admins and a version for normal users. any idea?

thanks a lot

**Comment by Suor** [comment]
You can used a nested function to build up a key, which includes that:

```python
from cacheops import cached_view_as

def your_view(request, ...):
    @cached_view_as(queryset, extra=request.user.is_staff)
    def _your_view(request, ...):
        # ... do the stuff
        return render(...)

    return _your_view(request, ...)
```

You may also look at `articles_block()` example in README.

**Comment by fcoppey** [comment]
Ok thanks. How would it work for class based ListView or DetailView?

On 22 Apr 2021, at 06:49, Alexander Schepanovski ***@***.******@***.***>> wrote:



You can use a nested function to build up a key, which includes that:

from cacheops import cached_view_as

def your_view(request, ...):
    @cached_view_as(queryset, extra=request.user.is_staff)
    def _your_view(request, ...):
        # ... do the stuff
        return render(...)

    return _your_view(request, ...)

You may also look at articles_block() example in README.

**Comment by Suor** [comment]
How do you use them at all?

**Comment by fcoppey** [comment]
I have followed recommendation :



class NewsIndex(ListView):
    model = News

news_index = cached_view_as(News)(NewsIndex.as_view())


My question is how can I condition this view to the user privileges?


On 22 Apr 2021, at 09:51, Alexander Schepanovski ***@***.******@***.***>> wrote:



How do you use them currently?

**Comment by Suor** [comment]
Added an ability to use callable as `extra` in latest master:

```python
cached_view_as(News, extra=lambda req: req.user.is_staff)
```

You can try that.
