### ISSUE TITLE
Error:  LookupError: No installed app with label 'migrations'.

### ISSUE THREAD

**Issue by 3lf** [Suor/django-cacheops#398]
Hi 
I get this error if redis is down :
![Screenshot from 2021-04-24 06-44-39](https://user-images.githubusercontent.com/25196606/115944014-ae52ab80-a4c8-11eb-98d2-9c5b5558326e.png)

my setting:
![Screenshot from 2021-04-24 06-44-50](https://user-images.githubusercontent.com/25196606/115944020-b4488c80-a4c8-11eb-9de9-95b0ac8bbdb7.png)

can I set cacheops off if redis is down?

**Comment by Suor** [comment]
I really not recommend caching all the models like that, including things like migrations. To skip cache on redis failure you may use:
```python
CACHEOPS_DEGRADE_ON_FAILURE = True
```
It might overload you db under load of cause.
