### ISSUE TITLE
Response time is not reduced with DRF

### ISSUE THREAD

**Issue by nishankgarg** [Suor/django-cacheops#401]
Hi,
I have added the following settings.
```
CACHEOPS_REDIS = "redis://localhost:6379/7"

CACHEOPS = {
    'auth.user': {'ops': 'get', 'timeout': 60*15},
    'auth.*': {'ops': {'fetch', 'get'}, 'timeout': 60*60},
    'auth.permission': {'ops': 'all', 'timeout': 60*60},
    '*.*': {'ops': 'all', 'timeout': 60*60},

}
```

I have verified the data is getting cached in redis as follows:
```
...
1885) "q:488bb37d4dce751fc4082b689ee3fc2d"
1886) "q:d81933c5b0cbd3ef8f56082930716820"

```

However, the response time is not getting reduce.
Let me know if I am missing something.

**Comment by Suor** [comment]
Strictly speaking cache is not about response time. It takes the load out of you database and if that was a bottleneck increases throughput. If your database answers as fast cache then extra caching layer will add to response time. I.e. caching simple queries to sqlite is usually slower than performing them. 

All the above being sad you might still not cache all the things you want or invalidate them on every request unwillingly. You can check whether you database is still being hit by logging queries ad/or monitor `cache_invalidated` signal of cacheops.

**Comment by nishankgarg** [comment]
Yes, database is getting hit and cache_invalidated signal is not called since I can see all the data in redis.
How does cacheops returns the cached data on list/ api call?
Is there some extra setting required for that?

**Comment by Suor** [comment]
> cache_invalidated signal is not called since I can see all the data in redis

How do you know "all the data" is in redis and not only some. Also, even if all the data in there when you are looking doesn't mean it stays there all the time. So unless you connect to `cache_invalidated` and e.g. log something you can't be sure it is not happening. You can also monitor `cache_read` signal and look at its `hit` param, if you get `False` there then you have cache misses.

> How does cacheops returns the cached data on list/ api call?

Cacheops knows nothing about API calls, it caches database requests. 

> Is there some extra setting required for that?

Maybe you are making count queries there too.

**Comment by nishankgarg** [comment]
Can you share some example repository in DRF having Cacheops applied.
This will help me in understanding how to exactly apply cacheops.

**Comment by Suor** [comment]
I don't have an example repo.

**Comment by ConfidenceYobo** [comment]
I am also experiencing the same thing. Using DRF with Debug-toolbar the SQL queries are being run twice.
Here is an example of what I did:

#### My Settings Configuration
```python
CACHE_TTL = 60 * 15
CACHE_TTL_ONE_HOUR = 60 * 60
CACHE_TTL_TEMPORARY = 60 * 2

CACHEOPS_REDIS = "redis://%s/0" % config('REDIS_ENDPOINT') # Using decouple to load env file configurations

CACHEOPS = {
    'auth.user': {'ops': 'get', 'timeout': CACHE_TTL},

    # Automatically cache all gets and queryset fetches
    # to other django.contrib.auth models for an hour
    'auth.*': {'ops': {'fetch', 'get'}, 'timeout': CACHE_TTL_ONE_HOUR},

    # Cache all queries to Permission
    # 'all' is an alias for {'get', 'fetch', 'count', 'aggregate', 'exists'}
    'auth.permission': {'ops': 'all', 'timeout': CACHE_TTL_ONE_HOUR},

    # Enable manual caching on all other models with default timeout of an hour
    # Use Post.objects.cache().get(...)
    #  or Tags.objects.filter(...).order_by(...).cache()
    # to cache particular ORM request.
    # Invalidation is still automatic
    '*.*': {
        'ops': {'all', 'filter', 'get', 'count', 'exists'},
        'timeout': CACHE_TTL_TEMPORARY
    },
}
```
And here Is what I tried in the view:
```python
users_list_one = User.objects.filter(is_staff=False, institution__isnull=False).filter(Q(username__icontains=query) | Q(
            fullname__icontains=query) | Q(
            bio__icontains=query)).exclude(Q(username__isnull=True) | Q(
                username='') | Q(institution__isnull=True)).annotate(followings=Count('follows')).defer('institution', 'profile_settings').cache()
print(users_list_one)

users_list_two = User.objects.filter(is_staff=False, institution__isnull=False).filter(Q(username__icontains=query) | Q(
            fullname__icontains=query) | Q(
            bio__icontains=query)).exclude(Q(username__isnull=True) | Q(
                username='') | Q(institution__isnull=True)).annotate(followings=Count('follows')).defer('institution', 'profile_settings').cache()
print(users_list_two)
```

If I try doing something like `users_list_two.count()` it would still hit the database.
I made two queries on purpose to test the caching and my use case would require running a function that will call this query twice.

Perhaps there is something am not doing right

**Comment by Suor** [comment]
I saw queries done twice under debug toolbar without caching sometimes.

**Comment by ConfidenceYobo** [comment]
Is that right? because that may be expensive in some scenarios. Shouldn't it fetch the second query from cache or something like that?

**Comment by Suor** [comment]
Debug toolbar should not be enabled on production anyway. So expensive doesn't matter for it.

**Comment by ConfidenceYobo** [comment]
Debug toolbar won't be used on production. I'm just a bit doubtful as there is no way to very that the queries are being cached

**Comment by Suor** [comment]
One can use query logging instead of Django Admin toolbar to see queries. And cacheops signals I mention above could be used to see what is cached/invalidated.
