### ISSUE TITLE
Not able to cache specific models after setting up CacheOps

### ISSUE THREAD

**Issue by aroraprince** [Suor/django-cacheops#403]
I have quite many Type models that hold choices.
I intended to cache those models specifically.

I tried adding the models as below:
```
CACHEOPS = {
     'reference_data.models.referenceregiontype': {'ops': 'all', 'timeout': 60*60},
     'reference_data.models.referencecontinenttype': {'ops': 'all', 'timeout': 60*60},
     'reference_data.models.referencecountrytype': {'ops': 'all', 'timeout': 60*60},
     .....
     .....
}
```

Also tried with:
```
CACHEOPS = {
     'reference_data.models.ReferenceRegionType': {'ops': 'all', 'timeout': 60*60},
     'reference_data.models.ReferenceContinentType': {'ops': 'all', 'timeout': 60*60},
     'reference_data.models.ReferenceCountryType': {'ops': 'all', 'timeout': 60*60},
     ......
     ......
}
```
`cacheops` has been installed and is in `INSTALLED_APPS`

I don't want to use `.*` syntax since there are other models in the files as well which I don't want to cache.

I am adding models like 
`'reference_data.models.ReferenceRegionType'`
and not

`'reference_data.ReferenceRegionType'`

since in a few apps, models is a directory and the path could be something like.

`'reference_data.models.types.ReferenceRegionType'`

Am I missing anything here?

**Comment by Suor** [comment]
`'reference_data.models.referenceregiontype'` -> `'reference_data.referenceregiontype'`'

These are not import paths but Django's `app.model_name` notation.

**Comment by aroraprince** [comment]
@Suor I noticed that, I added more details in my query at the end.
How should I handle where I have models as a directory on a few apps?

**Comment by Suor** [comment]
It doesn't matter where model classes reside. Django identifies models by `(app_label, model_name)` pair.

**Comment by aroraprince** [comment]
Thanks, was checking that.
Will close the issue in a bit, once I see it working.

**Comment by aroraprince** [comment]
Okay, I think this particular issue got solved.
I don't see any performance boost for my admins pages though, using django-cacheops.
Whereas with django-cache-machine I could see a significant drop in number of queries.

**Comment by Suor** [comment]
cache is disabled in admin deliberately.

**Comment by Suor** [comment]
You may enable it on a by queryset basis.

**Comment by aroraprince** [comment]
Okay, thanks for your time.
Is there any place where I can understand the rationale behind this?

All the models that I use inherit from a BaseAbstractClass.
Wondering if overriding the manager on my BaseClass and caching get_queryset, would work for me in that case.

I know I should not compare, but django-cache-machine sort of worked out of the box for me, just it did not look very up to date so was trying with this.

**Comment by Suor** [comment]
The queries in admin are different from usual ones so saving them to cache will simply pollute redis. And caching is not about speeding up queries but to increase throughput. For admin one might for example limit fields to be selected.

Changing base class will probably work, using `.get_queryset()` admin method would be more specific, may also employ a mixin to set it in several admins.

**Comment by aroraprince** [comment]
Okay, thanks.
For my use case, I had a lot of models which save type(you can consider them as Choices).
Need to reduce the number of DB queries for those as it is a pretty static data and needs to be looked up pretty frequently,
