### ISSUE TITLE
Read queries with round-robin load-balancing on slave instances when using Sentinel

### ISSUE THREAD

**Issue by mohammad-babaei** [Suor/django-cacheops#409]
Reading the source code i realized that reading from cache is not from replicas and all operations are done on a single master in Sentinel mode.
And if the master node fails and an automatic failover takes place, Cacheops still tries to work with previous master node not the new one.
Would you consider doing this in future?

**Comment by Suor** [comment]
cacheops provides `CACHEOPS_CLIENT_CLASS` for things like this. Many people used it successfully. I don't work on any higher level support though - I don't need it myself and it proved to be hard to generalize so people don't do that and don't contribute back.
