### ISSUE TITLE
Why the keep_fresh parameter in cached_as does not default to True ?

### ISSUE THREAD

**Issue by nMustaki** [Suor/django-cacheops#424]
Hello Suor,

first thanks for your work, it's very helpful here !
I'd like to ask some help to understand why the `keep_fresh` parameter of cached_as does not default to True ? Why would we want to cache stale data ?
Thanks !

**Comment by Suor** [comment]
In short:
- it costs to recheck
- if we do not cache while concurrent invalidation is happening we may never cache if we are under heavy invalidation
- if there are lots of invalidations stale cache won't survive long anyway

Sometimes not caching will mean app will just hang up, which is worse than serving something stale. 

You can take a look at original PR too https://github.com/Suor/django-cacheops/pull/302

**Comment by nMustaki** [comment]
Thanks you, that's a lot clearer !
