### ISSUE TITLE
AtomicMixIn doesn't re-raise commit exceptions

### ISSUE THREAD

**Issue by yamnikov-oleg** [Suor/django-cacheops#427]
https://github.com/Suor/django-cacheops/blob/ad83e51b6d82ba2bf4820953925ff889e4c4b840/cacheops/transaction.py#L74-L79

If the `__no_money__` object fails to commit the transaction and raises a `DatabaseError`, cacheops silences the exception. This sometimes makes integrity errors hard to discover, since transactions fail to commit without notice.

This `except` block should contain a `raise` operator.

**Comment by Suor** [comment]
It looks like it. Do you want to make a PR?

**Comment by yamnikov-oleg** [comment]
Yes, I'll make a PR as soon as I can
