### ISSUE TITLE
cache response of DRF view?

### ISSUE THREAD

**Issue by palvarezcordoba** [Suor/django-cacheops#439]
Hi, I'm wondering if there's any convenient way to cache the response of a Django Rest framework endpoint.
For what I've seen, there's no easy way.

I did this to use cacheops to cache the response, invalidating it if the model Project was created/changed/deleted:
```python
def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)

        @cached_as(
            Project,
            extra=lambda: (
                request.user.user_type,
                request.user.country,
                request.user.currency_token,
                request.user.company.is_intracommunity_operator if request.user.company else False,
            ),
        )
        def _list():
            if page is not None:
                serializer = self.get_serializer(page, many=True)
                return serializer.data
            serializer = self.get_serializer(queryset, many=True)
            return serializer.data
        data = _list()
        if page is not None:
            return self.get_paginated_response(data)
        else:
            return Response(data)
```

I needed a fast solution so this works for me, at this time. But I can't keep doing this all over the project if I need do cache more endpoints.

**Comment by reallyBhatti** [comment]
Did you figure out a simpler solution to this? 
I am currently trying to do something similar and I've got numerous APIs. Doing this all over the project is not feasible.

**Comment by campenr** [comment]
Does the **View caching** from the README not fit your needs? Per the docs:

```
from cacheops import cached_view_as

@cached_view_as(News)
def news_index(request):
    # ...
    return render(...)
```
    
Or in your case

```
from cacheops import cached_view_as

@cached_view_as(Project)
def list(self, request, *args, **kwargs):
    # ...
```

This decorator also takes the `extra` argument so you can pass the same lambda as in your example if needed.

**Comment by palvarezcordoba** [comment]
@campenr I don't know why I didn't do it that way.
I'll try that today/tomorrow and will say if worked or not.

@reallyBhatti Sorry, I didn't read github notifications.
I'm still doing it very similar to my original comment.
You can try to do it the way @campenr said

**Comment by Suor** [comment]
I never used DRF myself but saw people used some subclasses to marry it with cacheops.

A couple of notes on original code sample:
1. One might pass queryset to `@cached_as()` and `@cached_view_as()`, this will probably result in a more granular invalidation than simply passing `Project`.
2. `extra` does not need to be a lambda, it could be the tuple directly.

**Comment by modbender** [comment]
@Suor I wanted to use `cached_view_as`, but the request received inside REST API view is of type `rest_framework.request.Request`

But you have a assert at 
https://github.com/Suor/django-cacheops/blob/eb8218b5fc602fa8d89a3fc4317eb9482f42b71d/cacheops/utils.py#L106 
checking if the request is of type `HTTPRequest` which is raising error
`AssertionError: A view should be passed with HttpRequest as first argument`

**Comment by Suor** [comment]
One of the things `@cached_view_as()` does is calling `.render()` method on a response, this is done to fill it in properly before serializing and sending to cache. This might be interfering with what DRF expects, i.e. this `.accepted_renderer` doesn't look like a part of Django. It would be somewhat bit weird for cacheops to know such DRF internals, so the proper place to glue such things is the code using both. I would maybe ignore that being weird if this request were very common or if I myself used DRF and were familiar with its internals. For now though I don't think this belong to cacheops code.

There are ways for you to make it work though. The most trivial is cache only queryset not the list or whatever:
```python
class BaseModelViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        return super().get_queryset().cache()

    class Meta:
        abtract = True
```

Similary trivial will be just setting caching for needed models automatically in `CACHEOPS` settings.

If you insist on caching the list then you way try a more generic purpose `@cached_as()` instead:
```python
class BaseModelViewSet(viewsets.ModelViewSet):
    def list(self, request, *args, **kwargs):
        qs = self.get_queryset()

        # All arguments to this will be used in a cache key, HttpRequest will be turned into uri and
        # some other transformation are made, but be aware of what you are passing here. Anything
        # not varying the result should not go.
        @cached_as(qs)
        def _cached_list(request, *args, **kwargs):
            # This should not return any lazy thing
            return super(BaseModelViewSet, self).list(request, *args, **kwargs)
        
        return _cached_list(request, *args, **kwargs)

    class Meta:
        abtract = True
```

`@cached_view_as()` is a shallow enough wrapper for `@cached_as()` doing only a couple of things

**Comment by Suor** [comment]
This should do it for now. Please reopen if none of the recipes works though.

**Comment by Suor** [comment]
So it's indeed a `TemplateResponse` you need to render it the same way `@cached_view_as()` does.

**Comment by Suor** [comment]
There is an unfinished PR about this #453
