### ISSUE TITLE
Limit caching to certain DB to support Postgres followers

### ISSUE THREAD

**Issue by chickahoona** [Suor/django-cacheops#441]
## Problem

We are having this django setup with a Postgres master and a follower  that we are using for read only operations, so something like this:

```
READ_ONLY_DB = 'follower'
DATABASES = {
    'default': dj_database_url.config(default='postgres://postgres:abcdEF123456@...:5432/master'),
    'follower': dj_database_url.config(default='postgres://postgres:abcdEF123456@...:5432/follower')
}
```

If we quzery now the master we just do this:

```python
MyModel.objects.get(pk=my_model_id)
```

But whenever we want to query the follower we need to make sure that cacheops isn't caching anything.
```python
MyModel.objects.using(settings.READ_ONLY_DB).nocache().get(pk=my_model_id)
```

If we forget `nocache()`, it caches the entry and if we maybe half an hour later would do:

```python
my_model = MyModel.objects.get(pk=my_model_id)
my_model.name = 'somethingelse'
my_model.save()
```

it will pull the entry from the cache (which still "knows" that it came from the save) and then the `save()` method will throw this exception:

```
Cannot assign "<MyModel: ...>": the current database router prevents this relation.
```

Obviously the follower doesn't allow write operations ... This wouldn't be too problematic as one just needs make sure that one isn't forgettting the `nocache()` after `using(...)`. The real fun starts when you chain querysets. These chained querysets are actual copies of the original queryset and seem to "lose" this `nocache()` info while the `using(...)` info is preserved. So after every `filter(...)` or `values(...)` i need to call `nocache()`, especailly when these filter or values options query related objects. I am not even sure where it needs to be added always but we had a lot of bugs with this approach and finding them is HARD due to the reason that the error is thrown somewhere else in the code and one always needs to check where one added caching before or maybe added a new feature that might use it. :(

## Solution:

Would it be possible that one can define a whitelist or blacklist, so cacheops doesn't cache anything of our 'follower`. Then we could drop all these `nocache()` calls and our code would become much simpler and less error prone.

Thank you very much for consideration!

**Comment by Suor** [comment]
I don't remember having any out of the box solution in cacheops. However:
1. You might take a look at `db_agnostic` setting. 
2. You probably want to wrap your fetch/save code into transaction and add select for update to fetch, depending on your database router it might fix your issue indirectly. It also will prevent races. 
3. Alternative to 2 is passing `update_fields` to `Model.save()` if you also pass `using=”default”` there or set up database router to do it for you. This should also fix the issue. 
4. It should not be required to redo `.nocache()` unless you call `.cache()` again later. I.e. queryset chaining should preserve this. If it does not then that is the bug. It would be very helpful if you could isolate it and write a test - the instruction is in the end of the README.
