### ISSUE TITLE
Documentated code for reap_conjs is not in 6.1 version

### ISSUE THREAD

**Issue by nMustaki** [Suor/django-cacheops#446]
Hello,

thanks for the project !
The README documents `reap_conjs`, but it's not in the 6.1 version.
While the release is being prepared, maybe add a small warning that it's not released yet ? I can open a PR if you're ok.

Do you know when the next release with is scheduled ?

Thanks !

**Comment by Suor** [comment]
The README goes from master. The issue here is probably that I didn't release this soon enough, I will just make a release soon

**Comment by Suor** [comment]
Released in 6.2
