### ISSUE TITLE
v7 removed CacheOpsRedis but is not listed as backwards incompatible change in CHANGELOG

### ISSUE THREAD

**Issue by palvarezcordoba** [Suor/django-cacheops#448]
https://github.com/Suor/django-cacheops/compare/6.2..7.0

![imagen](https://user-images.githubusercontent.com/37622818/225602121-b4a8c97d-1650-4d39-9d10-e3ec93798f2a.png)

Is there a reason this is not listed as backwards incompatible change?
In my settings i have CACHEOPS_CLIENT_CLASS = 'cacheops.redis.CacheopsRedis'
And after upgrading to cacheops 7.0.0, it gives an error on server startup.

What changes are needed to upgrade to 7.0.0?

**Comment by Suor** [comment]
That's true, there is no such thing anymore, one should simply descend from Redis class. 

I forgot about this change when compiling the CHANGELOG. Your setting was always a noop though and could be safely removed.
