### ISSUE TITLE
`.aggregate()` is broken on 7.0

### ISSUE THREAD

**Issue by ukrarome** [Suor/django-cacheops#452]
Caching on `.aggregate()` method is broken in PR #https://github.com/Suor/django-cacheops/commit/e277e1ea09258cd981091be777abcc3cef79b03a
It no longer takes aliases into account
Example:
```python
s.packages.all().aggregate(dives=Max('dives_in_package'))
>> {'dives': None}

# cache
s.packages.all().aggregate(another_alias=Max('dives_in_package'))
>> {'dives': None}

# no cache
s.packages.all().nocache().aggregate(another_alias=Max('dives_in_package'))
>> {'another_alias': None}
```

**Comment by Suor** [comment]
Interesting, can you make a test of it? There is an instruction in README.

**Comment by ukrarome** [comment]
Is it fixed?

**Comment by Suor** [comment]
Yes

**Comment by ukrarome** [comment]
7.0.1  - still not working
