### ISSUE TITLE
Support for funcy > 2

### ISSUE THREAD

**Issue by fabaff** [Suor/django-cacheops#454]
https://github.com/Suor/django-cacheops/blob/master/setup.py#L29 limit the funcy releases. [2.0](https://github.com/Suor/funcy/blob/2.0/CHANGELOG) was released a while ago.

Are there any plans to support funcy > 2.0? 

This mainly affects distributions which are shipping django-cacheops as package and not users who are working with a `venv`.

**Comment by Suor** [comment]
I should probably work as is.

**Comment by Suor** [comment]
Fixed in b778177a1cbc776ace79ec234c25bdca8aa181ab.
