### ISSUE TITLE
in combination with django-tenant-schemas, "public" tables caching is not working

### ISSUE THREAD

**Issue by jacopsd** [Suor/django-cacheops#458]
Using django-cacheops in combination with django-tenant-schemas
Works fine for tenant specific tables, but doesn't not cache tables in the "public" tables which are shared over all tenants.

Probably setting the postgres schema to "public" is not foreseen, and hence this does not work.
Any suggestion on where to tackle this in the source?
Thank you.

**Comment by Suor** [comment]
Sorry for slow response. If you can make a test or a test project this would help to speed this up.
