### ISSUE TITLE
features to prevent cache stampede

### ISSUE THREAD

**Issue by moonseoklee** [Suor/django-cacheops#460]
'*.*': {'ops': 'all', 'timeout': 6000}
Is there any way to prevent cache stampede when using cacheops globally like above? Globally using methods like MintCache, debouncing, etc.! lock is currently not helping me much.

**Comment by moonseoklee** [comment]
https://github.com/Suor/django-cacheops/issues/289
I see there's already a thread for the feature I'm looking for, thanks for the response. I'll close this one.

**Comment by Suor** [comment]
Added a hint about that in the other thread https://github.com/Suor/django-cacheops/issues/289#issuecomment-1696973293.
