### ISSUE TITLE
django-cacheops not working with Django version 4

### ISSUE THREAD

**Issue by venkatvamshi** [Suor/django-cacheops#461]
Hi Team, 

I am new to Django and django-cacheops. 
We are using
Django==4.1.7
django-cacheops =7 .0.1
python 3.9

When trying to start the app. We are getting `cannot import name 'force_text' from 'django.utils.encoding'` error. 
I tried going through django.utils.encoding documentation. 

looks like there `force_str` instead of `force_text` in django 4.  https://docs.djangoproject.com/en/4.0/ref/utils/#module-django.utils.encoding. 

If i had to downgrade django version to 3.2.x i have to change many other dependencies as well. 

Is there a workaround for this. 

<img width="481" alt="Screenshot 2023-08-30 at 8 00 16 PM" src="https://github.com/Suor/django-cacheops/assets/10359735/51a1ec34-6ec8-4929-8aa7-a26f3d5fb343">
<img width="473" alt="Screenshot 2023-08-30 at 8 13 52 PM" src="https://github.com/Suor/django-cacheops/assets/10359735/9732a281-e428-4e17-9a23-eb3a6df85d52">

Thanks.

**Comment by Suor** [comment]
I can't find force_text() anywhere in cacheops, so it must be imported somewhere else or you have older version of cacheops. 

Looking at full stack trace might give some clue.

**Comment by venkatvamshi** [comment]
Thanks for the reply Suor. 

Looks like query.py > QuerySetMixin > _cache_key function on line 179 has force_text. 

BTW i am using the latest version of django cacheops.

<img width="1083" alt="Screenshot 2023-08-31 at 11 10 53 AM" src="https://github.com/Suor/django-cacheops/assets/10359735/d1a80743-ef1a-4596-b3cd-a5c864bda6cf">

**Comment by Suor** [comment]
Here is [query.py](https://github.com/Suor/django-cacheops/blob/7.0.1/cacheops/query.py) and it doesn't have `force_text()` anywhere. You are using older version of cacheops.
