### ISSUE TITLE
Unable to disable cacheops primitives

### ISSUE THREAD

**Issue by rain01** [Suor/django-cacheops#462]
I am using caheops primitives on top of the usual query caching in my view and I was trying to disable cacheops for tests but cacheops primitives never get disabled with `CACHEOPS_ENABLED = False`.

```
from cacheops import cache
cache.set(cache_key, data, timeout=60*60)
```

**Comment by Suor** [comment]
This is how they work. `CACHEOPS_ENABLED = False` only disables decorators and QuerySet methods. I don't want to add checks for this to every get/set call.

You can use mocking instead for tests.
