### ISSUE TITLE
Memory problem on django test init

### ISSUE THREAD

**Issue by cansarigol** [Suor/django-cacheops#463]
After installing 7.0.1 version, our memory usage of ci test pipeline on GitLab increased by over 12GB. Normally with 7.0 or 6.0 versions it is 4GB. Spesificly when i revoked the below code, i can trace that init cache prevents for the fake models and memory doesn't increase.

Can it be put back? or do you have a suggestion on the configuration level?

https://github.com/Suor/django-cacheops/commit/55179e3657df351257c54faa07af1bd8c39e3a0c#diff-f277025cad81b6bcc78c7a85cd938de600acf8ab2c28bb14226bb712ed77a672L402

![Screenshot 2023-10-18 at 08 32 40](https://github.com/Suor/django-cacheops/assets/5008696/8ca3ad79-5c91-4473-8672-dc4836a58ab6)

**Comment by cansarigol** [comment]
Yes exactly. There is no problem with caching fake modules but they are memorized

**Comment by Suor** [comment]
Thanks for finding this.

**Comment by Suor** [comment]
Might be a good idea to use weak refs for memory :)

**Comment by cansarigol** [comment]
@Suor are you planning to release this fix with 7.0.2 tag? It would be great for me to bump it my project. Thanks in advance.

**Comment by Suor** [comment]
I will let it sink a bit, in case something else comes up.

**Comment by Suor** [comment]
Released the fix in 7.0.2
