### ISSUE TITLE
DB migrations are being cached even after using setting migrations timeout to zero 

### ISSUE THREAD

**Issue by shivambalwani0704** [Suor/django-cacheops#465]
If we add a new column in a table and then try ti run server or makemigrations or to migrate it shows key not available in query list . After looking we found out about db migrations being cached but when we tried to set the migration timeout to zero still the same issue persists.

**Comment by Suor** [comment]
You need to be more specific in what you are doing and what you are getting. I.e. specific commands, code changes and error messages. For now it's totally puzzling for me what it is this about.

**Comment by shivambalwani0704** [comment]
I am using Cacheops = 6.1 and Django = 3.1.5 , I haven’t  initialised Cacheops with wildcard or neither  have used any models with django prefix but despite it I suspect it's caching Django migrations table because whenever we add any field in the models that we are caching it throws an error (1054, "Unknown column 'portfolio_programme.course_sub_category' in 'field list'")  
And then to make migration I need to disabled cache and then perform it

**Comment by Suor** [comment]
What makes you believe cacheops has anything to do with this? Especially if you didn't even cache anything.

**Comment by shivambalwani0704** [comment]
As we disabled cacheops it worked fine.

**Comment by Suor** [comment]
Ok, you still need to be more specific. Like what actually you doing: commands, code changes, errors with stack traces. Including how do you disable cacheops.

**Comment by Suor** [comment]
Also did you try updating cacheops to the latest version?
