### ISSUE TITLE
Question on @cached_as

### ISSUE THREAD

**Issue by Elendiar** [Suor/django-cacheops#467]
I understand that `select_related` not invalidated, but why i cant force invalidate it with `cached_as` and emplicit models definition as samples? 
I assumed this should work, but it doesn't

```
@cached_as(Project, Area, Subarea, Location, keep_fresh=True)
def _get_cached_select_related(queryset: QuerySet[WCCSheetTemplate]) -> QuerySet[WCCSheetTemplate]:
    return queryset.select_related('project', 'area', 'subarea', 'location')
```

Is there any way to perform manual explicit invalidation? (Think about `invalidate_model` in every model `(pre_delete, pre_save)` signal). Or maybe use `.nocache()` on complicated queries with few select_related and prefetch_related with nested select_related.

PS. Also i have issue with caching `Coalesce(_get_cached_subquery(), 0) - no invalidation when subquery inside Coalesce, but invalidate without Coalesce cached_as subquery.

**Comment by Suor** [comment]
Your code sample caches the queryset before any SQL query is done, this won't work. I.e. the results of the query won't be cached, the query will be executed every time unless you pass a queryset, which was an all already filled in. 

Another thing is passing the queryset as an argument. Arguments are the keys to cache entry, you are supposed to use some primitive types there. If you pass a queryset it will be stringyfied and that used as a key. Stringing a queryset involves executing the underlying SQL query, which is probably not what you want.
