### ISSUE TITLE
Redis getting called too many times in a single API call.

### ISSUE THREAD

**Issue by MahnoorShafique** [Suor/django-cacheops#468]
I am inheriting my classes in views from ModelViewSet . and using builtin for queryset and serializer class upon configuring django-cacheops I saw so many calls to ElastiCache in ELK server for a single transaction. What is the reason for this?

**Comment by Suor** [comment]
All cacheops calls are either get cache, set cache or cache invalidation, which happens upon save/delete signals. 

You can:
- set up database queries logging, and look if you do many
- try removing cacheops and see how many new database queries you do now
- set up cacheops signals to put stack traces to your logs or sentry or whatever to see exactly where these calls come from.

**Comment by MahnoorShafique** [comment]
@Suor This is my viewset Class:
class BookViewSet(ModelViewSet):
    permission_classes = [IsAuthenticated | RetoolIPPermission | HasAPIKey]
    queryset = Book.objects.select_related("grade_subject").all()
    serializer_class = BookSerializer
    http_method_names = ["get"]

    filter_backends = [DjangoFilterBackend]
    filterset_class = BookFilter

class Book(TimeStampedModel):
     grade_subject = ForeignKey(GradeSubject, on_delete=SET_NULL, null=True)
    ... 
    other fields
    ....
   
class GradeSubject(TimeStampedModel):
    grade = ForeignKey(Grade, on_delete=SET_NULL, null=True)
    subject = ForeignKey(Subject, on_delete=SET_NULL, null=True)
![image](https://github.com/Suor/django-cacheops/assets/68817446/f945351f-6fdc-4dab-9f8a-3764f9e3d8a0)
as you can see in image it calls db for 1 time but calls redis 1960 times. I have implemented caching using django-cacheops. what's missing , I am unable to debug. Can you please guide?
