### ISSUE TITLE
Django Admin not invalidating cache on save

### ISSUE THREAD

**Issue by northkode** [Suor/django-cacheops#469]
we have a pretty basic config:

```
CACHEOPS = {
    'auth.user': {'ops': 'get', 'timeout': 60 * 15},
    'auth.*': {'ops': ('fetch', 'get')},
    'auth.permission': {'ops': 'all'},
    'license.*': {'ops': 'all'},
    'users.*': {'ops': 'all'},
    'assessments.*': {'ops': 'all'},
    'trainingplans.*': {'ops': 'all'},
    'questionnaires.*': {'ops': 'all'},
    'workouts.*': {'ops': 'all'},
    'shop.*': {'ops': 'all'},
    'system.*': {'ops': 'all'},
    '*.*': {},
}
```

and everytime we update something in the admin, the object is still cached via API calls. 
Is there something I'm missing here?

**Comment by Suor** [comment]
That's something new. The only idea I have is that cacheops is not setup in admin or is disabled there somehow. Otherwise your will need to debug it.

**Comment by northkode** [comment]
i'm using out of the box setup based on the readme, yet it says that it should invalidate based on signals and the django admin does signals for saving and editing models.

Not sure what you mean, debug it.. we literally just did a pip install and added it to our configs

**Comment by Suor** [comment]
By debug I mean, go other how it works: do signals fire? are cacheops handlers called? are redis queries executed? I.e. what is happening at every separate step.

**Comment by Daveliuyabo** [comment]
I encountered a similar case where saving something in the Django admin detail page correctly invalidates the cache using cacheops. However, if I save in the Django admin list page (with list_editable enabled), it does not work.

**Comment by Suor** [comment]
Ok, another thing that comes to mind maybe admin is issuing mass updates or somehow else hit the [CAVEATS](https://github.com/Suor/django-cacheops?tab=readme-ov-file#caveats)?
