### ISSUE TITLE
conj keys always have -1 as expiration in redis 7

### ISSUE THREAD

**Issue by mariancraciun1983** [Suor/django-cacheops#475]
When using cacheops with Redis 7, the REDIS_4 code from [cache_thing.lua](https://github.com/Suor/django-cacheops/blob/master/cacheops/lua/cache_thing.lua#L53) is stripped away by the [load_script](https://github.com/Suor/django-cacheops/blob/master/cacheops/redis.py#L65) and we’re left with this part that sets the conj values and expiration:

```lua
-- ---
redis.call('sadd', conj_key, key)
redis.call('expire', conj_key, timeout, 'gt')
-- ---
```

- `sadd` will add/create the set with a default expiration of -1 
- `expire` uses `gt` option that won't have any effect if the expiration is`-1`.

The following code can be run to test this scenario:

```python
import uuid
from cacheops.redis import redis_client
key = str(uuid.uuid4())
print(redis_client.ttl(key)) # -2 # missing
print(redis_client.execute_command('sadd', key, "value1")) # 1
print(redis_client.ttl(key)) # -1 # no expiration
print(redis_client.execute_command('expire', key, 60*60, 'gt')) # False # not changed
print(redis_client.ttl(key)) # -1 # no expiration
```

**Comment by anton-puzyr** [comment]
I'm experiencing the same issue with Redis 7.2. Any advices?

**Comment by Suor** [comment]
I see, can anyone create a test for it?

**Comment by shubhamagrawal1906** [comment]
@Suor I have raised a pull request for the same issue as mentioned by @mariancraciun1983, please have a look at it.
