### ISSUE TITLE
Potential Concurrency Issue Leading to Cache Inconsistency in Multithreaded Environment

### ISSUE THREAD

**Issue by BoHuang-aspecta** [Suor/django-cacheops#478]
## Speculation

I would like to ask whether cacheops has the following concurrency issue.
For example, consider two threads, A and B. The operations occur in the following sequence:
1. Initial state is empty.
2. Thread A queries and finds no data, e.g.: `User.objects.get(id=1)`
3. Thread B writes data, e.g.: `User.objects.create(id=1, name='test')`
4. Thread B invalidates the cache but doesn’t actually clear anything.
5. Thread A writes the empty result (`DoesNotExist`) into the cache.
6. After this, all subsequent queries return empty data, resulting in inconsistency between the cache and the database.

## Actual Problem

In my system, I encounter a situation where multiple threads might simultaneously attempt to read and write the same user. After writing the user, I’m consistently unable to query the corresponding user until I manually clear the cache. Therefore, I suspect the scenario described above might be happening.
Here is an example code:

```python
class RemoteUserByPassportUserIdBackend(RemoteUserBackend):
    def authenticate(self, request, remote_user: str):
        """
        The user_id passed as ``remote_user`` is considered trusted.
        Try get or create user with thread safe.
        """
        if not remote_user:
            return
        user = None
        if not remote_user.isnumeric():
            return
        user_id = int(remote_user)
        if user_id <= 0:
            return

        # safeguards for multiple threads.
        try:
            user = UserModel.objects.get(user_id=user_id)
        except UserModel.DoesNotExist:
            if self.create_unknown_user:
                try:
                    create_param = {'user_id': user_id}
                    for field, func in settings.ASPECTA_GATEWAY_AUTH_SET_FIELDS.items():
                        create_param[field] = func(user_id)
                    user = UserModel.objects.create_user(**create_param)
                except IntegrityError:
                    try:
                        user = UserModel.objects.get(user_id=user_id)
                    except UserModel.DoesNotExist:
                        # After the error, the code always reaches here, causing the user to never be found.
                        logger.exception('get user failed after insert failed, user_id: %s', user_id)
                        return

        return user if self.user_can_authenticate(user) else None
```

## Speculated Solution
Since I cannot confirm if the described issue exists, and as this error in my system is difficult to reproduce, its effectiveness remains unverified.
If the described issue exists, it is speculated that the following solution might resolve it. During the second query, do not use the cache, and if the query succeeds, invalidate the erroneous cache.

```python
        """
        The user_id passed as ``remote_user`` is considered trusted.
        Try get or create user with thread safe.
        """
        if not remote_user:
            return
        user = None
        if not remote_user.isnumeric():
            return
        user_id = int(remote_user)
        if user_id <= 0:
            return

        # safeguards for multiple threads.
        try:
            user = UserModel.objects.get(user_id=user_id)
        except UserModel.DoesNotExist:
            if self.create_unknown_user:
                try:
                    create_param = {'user_id': user_id}
                    for field, func in settings.ASPECTA_GATEWAY_AUTH_SET_FIELDS.items():
                        create_param[field] = func(user_id)
                    user = UserModel.objects.create_user(**create_param)
                except IntegrityError:
                    try:
                        user = UserModel.objects.get(user_id=user_id).nocache()  # query with no cache
                        if user:
                            invalidate_obj(user)  # invalidate the error cache
                    except UserModel.DoesNotExist:
                        # After the error, the code always reaches here, causing the user to never be found.
                        logger.exception('get user failed after insert failed, user_id: %s', user_id)
                        return

        return user if self.user_can_authenticate(user) else None
```

**Comment by BoHuang-aspecta** [comment]
So, does this issue that I mentioned indeed exist? I will try to reproduce the problem and attempt to solve it using `lock = True`. THX

**Comment by Suor** [comment]
I don't understand what did this mean "Thread B invalidates the cache but doesn’t actually clear anything".

About whether there issue exists I am not sure, you can try to create a test using before_after library - there is already one test using it.

**Comment by BoHuang-aspecta** [comment]
> I don't understand what did this mean "Thread B invalidates the cache but doesn’t actually clear anything".
> 
> About whether there issue exists I am not sure, you can try to create a test using before_after library - there is already one test using it.

Because when Thread B invalidates the cache, Thread A's cache write operation hasn't completed yet. At that point, the cache is actually empty (assuming the initial state is empty).

In summary, could it happen that Thread B's cache invalidation occurs before Thread A writes to the cache, in a concurrent scenario?

**Comment by BoHuang-aspecta** [comment]
I reproduced this issue using a concurrent approach.

I tried to solve it using `lock = True`, but it didn’t completely resolve the issue. Some requests still couldn’t retrieve data and resulted in errors. However, it doesn’t seem to cause the previous irrecoverable problem.

By using the `invalidate_obj` approach mentioned above, it seems to have completely resolved the issue, and there are no more errors.

**Comment by Suor** [comment]
Actually looking a little bit more at problematic issue, it has concurrency issues outside of cache - the code is not have a transaction, doesn't set `._for_write = True` for initial `.get()`. Using `.get_or_create()` should solve this problem too.
