### ISSUE TITLE
How to enable caching for 'views' only

### ISSUE THREAD

**Issue by krasniy-1889** [Suor/django-cacheops#482]
I have a lot of other code besides the standard view classes. There is celery, services. There is a lot of code in them and nocache() is not an option. Writing cache() for 'views' is not an option either, there is a lot of code and pages. Is it possible to add for caching only a certain folder? Or make middleware that caches only if the request has a 'request' for example

**Comment by Suor** [comment]
You can write a middleware.

**Comment by krasniy-1889** [comment]
I need to disable caching for the rest of the project and only cache in a specific folder. Or maybe there is a class that enables caching for a single class. For example, CacheMixin. Which caches all requests in the methods of that class

`class TrackListView(BaseListView, CacheMixin):
    model = Track
    queryset = Track.objects.with_artists_and_album_and_place_in_top()  # type: ignore
    paginate_by = 50
    paginator_class = Fixed500Paginator
    template_name = "index.html"`

**Comment by Suor** [comment]
There is no mixin included, I saw people doing something like that, so it should not be too hard.
