### ISSUE TITLE
Publish latest changes to pypi to address Redis 7.* TTL issue

### ISSUE THREAD

**Issue by peteyb** [Suor/django-cacheops#487]
Hey @Suor,

We have recently upgraded our Google Memorystore Redis instance to v7.2 and are being impacted by TTL on keys returning -1, as noted in a few places:
https://github.com/Suor/django-cacheops/issues/475
https://github.com/Suor/django-cacheops/pull/477

I see these PRs have been merged but nothing published to PyPi since Oct 2023. 

Do you have a likely date by which a new version will be available via PyPi? 

NB. Ive converted our Poetry config to install straight from github but would much much prefer to use PyPi.

**Comment by Suor** [comment]
Released 7.1
