### ISSUE TITLE
Allow blank CACHEOPS setting when only using function caching

### ISSUE THREAD

**Issue by foobarbecue** [Suor/django-cacheops#53]
If enabling CACHEOPS using the @Cached() decorator and similar, it makes sense that the CACHEOPS setting would be left blank, right? At the moment you get an 
```
ImproperlyConfigured: You must specify non-empty CACHEOPS setting to use cacheops 
```
in that case.

**Comment by Suor** [comment]
Looks like this was erroneously closed.

The thing is the only part of cacheops that will work without redis connection is file cache. `@cached()` decorator stores cache in redis so it requires a connection. I don't know whether file cache should be just separated.

**Comment by Suor** [comment]
Looks like this was erroneously reopened as `CACHEOPS` is not about redis connection.

BTW `CACHEOPS_REDIS` is also lazily used now.
